### ISSUE TITLE
Add support for HTTPS

### ISSUE THREAD

**Issue by jasonmccallister** [craftcms/nitro#10]
This command would create a certificate for local development. We should look at using this library: https://github.com/FiloSottile/mkcert

```
nitro --machine=nitro-dev cert
```

For simplicity, we should create `*.test` certificates. Still need to research the feasibility of this.

**Comment by johndwells** [comment]
@jasonmccallister Is there any progress on this ticket? It's the one missing thing I'd love to see Nitro support! :)

**Comment by jasonmccallister** [comment]
@johndwells I am still looking into support for certificates. There are a few issues with generating certificates locally, mostly due to the Windows VM's changing IPs often.

**Transition to Caddy Server**

We are highly considering moving from NGINX to Caddy for a few reasons:

1. Caddy has an API so we can get more advanced features out of configuring sites (e.g. additional domains per site)
2. Caddy has built-in TLS (including internal/non-production) to make certificates valid locally (everyone likes the green lock)
3. The way we setup NGINX sites is kind.. of... horrible. Its a lot of remove and re-add right now. Switching to Caddy would make that process _alot_ more graceful.

Ideally, the only _noticeable_ change from NGINX to Caddy would be the sites having `https` and being redirected. 

**Trusting Virtual Machine Certificates on the Host Machine**

There would have to be a command similar to `nitro trust` to copy the CA certificate from the virtual machine and adding it to the host machine. With macOS, there is the `security` CLI that we can automate adding to the keychain. We would still need to look at integration with Windows and Linux.

Kind of a long answer for "we are working on it" but wanted to give you some background context on the thoughts behind it.

**Comment by johndwells** [comment]
Thanks @jasonmccallister for a look behind the curtain on this ticket! It's all beyond my area of expertise so I sadly cannot offer any help. :(. Anyway I appreciate knowing this ticket isn't forgotten. 👍

**Comment by jasonmccallister** [comment]
Support for HTTPS has been added in v2.Please see the documentation here for upgrading instructions https://craftcms.com/docs/nitro/2.x/
