### ISSUE TITLE
PHP memory_limit should be 256M

### ISSUE THREAD

**Issue by peteheaney** [craftcms/nitro#100]
The PHP memory limit seems to be set to 128M.  If this is supposed to be tuned for Craft, shouldn't it be set to 256M?

<img width="1171" alt="image" src="https://user-images.githubusercontent.com/234166/81114526-199f1880-8f1a-11ea-9340-8f28b88bb506.png">

**Comment by angrybrad** [comment]
Might as well turn it up to 11.  Or `512M`

**Comment by jasonmccallister** [comment]
We are setting the memory limit for fpm here: https://github.com/craftcms/nitro/blob/master/internal/cmd/init.go#L235. 

@peteheaney can you run `nitro restart` and check it again? I'm wondering if we just need to restart php-fpm during the install/setup.

**Comment by angrybrad** [comment]
Weird... just created a fresh machine and did a fresh Craft install and definitely seeing 256M

<img width="890" alt="CleanShot 2020-05-05 at 14 24 02@2x" src="https://user-images.githubusercontent.com/61869/81117524-18e79180-8edc-11ea-8119-a54f657eba91.png">

**Comment by angrybrad** [comment]
@peteheaney What version of PHP did you create the machine with?

Can you `nitro ssh` into the box and open up `/etc/php/(your PHP version)/fpm/php.ini`, then check what `memory_limit` is set to in there?

**Comment by peteheaney** [comment]
@jasonmccallister @angrybrad Sorry all, I've got Valet running on my machine as well and it looks like I was getting some conflict with that. I thought the site was being served by Nitro but it was actually Valet.  Sorry for the false alarm!

**Comment by angrybrad** [comment]
@peteheaney no worries! going to go ahead and close this out.
