### ISSUE TITLE
Download Craft via Nitro

### ISSUE THREAD

**Issue by JMKelley** [craftcms/nitro#101]
Just installed this and got it set-up. Really epic stuff. From recently building sites with the likes of the Ghost.org Command Line Tools. It'd be great if:

- Download Craft & Start Installation using `nitro install craft` or `nitro new *sitename*`.

Downloads latest craft and starts a new setup in Nitro. I know it's easy to download Craft via command line but it'd be a nice additional feature to have. Especially nice for new developers approaching Craft for the first time.

**Comment by brandonkelly** [comment]
We plan to do this post-1.0 ;)

**Comment by ademers** [comment]
Would this work with our custom Craft starter projects on Packagist?

**Comment by khalwat** [comment]
I sure hope so @ademers !

**Comment by jasonmccallister** [comment]
I'm preparing the next release that will ship with a new `nitro create` command to scaffold out a new Craft installation without PHP or Composer.

**Comment by khalwat** [comment]
@jasonmccallister Can that be used with custom scaffolding someone might have in their own git repo?

**Comment by ademers** [comment]
I have the same question as per https://github.com/craftcms/nitro/issues/101#issuecomment-624796386

**Comment by jasonmccallister** [comment]
@khalwat and @ademers technically it does not, but it will make adding this feature by appending an argument in a future release. The main goal of `nitro create` was to get people without PHP or Composer up and running ASAP. 

I imagine pointing to a Git repo would be similar, except using `git clone` versus downloading a `.zip` file (e.g. `nitro create https://github.com/jasonmccallister/craft-boilerplate`). This would not include installing composer however - as that depends on the host machine. I'm happy to work through this a little more in detail down the line though.

**Comment by jasonmccallister** [comment]
Support for downloading Craft CMS and a custom Git repository has has been added in v2 using the `nitro create` command. Please see the documentation here for upgrading instructions https://craftcms.com/docs/nitro/2.x/usage.html#creating-a-new-site-with-nitro-create

**Comment by JMKelley** [comment]
Awesome! Cheers guys.
