### ISSUE TITLE
`php restart` command

### ISSUE THREAD

**Issue by brandonkelly** [craftcms/nitro#106]
Would be cool if Nitro had a `php restart` command, which called `service php7.4-fpm restart` inside the VM – saving you from having to SSH into the VM (or remember the correct service name).

The service name would default to the default PHP version, but there could be a `-v` option that lets you specify a different version, and an `--all` flag for restarting all PHP versions.

**Comment by angrybrad** [comment]
Probably falls under https://github.com/craftcms/nitro/issues/57

**Comment by jasonmccallister** [comment]
I'm going to close this in favor of #57
