### ISSUE TITLE
Add information about providing multipassd full disk access.

### ISSUE THREAD

**Issue by simeon-smith** [craftcms/nitro#108]
When I initially installed multipassd and nitro on MacOS it would not mount when using `nitro add` or `nitro apply`. It gave me the following error.

```
mount failed: source "PROJECT_PATH" is not readable
```

I was able to determine that multipass did not have access to read the folders. Doing the following steps fixed that:

Go to:
  System Preferences
  Security & Privacy
  Full Disk Access

And then check multipassd to provide it full disk read access.

**Comment by angrybrad** [comment]
@simeon-smith did you install multipass using their native installer or through brew?

**Comment by simeon-smith** [comment]
@angrybrad I did it through their native installer.

**Comment by angrybrad** [comment]
Looks like this: https://github.com/canonical/multipass/issues/1389

Guessing you were trying to mount in one of these protected folders?

**Comment by simeon-smith** [comment]
Yes I was. Documents to be specific.

**Comment by jasonmccallister** [comment]
This would be good to have documented somewhere, but since this is a multipass thing, would this issue suffice as documentation?

**Comment by simeon-smith** [comment]
I feel like there might be enough people that run into this that it could warrant a mention. It affects some of the standard folders on MacOS and I know several developers that store their files in a location that this would affect.

**Comment by byronrode** [comment]
I came across this today, using an external drive, and didn't see this issue until after I had made mine: #148 

Multipass does add "multipassd" into the list of apps requiring access, but doesn't check it, as it requires authentication. In most cases (PHPStorm / TextMate etc) when you first attempt to open a folder on those drives, or protected folders it will ask for permission. Multipass will likely have to do the same, through their CLI.

**Comment by jasonmccallister** [comment]
@byronrode thank you, I think placing some documentation on the readme would be helpful. I have not ran into this issue yet since most of my sites are in `~/dev/<site>`. Having this documented on the README might be the best approach.

**Comment by jasonmccallister** [comment]
@mattstein can you take a stab at documenting this?

**Comment by mattstein** [comment]
Sure thing, @jasonmccallister!

**Comment by mattstein** [comment]
Noted in f05b3d7c6a3a6d1031c07b94b402e2f3cda09574.
