### ISSUE TITLE
Missing mysqldump?

### ISSUE THREAD

**Issue by bjerenec** [craftcms/nitro#109]
I got database backup error while trying to update Craft 2 site to Craft 3 site.
`2020-05-06 20:53:15 [-][-][-][error][craft\controllers\UpdaterController::actionBackup] Error backing up the database: The shell command "mysqldump <all the arguments>  failed with exit code 127: sh: 1: mysqldump: not found`.

Manually installing mysql-client-5.7 on VM solves this problem, but I guess `mysqldump` should be installed by default.

**Comment by angrybrad** [comment]
This will be solved via https://github.com/craftcms/nitro/issues/54 so going to go ahead and close this one.
