### ISSUE TITLE
`self-update` asks and ignores option to initialize the primary machine

### ISSUE THREAD

**Issue by brandonkelly** [craftcms/nitro#115]
At the end of `self-update`, this happens:

```
Nitro 1.0.0-beta.2 has been installed to /usr/local/bin
Initialize the primary machine now? [n]
$ 
```

(It answers its own question on whether to initialize the primary machine – I didn’t type <kbd>Return<kbd> at the prompt.)

Ideally the prompt shouldn’t even be output, since this is an _update_, not a fresh install of Nitro.

Maybe the prompt should be output depending on whether a primary machine already exists; and if not, actually pause and give the user a chance to answer.

This happened while upgrading from 1.0.0.-beta.1 to 1.0.0-beta.2, but is reproducible “updating” from 1.0.0-beta.2 to itself as well.

**Comment by angrybrad** [comment]
Resovled in https://github.com/craftcms/nitro/commit/33ce88f1425538070149d087c8cef2e0b6f5756f
