### ISSUE TITLE
`destroy` should prompt for confirmation.

### ISSUE THREAD

**Issue by brandonkelly** [craftcms/nitro#116]
Currently running `nitro destroy` immediately permanently destroys the machine. It should prompt for confirmation first.

```sh
$ nitro destroy
Are you sure you want to permanently destroy your nitro-dev machine? [n] $ y
Permanently removed nitro-dev
```

(While you’re in there, “removed” should be changed to “destroyed” in that last message.)

**Comment by angrybrad** [comment]
Resovled in https://github.com/craftcms/nitro/commit/274b94e3e7438db9619488f1b93a0cf6bbe215f5
