### ISSUE TITLE
`add` shouldn’t break if it can’t find a webroot

### ISSUE THREAD

**Issue by brandonkelly** [craftcms/nitro#121]
`nitro add` shouldn’t break if a webroot doesn’t exist yet.

(nginx doesn’t care if a server’s webroot doesn’t exist.)

Nitro version 1.0.0-beta.2

**Comment by jasonmccallister** [comment]
Just pushed this change to `develop`. It will default to web:

```
$nitro add
What should the hostname be? [examples] 
Unable to locate a webroot, setting to web
Where is the webroot? [web]
```

**Comment by jasonmccallister** [comment]
Resolved for the next release

**Comment by mach1media** [comment]
Just ran into this issue with Nitro v2.0.3.

My existing project's web root is `html` but Nitro didn't give me a prompt to specify... just throws an error.

```
 % nitro add
Adding site…
Enter the hostname [sitename.local]: sitename.local
  ✓ setting hostname to sitename.local
  ✓ adding site ~/sites/sitename.local
Error: unable to locate a webroot
```

**Comment by jasonmccallister** [comment]
@mach1media can you create a new issue and show the contents of that directory?
