### ISSUE TITLE
`apply` not applying changes to sites’ webroots

### ISSUE THREAD

**Issue by brandonkelly** [craftcms/nitro#122]
Running `nitro apply` is not applying changes to sites’ webroots.

#### Steps to reproduce

1. Add a site
2. Run `nitro edit` and change the site’s webroot to something else
3. Run `nitro apply`

#### Expected behavior

The new webroot should be reflected in `/etc/nginx/sites-available/<hostname>`, and nginx should have been restarted so the change is pulled in.

#### Actual behavior

No changes are made to `/etc/nginx/sites-available/<hostname>`.

**Comment by brandonkelly** [comment]
Even after manually editing the webroot in `/etc/nginx/sites-available/<hostname>`, the Xdebug config was still off, and thinking the files lived within the old webroot. I tried running `nitro xdebug configure` again but that didn’t help.

Destroyed and reinitialized the machine, with no changes to the config file, and now Xdebug is configured properly again.

**Comment by nfourtythree** [comment]
Think this is a duplicate of #113

**Comment by jasonmccallister** [comment]
Identified the issue and will be making a change to address this.

**Comment by brandonkelly** [comment]
Sorry, missed #113 @nfourtythree . Will close this as a duplicate, and added #113 to the 1.0 milestone.
