### ISSUE TITLE
`init` doesn’t add existing sites to hosts file

### ISSUE THREAD

**Issue by brandonkelly** [craftcms/nitro#123]
If you run `nitro init` for a machine that already has a matching config file in place, Nitro seems to do a good job creating the appropriate mounts and nginx configs, however it does not add the sites’ host names to `/etc/hosts`, so you still end up needing to run `nitro apply` afterward to make that change.

Nitro version: 1.0.0-beta.2

**Comment by jasonmccallister** [comment]
Going to add this in after the changes to support windows host editing.

**Comment by jasonmccallister** [comment]
Will be released in 1.0.0-beta.3.
