### ISSUE TITLE
Can't use localhost as Craft DB server host

### ISSUE THREAD

**Issue by rmales** [craftcms/nitro#125]
When I try to use `localhost` as the DB server host for a Craft site in Nitro it can't connect, `127.0.0.1` does work. Not sure if this could be something I've done wrong or a quirk of my set up.

**Comment by RyanRoberts** [comment]
I believe you need to use the machine's IP address, type `nitro info` in the CLI and you'll find it.

**Comment by RyanRoberts** [comment]
Here you go https://github.com/craftcms/nitro#connecting-to-the-database

**Comment by jasonmccallister** [comment]
@rmales that is intended behavior. Docker is running the databases in containers within the nitro virtual machine, so you will access them when inside the virtual machine using `127.0.0.1`. 

If you are looking to use a GUI like SequelPro you should use the IP address of the machine in the docs that @RyanRoberts provided.

**Comment by brandonkelly** [comment]
Going forward (Nitro 1.0 Beta 3+ and Craft 3.4.19+) Craft will stop asking for the DB server’s IP address, user & password, if running in Nitro.

<img width="829" alt="Screenshot 2020-05-11 at 17 35 05@2x" src="https://user-images.githubusercontent.com/47792/81625593-4043d000-93ae-11ea-92db-f174ff1fd8f7.png">

**Comment by watershed** [comment]
Just noting that the Nitro 2 version of Ryan's [doc link above](https://github.com/craftcms/nitro/issues/125#issuecomment-626220557) is now at: 

https://craftcms.com/docs/nitro/2.x/usage.html#connecting-to-the-database
