### ISSUE TITLE
https

### ISSUE THREAD

**Issue by RyanRoberts** [craftcms/nitro#130]
Apologies if this has been covered somewhere already but I can't find anything in the docs, issues or even the Nitro code.

Is it possible yet to secure a local site via Nitro?

**Comment by jasonmccallister** [comment]
@RyanRoberts we have #10 to cover this, but it is not very clear as to "what" that means in the title. I'm going to update that tickets title and that will be the best place to keep track.

**Comment by RyanRoberts** [comment]
Thanks. I swear I searched for "https" 🤔
