### ISSUE TITLE
Windows: 404 should 404 without Craft

### ISSUE THREAD

**Issue by mattstein** [craftcms/nitro#131]
If I create a bare site with Nitro and Craft isn’t installed, would-be 404s are still served by `index.php`.

I would expect to get some kind of 404 response for a non-existent route, whether it’s served by Craft or nginx.

**This behavior was identical between macOS and Windows in 0.10.13, but only happens in Windows now as of 1.0.0-beta.2.**

## Steps to Reproduce

1. Add a Nitro site for a web root containing only `index.php`.
2. Echo something sophisticated like `hello, there! 👋` from `index.php`.
3. Visit `hostname.site` and observe greeting as expected.
4. Visit `hostname.site/foo`, `hostname.site/foo.html`, `hostname.site/foo.php`, and observe greeting in each case rather than 404.

Repeat steps in macOS to observe expected behavior, which is that each case in step 4 returns the nginx 404 response.

## Setup

Compared with...
- Nitro 0.10.13 on macOS 10.15.4
- Nitro 1.0.0-beta.2 on macOS 10.15.4
- Nitro 1.0.0-beta.2 on Windows 10 Pro

**Comment by jasonmccallister** [comment]
@mattstein the recommended default for NGINX is to pass all 404's to index.php for PHP applications:

```
error_page 404 /index.php?$query_string;
```

When you add a site, we assume its Craft. Is this something we should remove or document? I'm not sure this is a bug since we added that configuration based on NGINX and PHP best practices?

**Comment by mattstein** [comment]
@jasonmccallister I might wandered into useless edge case territory. It seems ideal, for science, to use the default error page if PHP’s response doesn’t come with a 404 status. But I don’t know if that’s possible or even worth the time to work out. I won’t be offended if you slam this issue shut. :)

**Comment by jasonmccallister** [comment]
@mattstein I'm going to say this is an edge case and not a bug since we purposely set the NGINX config to pass 404s to index.php.
