### ISSUE TITLE
Support .gz for `nitro import`

### ISSUE THREAD

**Issue by khalwat** [craftcms/nitro#132]
Adding support for `.gz` compressed `.sql` files like generated by the Craft CMS backup command for direct importing via `nitro import`

Craft Scripts does this using [zcat](https://linux.die.net/man/1/zcat) ->

https://github.com/nystudio107/craft-scripts/blob/master/scripts/pull_db.sh#L80

This would be super convenient, and faster too.

**Comment by jasonmccallister** [comment]
Just cleaned this up a bit for the next release.
