### ISSUE TITLE
Changing MySQL Configuration Variables via my.cnf

### ISSUE THREAD

**Issue by bmorykon** [craftcms/nitro#133]
On a page with a large dataset, I ran into the error: Got a packet bigger than 'max_allowed_packet' bytes. 

So I tried updating that variable by modifying /etc/mysql/my.cnf which now reads:

```
!includedir /etc/mysql/conf.d/
[mysqld]
max_allowed_packet=64M
```

I couldn't figure out how to restart mysql from nitro (`sudo service mysql restart` doesn't work from within the machine), so I ran `nitro restart` from the host. After nitro restarts, max_allowed_packet size doesn't reflect the value set in my.cnf.

Any ideas?

**Comment by jasonmccallister** [comment]
@bmorykon the databases are created as Docker containers, which is why you are having issues setting a custom my.cnf. I'm going to work on adding this to the next beta and document how to include your custom config to a database.

**Comment by bmorykon** [comment]
Ah, got it. Thanks!

**Comment by jasonmccallister** [comment]
I'm wrapping up this feature and setting some defaults - will need to provide documentation on where/how to modify configurations but coming along pretty nicely!

**Comment by jasonmccallister** [comment]
I'm testing and writing some docs, closing this for beta 3.

**Comment by seandelaney** [comment]
Any update on using custom configuration?

Looking to set `innodb_strict_mode = 0` for a project.

**Comment by jasonmccallister** [comment]
Hi @seandelaney! This functionality was implemented with V1. Since we have moved V2 to Docker this will change how we implement the change. If you don't mind, can you create a new issue to request this feature so we can better track it?
