### ISSUE TITLE
`init` should automatically backup & restore all configured DBs for existing machines

### ISSUE THREAD

**Issue by brandonkelly** [craftcms/nitro#136]
If you run `init` for a machine that already exists, then any DBs listed in the config (#135) should be automatically backed up and then restored after the config has been fully applied.

Backups should probably live at `~/.nitro/backups/<machine>/<db>/<dbname>_YYMMDD_HHMMSS.sql` (or `.sql.gz` after #132).

Ex: `~/.nitro/backups/nitro-dev/mysql:5.7/craft3_200512_105130.sql`

**Comment by jasonmccallister** [comment]
dbs are automatically backed up when using `destroy`. The `init` command is not destructive so I think we can close this one out. I also updated the `db backups` command to use the path above.

**Comment by angrybrad** [comment]
Closing this out... if you run `nitro init` on a machine that already exists, you get:

> Machine "nitro-dev" already exists, skipping the init process
