### ISSUE TITLE
Nitro should copy SSH keys into the machines

### ISSUE THREAD

**Issue by brandonkelly** [craftcms/nitro#141]
Similar to how Homestead lets you specify the path to your SSH key via the `authorize` setting, and copies it into the VM. (See “Set Your SSH Key” section on https://laravel.com/docs/4.2/homestead.)

**Comment by lukeholder** [comment]
Not sure if this is helpful?: https://github.com/canonical/multipass/issues/965#issuecomment-591284180

**Comment by lukeholder** [comment]
https://github.com/canonical/multipass/issues/1413#issuecomment-596438518

**Comment by jasonmccallister** [comment]
I think during the init process we should prompt the user to add their SSH keys into the machine along with the option to run a command that will import the keys.

To @lukeholder's point, it should also add to the authorized keys, but my big thing is to keep this out of the config file. I'm thinking something along the lines of:

```bash
$ nitro init
# all the prompts
Should we add your SSH keys to the machine? [yes]
```

```bash
$ nitro keys
Should we add your SSH keys to the machine? [yes] yes
Ok, we have added your SSH keys into `nitro-dev`
```

**Comment by jasonmccallister** [comment]
We should list the keys to select similar to this: https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/eb3-init.html

**Comment by jasonmccallister** [comment]
Added the `keys` command to make this easy, should probably also prompt during init?
