### ISSUE TITLE
Use Caddy Server instead of NGINX

### ISSUE THREAD

**Issue by jasonmccallister** [craftcms/nitro#142]
We should consider the switch to [Caddy Server](https://caddyserver.com) for Nitro instead of using [NGINX](https://www.nginx.com). While NGINX is the most popular option for deployment, Caddy Server offers an API to create sites and easy local HTTPS. 

**Benefits**
- **API Driven:** We can remove the scripts inside of Nitro in favor of making an API request to the VM IP address from the CLI
- **Local HTTPS:** Caddy has an easy method to get local HTTPS support. When investigating #10, there are a lot of rough steps to getting this working. Caddy handles all the rough edges for us

**Cons**
- **NGINX Popularity:** NGINX is the most common deployment server, next to Apache, for Craft installations
- **Caddy Documentation:** Caddy documentation can be a little confusing, they are actively working on better docs, so there are potentially road bumps

Ultimately, Nitro is a tool for local development. While it might not be "same as production" it is a good idea to have it relatively similar.

**Comment by MisterMike** [comment]
I would love to see and test Caddy, but your point of making the Dev environment as similar as possible to the production field is a strong one. Having such a simple LetsEncrypt functionality makes Caddy really wave hands.

This also includes https, unfortunately (for you as a dev ). 

While not being comparable, how do Homestead or Flywheel achieve this?

**Comment by jasonmccallister** [comment]
We are looking at adding HTTPS support in #10, we will use Nginx over Caddy as most people are using Nginx in their real environments.
