### ISSUE TITLE
Update the documentation to include the database name for the Craft install

### ISSUE THREAD

**Issue by ConversioniaDev** [craftcms/nitro#143]
Maybe I missed something, but the documentation didn't include the name of the database created during the Nitro setup. I figured out that it's the root folder name.

**Comment by angrybrad** [comment]
Sorry, but I don't think I'm following. `nitro init` won't create a default database at all.  We probably should update https://github.com/craftcms/nitro#connecting-to-the-database to say you'll need to manually create a database. Is that what you're referring to?

**Comment by ConversioniaDev** [comment]
The name of the folder that I stored the craft install is "checkout" but I don't have a database named checkout. The only way I could install craft was to include checkout as the database name. I can connect to the database using my SQL client but I never created it.

**Comment by jasonmccallister** [comment]
@ConversioniaDev that makes sense, right now we do not create a database when you add a site, we certainly have talked about adding support for that use case.

In beta 3 you will be able to add databases easily with `nitro db add`.

**Comment by ConversioniaDev** [comment]
Sounds like a nice feature to be added. Looking forward to it.

**Comment by jasonmccallister** [comment]
@ConversioniaDev we tagged beta 3 which will make it easier to add databases. When a new machine (or adding a MySQL engine) there is a default database called nitro. 

I think we will eventually create a database during add but I’m not sure if will make it in 1.0.

**Comment by jasonmccallister** [comment]
Closing this out as the documentation discusses this here: https://craftcms.com/docs/nitro/usage.html#connecting-to-the-database
