### ISSUE TITLE
Multipass requires Full Disk Access on macOS

### ISSUE THREAD

**Issue by byronrode** [craftcms/nitro#148]
Hey folks, putting this here so you can keep a reference to it, or add it to the docs.

I use an external USB-C thumb drive to store all my dev work and I was trying to add a site, and kept getting a mount issue.

```
Webroot for "example.test" does not match, found "/etc/nginx/sites-available/example.test"
Mounting /Volumes/Code/Craft/example to nitro-dev
Adding site example.test to nitro-dev
mount failed: source "/Volumes/Code/Craft/example" is not readable
Error: exit status 2
```
At first I thought it might be related to Nitro, bBut after some investigation, I came across this issue: https://github.com/canonical/multipass/issues/1389 

Multipass (at this point) doesn't ask for Full Disk Access permissions during install, or for when attempting to mount a folder on an external drive, and the solution is to ensure `multipassd` is checked under "Full Disk Access" in System Preferences > Security.

**Comment by jasonmccallister** [comment]
This is a multipass access issue that needs to be documented, closing out in favor of #108. Thank you @byronrode!

**Comment by mattstein** [comment]
Noted in f05b3d7c6a3a6d1031c07b94b402e2f3cda09574..
