### ISSUE TITLE
Adding sites should add the site to the virtual machines hosts file

### ISSUE THREAD

**Issue by jasonmccallister** [craftcms/nitro#150]
> This is from troubleshooting with @onebrightlight on discord.

When trying to use browser sync inside of the VM, the proxy is not working because the virtual machine cannot reach `site-name.test`.

When a new site is added to the machine, we should add the following to the `/etc/hosts` file:

```
127.0.0.1    site-name.test
```

This will help with future tools like browser sync, etc.

**Comment by nordentwickler** [comment]
So after Adding the domain to the hosts-file on the vm, you get browsersync to work? I'm hustling with this exact problem, i want use browsersync in the vm as well. Could you give us more information ob your configuration? How to you handle the port-forwarding between your local machine and multipass/nitro and how did you config the browsersync, what did you use for proxy, open etc?

**Comment by simeon-smith** [comment]
I think if you set "disableHostCheck: true," for you webpack dev server you can get around this issue. I'm running webpack dev server on localhost:4000 with a proxy to my site url with this config. I'm pulling SITE_URL from the craft config so they are all the same.

```javascript
devServer: {
    contentBase: "./src/",
    watchContentBase: true,
    host: "0.0.0.0",
    disableHostCheck: true,
    hot: true,
    port: 4000,
    proxy: {
      "*": {
        changeOrigin: true,
        target: SITE_URL,
      },
    },
  },
```

**Comment by MaartenVenema** [comment]
The workaround supplied by @simeon-smith does not seem to work for me. I'm running the **feed me** plugin and I'm trying to get a feed from a local url and running into a curl error:  `Unable to reach //li.test/import/?key=getin. Message: cURL error 6: Could not resolve host: li.test (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://li.test/import/?key=getin` I guess this has to do with this issue.

**Comment by jasonmccallister** [comment]
Just an update, this has been resolved for v2 plus a lot of other fixes and additions. Only a handful of issues to resolve internally before its made public.

**Comment by MaartenVenema** [comment]
Thanks for the update @jasonmccallister. Good luck with the final stretch!

**Comment by jasonmccallister** [comment]
Hostnames and aliases are now set in the site container with v2. Please see the documentation here for upgrading instructions https://craftcms.com/docs/nitro/2.x
