### ISSUE TITLE
Not able to fetch and install php 7.4 on nitro apply

### ISSUE THREAD

**Issue by delixyr** [craftcms/nitro#152]
![php error](https://user-images.githubusercontent.com/4602841/82646806-1074a380-9bca-11ea-9601-7c04f6787734.jpg)
![php erroro 2](https://user-images.githubusercontent.com/4602841/82646813-136f9400-9bca-11ea-9a83-66cb4bd65818.jpg)

I get these error after running `nitro init` and  `nitro apply` on first machine I created. 
Works fine if i choose 7.2

**Comment by lukebailey** [comment]
seeing the same issue here

**Comment by jasonmccallister** [comment]
@delixyr and @lukebailey this might be related to #127. If your machine did not `init` properly you are going to have issues with the other commands as well. 

Can you run the following steps we discussed [here](https://github.com/craftcms/nitro/issues/127#issuecomment-626239432) to see if its a DNS problem with the virtual machine?

Also, can you attach the contents of `/var/log/cloud-init-output.log` and `/var/log/cloud-init.log`? 

Here are some steps to get those files from the machine to your host:

1. `multipass transfer nitro-dev:/var/log/cloud-init-output.log cloud-init-output.log`
2. `multipass transfer nitro-dev:/var/log/cloud-init.log cloud-init.log`

**Comment by delixyr** [comment]
> @delixyr and @lukebailey this might be related to #127. If your machine did not `init` properly you are going to have issues with the other commands as well.
> 
> Can you run the following steps we discussed [here](https://github.com/craftcms/nitro/issues/127#issuecomment-626239432) to see if its a DNS problem with the virtual machine?
> 
> Also, can you attach the contents of `/var/log/cloud-init-output.log` and `/var/log/cloud-init.log`?
> 
> Here are some steps to get those files from the machine to your host:
> 
> 1. `multipass transfer nitro-dev:/var/log/cloud-init-output.log cloud-init-output.log`
> 2. `multipass transfer nitro-dev:/var/log/cloud-init.log cloud-init.log`
@jasonmccallister 
[cloud-init.log](https://github.com/craftcms/nitro/files/4668134/cloud-init.log)
[cloud-init-output.log](https://github.com/craftcms/nitro/files/4668135/cloud-init-output.log)

**Comment by jasonmccallister** [comment]
@delixyr I think we have identified the issue, we are install `php-cli` on `init` which includes PHP 7.2 so we can install composer automatically. We discovered `php-cli` also install OCache by default. We are removing the `php-cli` in beta 5 and moving composer to `nitro install composer`. 

Hoping this resolves the issue.

**Comment by travisboss** [comment]
Having same issue, will wait for Beta 5.

**Comment by jasonmccallister** [comment]
Beta 6 was just released which should resolve this issue. I'm going to keep this open until we are sure but if you can update to the latest beta and try `nitro init`.

**Comment by jasonmccallister** [comment]
We just released Nitro 2 where we switched from Multipass to Docker and added a ton of new features. Please see the [announcement for more details](https://craftcms.com/blog/nitro-2).

This issue was specific to Multipass so we are going to close this out. Please see the documentation on upgrading from [Nitro 1](https://craftcms.com/docs/nitro/2.x/upgrade.html).
