### ISSUE TITLE
Private key permissions too open

### ISSUE THREAD

**Issue by michaelroper** [craftcms/nitro#154]
I used the `nitro keys` command to add my private key, but when I tried to use it from the VM, I got an error about the permissions on the key file being too open..

```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 0664 for '/home/ubuntu/.ssh/id_rsa' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
Load key "/home/ubuntu/.ssh/id_rsa": bad permissions
```

Not sure if this can be an easy fix by setting the permissions in the script that adds them, but `chmod 600 ~/.ssh/id_rsa` did the trick for me.

**Comment by jasonmccallister** [comment]
thank you @michaelroper, will be included in the next release.

**Comment by frankgo81** [comment]
chmod 600 ~/.ssh/id_rsa
this works like a charm. 
Thanks.
