### ISSUE TITLE
Missing 'unzip' command

### ISSUE THREAD

**Issue by michaelroper** [craftcms/nitro#159]
When doing a `composer update` from my nitro VM, I get the following error during the process:
```
As there is no 'unzip' command installed zip files are being unpacked 
using the PHP zip extension. This may cause invalid reports of corrupted 
archives. Besides, any UNIX permissions (e.g. executable) defined in the 
archives will be lost. Installing 'unzip' may remediate them.
```
Can that (and any other common utilities) be installed as part of the base install?

--
Environment: nitro 1.0.0-beta.7, Ubuntu 20.04

**Comment by jasonmccallister** [comment]
Thanks @michaelroper, I'm not sure why the unzip package is not added, its set as part of the init here: https://github.com/craftcms/nitro/blob/master/internal/cmd/config.go#L4

I'll spin up a new machine and verify its good to go.

**Comment by jasonmccallister** [comment]
I can't reproduce this on a new machine. Which version of PHP are you running?

**Comment by michaelroper** [comment]
Huh.. not sure whats going on then - none of those seem to be installed!
I created the machine yesterday with beta.6, updated today, and its using PHP 7.4..

**Comment by jasonmccallister** [comment]
@michaelroper can you try on the latest beta (beta 8)? Also, can you change the PHP version to 7.3 using `nitro edit` and then run `nitro apply -d` and provide the output?

**Comment by michaelroper** [comment]
Thanks Jason - updated to beta 9, and unzip is there, and `composer update` works without complaining now; though it does seem to take a lot longer than usual on the initial `Updating dependencies (including require-dev)` part, like at least a minute before it actually starts doing the updates.

Output from changing to 7.3 is:
```
nitro apply -d
Installing PHP 7.3 on nitro-dev
[exec nitro-dev -- sudo apt-get install -y php7.3 php7.3-mbstring php7.3-cli php7.3-curl php7.3-fpm php7.3-gd php7.3-intl php7.3-json php7.3-mysql php7.3-pgsql php7.3-zip php7.3-xml php7.3-soap php7.3-bcmath php7.3-gmp php-xdebug php-imagick blackfire-agent blackfire-php]
```
