### ISSUE TITLE
[FR] `nitro info` command

### ISSUE THREAD

**Issue by mattstein** [craftcms/nitro#16]
Single command for listing commonly-important (and unique) machine details.

Example:
```
nitro info

⚡️ running
Host IP Address: 0.0.0.0
Hostname(s): omgnitro.dev
MySQL: 
- username `root` 
- password `extrasecure`
- port 3306
MailHog UI: 0.0.0.0:8025

Use `nitro -h` for a full list of commands!
```

**Comment by clarknelson** [comment]
Have you thought of showing the directories added to the machine? Similar to 'valet list' where you can see all of the domains available.

**Comment by jasonmccallister** [comment]
@clarknelson we have the `nitro context` command that will display your entire config file. We have discussed adding databases and domains => folders in the `nitro info` command. Definitely on the plate though but we don't have a current FR/issue for that yet.
