### ISSUE TITLE
Update tip around recommended mount point

### ISSUE THREAD

**Issue by michaelroper** [craftcms/nitro#166]
Should this tip in the `readme.md` be updated to reflect the default suggested mount point being changed to `/home/ubuntu/sites`? 

> 💡 **Tip:** To avoid permission issues, we recommend you always mount folders into `/nitro/*` within the machine. 

https://github.com/craftcms/nitro/blame/master/README.md#L200

**Comment by jasonmccallister** [comment]
Yes it definitely should be updated!

**Comment by jasonmccallister** [comment]
Just updated this on `develop`. Planning a release soon.
