### ISSUE TITLE
Pass-through shell commands for matched site directories

### ISSUE THREAD

**Issue by michaelroper** [craftcms/nitro#167]
As discussed in #165, it would be great to be able to 'pass through' commands like the `nitro craft update' you mentioned, that when run will pass the current working directory, and run the command from the matching mounted site directory on the VM.

```
me@local-machine:~/Sites/my-website$ nitro exec composer update
==
ubuntu@nitro-dev:/home/ubuntu/sites/my-website$ composer update

me@local-machine:~/Sites/my-website$ nitro exec ./scripts/pull_db.sh
==
ubuntu@nitro-dev:/home/ubuntu/sites/my-website$ ./scripts/pull_db.sh
```

Alternatively, if that's not possible, it would be good to at least have some set commands for other common tasks, like `nitro composer-install` or `nitro composer-update`.

**Comment by jasonmccallister** [comment]
This will be released with the next version. We also added a `nitro queue` command that is _context aware_ to help running queues locally.

**Comment by jasonmccallister** [comment]
While this is not "technically" complete, the following commands are now "context-aware" and will detect if you are in a sites directory and should be used as an alternative:

1. `nitro ssh`
2. `nitro craft`
3. `nitro queue`
4. `nitro xon`
5. `nitro xoff`
6. `nitro share`

This should resolve this issue, let me know if we are good to close this one out 👍

**Comment by michaelroper** [comment]
Thanks Jason - I was just about to come back and find this issue and say that you absolutely NAILED IT! 🙌
