### ISSUE TITLE
An instance name is needed for either source or destination

### ISSUE THREAD

**Issue by jamiewade** [craftcms/nitro#174]
I'm getting this when trying to import an `.sql` file into one of my databases:

```
$ nitro db import C:/users/jamie/desktop/xxx.sql
Enter the database name to create for the import dbname
Uploading "xxx.sql" into "nitro-dev" (large files may take a while)...
An instance name is needed for either source or destination
Error: exit status 1
```

My Nitro server is up and running. I can get to my local site which is connected to the database, but as the database is empty it's prompting me to install Craft from scratch.

What am I doing wrong?

**Comment by jamiewade** [comment]
This seems to be an issue with the path to the `.sql` file. I was pointing to a file on my desktop:

`C:\Users\jamie\Desktop\xxx.sql`

However when I ran `nitro db import C:\Users\jamie\Desktop\xxx.sql` in [Hyper](https://hyper.is/), it didn't like that path and changed the command to:

`Error: Unable to locate the file "C:\\UsersjamieDesktopxxx.sql".`

Which of course failed. So I changed the path in Hyper which did seem to work (note the use of `/` instead of `\`, but that caused the error above.

Running:

`nitro db import C:\Users\jamie\Desktop\xxx.sql`

In Windows CMD does work.

**Comment by jasonmccallister** [comment]
Thanks for the report @jamiewade! I’m going to take a look at that soon. That’s strange that hyper is having that issue only. We break the file part using the host operating systems path separator and I’m not sure why Hyper is stripping the slashes... is it possible Hyper shell is using bash or WSL?

**Comment by jamiewade** [comment]
Cheers! Yeah it's strange indeed, but I don't think this is an issue with Nitro specifically. I'll see if there is anything I can do to stop Hyper doing what it's doing!

**Comment by jasonmccallister** [comment]
@jamiewade can you and I hop on a call and work through these issues? I’d like to see if we can narrow it down to something specific.

**Comment by jamiewade** [comment]
@jasonmccallister Sure, I'd be happy to. I'll drop you a message on Discord.

**Comment by jasonmccallister** [comment]
It seems to be occurring when running MINGW64 (e.g. Hyper.sh). The error occurs because the fileAbsPath has the path separators stripped.

https://github.com/craftcms/nitro/blob/master/internal/cmd/db_import.go#L40

**Comment by jasonmccallister** [comment]
We just released Nitro 2 where we switched from Multipass to Docker and added a ton of new features. Please see the [announcement for more details](https://craftcms.com/blog/nitro-2).

This issue was specific to Multipass so we are going to close this out. Please see the documentation on upgrading from [Nitro 1](https://craftcms.com/docs/nitro/2.x/upgrade.html).
