### ISSUE TITLE
Unlink x: Operation not permitted

### ISSUE THREAD

**Issue by jamiewade** [craftcms/nitro#175]
I deleted the contents of my `storage/runtime` and `storage/logs` folders for a Craft site using Nitro. Now when I request the site, I get this:

```
unlink(/home/ubuntu/sites/xxx/storage/runtime/mutex/ca1a8c7e23f25c20ac57ba3e1be16f0d.lock): Operation not permitted
```

Of course a permissions issue, but I'm not sure how to resolve it?

**Comment by jamiewade** [comment]
I've just realised my Windows path has been completely wiped after I run `setx path "%PATH%;%USERPROFILE%\Nitro"` from the [docs](https://github.com/craftcms/nitro#installation). It must be related to that.

**Comment by jasonmccallister** [comment]
@jamiewade It might be related to this: https://github.com/craftcms/cms/issues/4355

**Comment by jasonmccallister** [comment]
Closing this out as setting the mutex component resolved it. Thanks @jamiewade!

**Comment by jamiewade** [comment]
@jasonmccallister Unfortunately I'm still getting this issue when making Craft CMS requests on a Nitro instance (saving entries, saving Solspace Calendar events etc)

**Comment by mightyfineyall** [comment]
@jasonmccallister Having the same issue here, adding that to app.php didn't help. Unable to even create a single section within Craft running on Nitro - which makes it unusable.

**Comment by jasonmccallister** [comment]
@jamiewade and @mightyfineyall can either of you create a new ticket with your project configuration files, Craft CMS version, and the content of `nitro context`? That would help me troubleshoot the issue and see if I can identify a cause. Thank you!

**Comment by jasonmccallister** [comment]
I take that back, I thought I was reading a different ticket. I'm going to reopen but would still like to see those files if possible?

**Comment by jasonmccallister** [comment]
We just released Nitro 2 where we switched from Multipass to Docker and added a ton of new features. Please see the [announcement for more details](https://craftcms.com/blog/nitro-2).

This issue was specific to Multipass so we are going to close this out. Please see the documentation on upgrading from [Nitro 1](https://craftcms.com/docs/nitro/2.x/upgrade.html).
