### ISSUE TITLE
Twigpack config

### ISSUE THREAD

**Issue by jimhaakman** [craftcms/nitro#177]
In Twigpack I have a config that connects to the webpack dev server running on my mac. Is it possible to have an IP that connects to host machine? Like Homestead that has a special IP: `10.0.2.2`.

```
'devServer' => [
    'manifestPath' => 'http://10.0.2.2:8000/assets/',
    'publicPath' => 'http://localhost:8000/assets/'
],
```

Thanks.

**Comment by jasonmccallister** [comment]
@jimhaakman there is an IP address that is configured to your host machine already. By default, that IP should be `192.168.64.1`. 

In order to verify, you can take the following steps:

1. `nitro ssh`
2. `ip addr show`
3. The `enp0s2` should have an IP address similar to `192.168.64.21`
4. You can replace the last octet of the IP with `1` and reach your host machine (e.g. `192.168.64.21` would be `192.168.64.1`)

In your config, you would update it to look like this:

```
'devServer' => [
    'manifestPath' => 'http://192.168.64.1:8000/assets/',
    'publicPath' => 'http://192.168.64.1:8000/assets/'
],
```

**Comment by jimhaakman** [comment]
@jasonmccallister thank you for your reply. However I'm getting a connection refused when trying to access that host.

For instance (from `nitro ssh`) using ` curl http://192.168.64.1:8000/assets/manifest.json` my response is:

```
curl: (7) Failed to connect to 192.168.64.1 port 8000: Connection refused
```

Result from `ip addr show` is:
```
ubuntu@nitro-dev:~$ ip addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp0s2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 66:7d:3d:f7:b2:3a brd ff:ff:ff:ff:ff:ff
    inet 192.168.64.2/24 brd 192.168.64.255 scope global dynamic enp0s2
       valid_lft 83760sec preferred_lft 83760sec
    inet6 fe80::647d:3dff:fef7:b23a/64 scope link 
       valid_lft forever preferred_lft forever
3: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:30:3a:26:61 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:30ff:fe3a:2661/64 scope link 
       valid_lft forever preferred_lft forever
5: veth013fe48@if4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP group default 
    link/ether f2:82:7e:bf:05:85 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::f082:7eff:febf:585/64 scope link 
       valid_lft forever preferred_lft forever
```

**Comment by jasonmccallister** [comment]
@jimhaakman can you access port 8000 on your host machine to verify that it is running?

**Comment by jimhaakman** [comment]
@jasonmccallister yes it is running and accessible.

**Comment by jimhaakman** [comment]
I've found a fix for this. Instead of using `localhost` as a host in your webpack config use `0.0.0.0` instead. Now it's working.

**Comment by jasonmccallister** [comment]
That makes sense, glad you got it sorted out!

**Comment by umkasanki** [comment]
Does anyone have a working configuration for the Windows machine?
Thanks

**Comment by CharlieGentle** [comment]
@jimhaakman Any chance you can post your webpack dev server and twigpack settings? I'm struggling with the same issue. Thanks.

**Comment by ohtishkin** [comment]
> 
> 
> @jimhaakman Any chance you can post your webpack dev server and twigpack settings? I'm struggling with the same issue. Thanks.

sure 
[craft.zip](https://github.com/craftcms/nitro/files/5667153/craft.zip)

**Comment by ohtishkin** [comment]
> 
> 
> @jimhaakman Any chance you can post your webpack dev server and twigpack settings? I'm struggling with the same issue. Thanks.

Sure
[craft.zip](https://github.com/craftcms/nitro/files/5667478/craft.zip)

**Comment by tamlyn** [comment]
For Nitro 2.0 which is based on Docker, you can get Twigpack working with the following config, assuming you're running Webpack on the host.

In `twigpack.php`:

    'devServer' => [
        'manifestPath' => 'http://host.docker.internal:8080/',
        'publicPath' => 'http://localhost:8080/',
    ],

In `webpack.config.js`:

    devServer: {
      disableHostCheck: true
    },

**Comment by kevinmu17** [comment]
> For Nitro 2.0 which is based on Docker, you can get Twigpack working with the following config, assuming you're running Webpack on the host.

To what are you referring here as **host**?

**Comment by tamlyn** [comment]
@kevinmu17 I mean the Docker host or in other words your local machine outside of Docker.

**Comment by kevinmu17** [comment]
Thanks for clearing that up. What command are you using for running the dev server? I can't get it to work buy you pointed me in the right direction already, because it's now workingish ha!
