### ISSUE TITLE
Slow performance after sleep mode 

### ISSUE THREAD

**Issue by mmorkt** [craftcms/nitro#178]
Just started testing Nitro and I'm loving it. But I'm having trouble with slow load times running Nitro on MacOS. 
Tried two different Macbook Pros. Haven't tried Craft CMS yet only flat-file CMS systems. 

Load time DOMContentLoaded: 2.50 s
Tried bumping up CPU and memory but without any changes in the performance.

**Comment by mmorkt** [comment]
Seems like Nitro gets significantly slower after the Mac has been in sleep mode for some time.

**Comment by simeon-smith** [comment]
Using multipass to stop then then start the machine back up improved things for me. I didn't need to restart my whole machine.

**Comment by jasonmccallister** [comment]
@mmorkt and @simeon-smith this seems somewhat related to https://github.com/canonical/multipass/issues/1531. 

When the computer goes to sleep, it stops processing the mount and when its awake it appears to take a long time to get caught up. If this occurs again, you can run `nitro restart` to stop and start the machine, which would tell the mounts to "reinitialize".
