### ISSUE TITLE
Database Connection Timeout

### ISSUE THREAD

**Issue by aaronbest4** [craftcms/nitro#185]
### Description

Nitro is running and the server is loading Craft, however Craft is unable to connect to the DB. The credentials are correct in the .env file and I can connect to the DB using MySQL workbench on my host machine.

The following credentials are in the .env file:

```
DB_SERVER="172.17.17.7" << from nitro info
DB_USER="nitro"
DB_PASSWORD="nitro"
```

### Craft is throwing:

```
Database Connection Error – craft\errors\DbConnectException
Craft CMS can’t connect to the database with the credentials in config/db.php.

Caused by: Database Exception – yii\db\Exception
SQLSTATE[HY000] [2002] Connection timed out
in /home/ubuntu/sites/propertymentors/vendor/yiisoft/yii2/db/Connection.php at line 635
```

### Additional info

- Nitro version:  1.0.0-beta.10
- Multipass version: 1.3.0+win

**Comment by jasonmccallister** [comment]
@aaronbest4 when connecting to the database inside of the virtual machine you need to use the `127.0.0.1` address. The `172.17.17.7` is only when you are accessing the database from outside of the virtual machine (e.g. from the host OS using a database GUI).

Can you change the `DB_SERVER` to `127.0.0.1` and try again?

**Comment by aaronbest4** [comment]
Changing `DB_SERVER` to `127.0.0.1` has not fixed the problem, however, I think the issue is now different:

I am getting this error if the `DB_SERVER` is any IP:

```
Craft CMS can’t connect to the database with the credentials in config/db.php.

Caused by: Database Exception – yii\db\Exception
SQLSTATE[HY000] [1045] Access denied for user 'root'@'172.17.0.1' (using password: YES)
in /home/ubuntu/sites/tpm/vendor/yiisoft/yii2/db/Connection.php at line 635
```

Using:

```
DB_SERVER="127.0.0.1"
DB_USER="nitro"
DB_PASSWORD="nitro"
```

Changing the `USER `and `PASSWORD `in the `.env` file do not have an effect. Changing `DB_SERVER` to `localhost ` results in `No such file or directory` and a blank string triggers Craft to try and install.

**Comment by jasonmccallister** [comment]
@aaronbest4 can you provide the content of `nitro context` as well as use `nitro logs` and select the correct database to ensure its running?

**Comment by jasonmccallister** [comment]
@aaronbest4 I'm not sure why this is still occurring, can you run `nitro db restart` to restart the database and ensure its working?

If that does not do it I'm happy to hop on a call and work through this!

**Comment by jasonmccallister** [comment]
@aaronbest4 this might be related to a caching issue in an earlier version of Craft. Can you clear the cache directory and try again (if this is still an issue)?

**Comment by jasonmccallister** [comment]
We just released Nitro 2 where we switched from Multipass to Docker and added a ton of new features. Please see the [announcement for more details](https://craftcms.com/blog/nitro-2).

This issue was specific to Multipass so we are going to close this out. Please see the documentation on upgrading from [Nitro 1](https://craftcms.com/docs/nitro/2.x/upgrade.html).
