### ISSUE TITLE
Xdebug config

### ISSUE THREAD

**Issue by ryanpcmcquen** [craftcms/nitro#188]
### Description

What is the Xdebug config? The IP and the default port of 9000? That port isn't serving for me ...

### Steps to reproduce

1. Enable Xdebug.
2. Try to connect to Xdebug.

**Comment by ryanpcmcquen** [comment]
I see, it's some random ip that you can locate in the PHP info tab:
```/admin/utilities/php-info```

**Comment by jasonmccallister** [comment]
@ryanpcmcquen it should be setup by default for you.. were the IP addresses not matching?

**Comment by ryanpcmcquen** [comment]
That's correct:
`192.168.64.2` from `nitro info` and `192.168.64.1` for Xdebug.

**Comment by jasonmccallister** [comment]
The .1 should be the correct address, since it's running in a virtual machine. Is xdebug working for you with that IP?

**Comment by ryanpcmcquen** [comment]
Yes!
