### ISSUE TITLE
ImageMagick with webp support

### ISSUE THREAD

**Issue by mattstein** [craftcms/nitro#19]
Installing ImageMagick, specifically with webp support for PHP, can be annoying. It would be wonderful if Nitro came out of the box with the option to use GD or ImageMagick and modern presets. (Some hosts and provisioning services do this by default and it’s fabulous—many do not and it can be a struggle.)

The end goal is to run `php --info` and see `WEBP` included in the imagick extension’s supported formats:

```
$ php --info | grep 'supported formats'
ImageMagick number of supported formats:  => 230
ImageMagick supported formats => 3FR, AAI, AI, ART, ARW, AVI, AVS, BGR, BGRA, BGRO, BIE, BMP, BMP2, BMP3, BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CRW, CUR, CUT, DATA, DCM, DCR, DCX, DDS, DFONT, DJVU, DNG, DOT, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, EXR, FAX, FILE, FITS, FRACTAL, FTP, FTS, G3, G4, GIF, GIF87, GRADIENT, GRAY, GROUP4, GV, H, HALD, HDR, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, JBG, JBIG, JNG, JNX, JPE, JPEG, JPG, JPS, JSON, K25, KDC, LABEL, M2V, M4V, MAC, MAGICK, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPEG, MPG, MRW, MSL, MSVG, MTV, MVG, NEF, NRW, NULL, ORF, OTB, OTF, PAL, PALM, PAM, PANGO, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, PPM, PREVIEW, PS, PS2, PS3, PSB, PSD, PTIF, PWP, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGBA, RGBO, RGF, RLA, RLE, RMF, RW2, SCR, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, SVG, SVGZ, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIFF, VIPS, VST, WBMP, WEBP, WMF, WMV, WMZ, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, YCbCr, YCbCrA, YUV
```

This wiki has been helpful for me in the past:
https://github.com/rosell-dk/webp-convert/wiki/Installing-Imagick-extension-with-WebP-support

**Comment by jalendport** [comment]
Been a while since I launched a site with webp (😬), but here's what I think I've run in the past to install it:

```
apt-get install -y webp
```

**Comment by mattstein** [comment]
Sure @jalendport, but was it then magically available to ImageMagick, or was there pain and suffering required to convince ImageMagick to use it? My experience has usually been the latter. :)

**Comment by jalendport** [comment]
Hmm 'tis a great question. I've forgotten lol 😂 

I will report back on this thread the next time I go about setting up a new server with webp with a complete list of steps (unless this is resolved before then)...

**Comment by jasonmccallister** [comment]
Hmmm, I just checked the latest version of nitro and I see webp as a supported format. @mattstein or @jalendport can you confirm?

<img width="1588" alt="Screen Shot 2020-08-12 at 11 29 57 AM" src="https://user-images.githubusercontent.com/5354908/90034949-41c3b380-dc8f-11ea-9d2d-058aa17d3806.png">

**Comment by mattstein** [comment]
Yep, `WEBP` is listed in ImageMagick’s supported formats and a quick test in a template transformed a lovely `.webp` as expected. Thanks @jasonmccallister!
