### ISSUE TITLE
Default behavior when remove db

### ISSUE THREAD

**Issue by yanickrecher** [craftcms/nitro#190]
### Description
It's maybe not that important, but i just saw that.
When i try to remove a Database which was created with nitro, i will be asked if i really want to remove a specific db.

The Default Value is [no]. If i type "any chars" and hit ENTER the database will removed any way. 
I know the prompt didn't require a "yes" but it could be a bit more save. Otherwise the question if i really want to remove the db could also be omit.

### Steps to reproduce

1. nitro db remove
2. 3
3. ENTER

**Comment by jasonmccallister** [comment]
Thank you for reporting @yanickrecher, I'm going to add this to the list for the next release.

**Comment by jasonmccallister** [comment]
@yanickrecher I just tagged our prompt library with the latest version. We were looking for any characters in "yes". The library will now only check return if its "y" or "yes" and not any of the characters.
