### ISSUE TITLE
Invalid catalog name: 1046 No database selected

### ISSUE THREAD

**Issue by JMKelley** [craftcms/nitro#191]
### Description
Having run through the install, conducted `nitro add` and got Craft loading it's install page up. When trying to finish the install I get the dreaded `install failed - check logs` screen. When checking the logs I discovered it's because of the following error `Invalid catalog name: 1046 No database selected`. 

Followed the instructions to the letter, no mention of adding the DB name to `.env`? Should this be automatically setup during install? 

### Steps to reproduce

1. Install Nitro
2. Run `nitro add`
3. Follow Instructions.
4. Generate Security Key with Lastpass.
5. Try and Install Craft.
6. Craft Install Failed - No Database Selected.

### Additional info

- Nitro version: nitro 1.0.0-beta.10

```# The environment Craft is currently running in ("dev", "staging", "production", etc.)
ENVIRONMENT="dev"

# The application ID used to to uniquely store session and cache data, mutex locks, and more
APP_ID="CraftCMS--33cd16ff-1b4b-422d-8b2c-xxxxx"

# The secure key Craft will use for hashing and encrypting data
SECURITY_KEY="xxx"

# The database driver that will be used ("mysql" or "pgsql")
DB_DRIVER="mysql"

# The database server name or IP address
DB_SERVER="127.0.0.1"

# The port to connect to the database with
DB_PORT="3306"

# The name of the database to select
DB_DATABASE=""

# The database username to connect with
DB_USER="nitro"

# The database password to connect with
DB_PASSWORD="nitro"

# The database schema that will be used (PostgreSQL only)
DB_SCHEMA="public"

# The prefix that should be added to generated table names (only necessary if multiple things are sharing the same database)
DB_TABLE_PREFIX=""```

**Comment by JMKelley** [comment]
Fixed by adding `DB_DATABASE="nitro"` should be added to docs.

**Comment by mattstein** [comment]
Thanks @JMKelley! Updated the readme to mention the default database: https://github.com/craftcms/nitro#connecting-to-the-database
