### ISSUE TITLE
Add the ability to drop a database from the CLI

### ISSUE THREAD

**Issue by lukeholder** [craftcms/nitro#193]
### Description

Looking for the opposite of `nitro db add`

**Comment by jasonmccallister** [comment]
@lukeholder part of the work in the `db` command is to read all of the system databases. Are you expecting the same type of interaction?

1. `nitro db drop`
2. prompts for the engine if there are multiple
3. prompts for the database inside of the engine

**Comment by angrybrad** [comment]
`nitro db remove` was added in 1.0.0-beta.3
