### ISSUE TITLE
Windows: calling ./craft results in "Permission denied"

### ISSUE THREAD

**Issue by sa3dany** [craftcms/nitro#197]
### Description
With a clean slate (empty DB & fresh uninstalled Craft), calling ./craft inside the VM results in a permision denied error. Possibly related to mounting options of the craft directory.

### Steps to reproduce

```shell
ubuntu@nitro-dev:~$ cd sites/craft/

ubuntu@nitro-dev:~/sites/craft$ ./craft
-bash: ./craft: Permission denied

ubuntu@nitro-dev:~/sites/craft$ chmod +x craft
ubuntu@nitro-dev:~/sites/craft$ ./craft
-bash: ./craft: Permission denied

ubuntu@nitro-dev:~/sites/craft$ ll
total 208
...
-rw-rw-rw- 1 ubuntu ubuntu    655 Aug  4 13:47 craft
...
drwxrwxrwx 1 ubuntu ubuntu      0 Aug 10 14:01 web/
```

### Additional info

For reference, when I was using Vagrant I set `fmode=0774` when mounting the shared directory.

- Nitro version: 1.0.0-RC1.1
- Multipass version: 1.3.0+win

**Comment by sa3dany** [comment]
I just want to add that I can still call craft through php directly as a workaround. So this is not big issue.
```shell
ubuntu@nitro-dev:~/sites/craft$ php craft install/check
Craft is not installed yet.
```

**Comment by jasonmccallister** [comment]
@sa3dany the mounting system multipass uses under the hood is sshfs, that is strange that you are getting that error. I'm going to look into that issue.

**Comment by sa3dany** [comment]
I also get an exception when doing a database backup from the utilities section in the control panel:
```php
yii\base\Exception: Could not create backup: \
    The shell command "mysqldump ... nitro >> "...v3.5.2.sql"" failed with exit code 2: mysqldump: \
    [Warning] World-writable config file '/home/ubuntu/sites/craft/storage/runtime/temp/my.cnf' is ignored.
mysqldump: Got error: 2002: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) when trying to connect in /home/ubuntu/sites/craft/vendor/craftcms/cms/src/controllers/UtilitiesController.php:377
Stack trace:
#0 [internal function]: craft\controllers\UtilitiesController->actionDbBackupPerformAction()
#1 /home/ubuntu/sites/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#2 /home/ubuntu/sites/craft/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams()
#3 /home/ubuntu/sites/craft/vendor/craftcms/cms/src/web/Controller.php(181): yii\base\Controller->runAction()
#4 /home/ubuntu/sites/craft/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction()
#5 /home/ubuntu/sites/craft/vendor/craftcms/cms/src/web/Application.php(294): yii\base\Module->runAction()
#6 /home/ubuntu/sites/craft/vendor/craftcms/cms/src/web/Application.php(597): craft\web\Application->runAction()
#7 /home/ubuntu/sites/craft/vendor/craftcms/cms/src/web/Application.php(273): craft\web\Application->_processActionRequest()
#8 /home/ubuntu/sites/craft/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest()
#9 /home/ubuntu/sites/craft/web/index.php(22): yii\base\Application->run()
#10 {main}
```

I thought about opening a separate issue for this but it looks relating to mounting options for directories created by craft.

**Comment by jasonmccallister** [comment]
@sa3dany what does your .env contain?

**Comment by sa3dany** [comment]
```
WINDOWS_FS=1

ENVIRONMENT="dev"
APP_ID="CraftCMS--53cf255f-7f39-4a63-bb31-9f3615d51fc7"
SECURITY_KEY="nitro"
DB_DRIVER="mysql"
DB_SERVER="127.0.0.1"
DB_PORT=""
DB_DATABASE="nitro"
DB_USER="nitro"
DB_PASSWORD="nitro"
DB_SCHEMA="public"
DB_TABLE_PREFIX=""

PRIMARY_SITE_URL="http://craft.test"
```
```

**Comment by sidm1983** [comment]
@jasonmccallister I am having the same issue on Windows 10 Pro. Basically, I can't execute any craft CLI commands within the nitro VM by directly executing the `craft` file (adding `php` to the beginning works e.g. `php craft install/check`). All files seem to be stuck with a permission of 666 and I can't change the permission within the VM as I believe that is locked or set to read-only. I am using `nitro 1.0.0-beta.10` and `multipass  1.3.0+win`.

I also can't run any craft CLI commands on the windows side because the database connection string points to 127.0.0.1 which is for use within the nitro VM.

I also get errors if I try to do a craft update from within the control panel. I think this is also related to the permission issue above.

Here are the contents of my .env file:
```
ENVIRONMENT="dev"
APP_ID="<some-craft-generated-app-id>"
SECURITY_KEY="<some-security-key-here>"
DB_DRIVER="pgsql"
DB_SERVER="127.0.0.1"
DB_PORT="5432"
DB_DATABASE="nitro"
DB_USER="nitro"
DB_PASSWORD="nitro"
DB_SCHEMA="public"
DB_TABLE_PREFIX=""
DEFAULT_SITE_URL="http://portal-cms.test"
```
As you can see above, I don't have the `WINDOWS_FS=1` environment variable like @sa3dany does (not sure what it does and if I need it)

Any ideas? Is there any additional information or log file I can send you to help troubleshoot this issue? Please let me know.

Thank you! 😄

**Comment by angrybrad** [comment]
@sa3dany @sidm1983 

> ubuntu@nitro-dev:~/sites/craft$ chmod +x craft

chmod, chown (almost all permissions related commands) won't actually work inside of a VM where the host is Windows.

You can still see that here:

> -rw-rw-rw- 1 ubuntu ubuntu    655 Aug  4 13:47 craft

Where there the executable bit still isn't set.

> I just want to add that I can still call craft through php directly as a workaround. So this is not a big issue.

Yeah, that's the workaround. Going to update the docs shortly to reflect this.

> I also get an exception when doing a database backup from the utilities section in the control panel:

Yeah, essentially the same issue. Resolved it here for the next Craft release by moving where we store that temp file to the system temp dir (that is outside of the SSHFS mount) https://github.com/craftcms/cms/commit/550da44fa471f41d8411e5608ceb11a7403c3c1e
