### ISSUE TITLE
Unable to backup the database from Craft or CLI

### ISSUE THREAD

**Issue by RyanRoberts** [craftcms/nitro#198]
### Description

Using Nitro, I can't backup from the Craft Admin or CLI, but `nitro db backup` works. Here's the error log:

```
[-][1][5bfc5nf5mt7q99rhrt1mcrqob6][error][yii\base\Exception] yii\base\Exception: Could not create backup: The shell command "mysqldump --defaults-extra-file="/home/ubuntu/sites/client/storage/runtime/temp/my.cnf" --add-drop-table --comments --create-options --dump-date --no-autocommit --routines --default-character-set=utf8 --set-charset --triggers --no-tablespaces --single-transaction --no-data --result-file="/home/ubuntu/sites/client/storage/backups/client-rentals--2020-08-10-110337--v3.5.2.sql" client && mysqldump --defaults-extra-file="/home/ubuntu/sites/client/storage/runtime/temp/my.cnf" --add-drop-table --comments --create-options --dump-date --no-autocommit --routines --default-character-set=utf8 --set-charset --triggers --no-tablespaces --no-create-info --ignore-table=client.assetindexdata --ignore-table=client.assettransformindex --ignore-table=client.sessions --ignore-table=client.templatecaches --ignore-table=client.templatecachequeries --ignore-table=client.templatecacheelements --ignore-table=client.cache --ignore-table=client.templatecachecriteria client >> "/home/ubuntu/sites/client/storage/backups/client-rentals--2020-08-10-110337--v3.5.2.sql"" failed with exit code 127: sh: 1: mysqldump: not found in /home/ubuntu/sites/client/vendor/craftcms/cms/src/controllers/UtilitiesController.php:377
Stack trace:
#0 [internal function]: craft\controllers\UtilitiesController->actionDbBackupPerformAction()
#1 /home/ubuntu/sites/client/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#2 /home/ubuntu/sites/client/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams()
#3 /home/ubuntu/sites/client/vendor/craftcms/cms/src/web/Controller.php(181): yii\base\Controller->runAction()
#4 /home/ubuntu/sites/client/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction()
#5 /home/ubuntu/sites/client/vendor/craftcms/cms/src/web/Application.php(294): yii\base\Module->runAction()
#6 /home/ubuntu/sites/client/vendor/craftcms/cms/src/web/Application.php(597): craft\web\Application->runAction()
#7 /home/ubuntu/sites/client/vendor/craftcms/cms/src/web/Application.php(273): craft\web\Application->_processActionRequest()
#8 /home/ubuntu/sites/client/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest()
#9 /home/ubuntu/sites/client/public/index.php(22): yii\base\Application->run()
#10 {main}
```

### Steps to reproduce

Try to run a backup from Utilities, or update the CMS and allow it to backup the DB (I have to choose to skip backup).

### Additional info

May be related to #139

- Craft version: 3.5.2
- Nitro version: beta 10
- Multipass version: 1.3.0+mac

**Comment by jasonmccallister** [comment]
@RyanRoberts can you run `nitro ssh` and `which mysqldump` to verify that it is installed?

**Comment by RyanRoberts** [comment]
@jasonmccallister I get nothing returned :/

**Comment by jasonmccallister** [comment]
@RyanRoberts can you run the following in your terminal and attach it to this ticket?

1. `multipass exec nitro-dev -- cloud-init collect-logs`
2. `multipass transfer nitro-dev:/home/ubuntu/cloud-init.tar.gz cloud-init.tar.gz`

That will place the `cloud-init.tar.gz` file in the current directory, this contains logs on creating a new machine and will help troubleshoot if there was an issue during creation.

**Comment by RyanRoberts** [comment]
@jasonmccallister here we go… https://www.dropbox.com/t/NB0i70KfmowjS4fK

Thanks

**Comment by jasonmccallister** [comment]
@RyanRoberts ok I see what is happening here. You created this machine on May 9th correct (cloud-init logs start on that date)? There have been a lot of changes to nitro since then. I would recommend taking the following steps:

1. `nitro db backup` to save your databases in `~/.nitro/backups/nitro-dev/<backup.sql>`
2. `nitro destroy --skip-backup` which will delete the virtual machine and not perform a backup - since we manually performed the backup
3. Install the latest nitro version and multipass version
4. Run `nitro init` which will use your existing config and remount the sites 
5. Run `nitro nginx restart` and you should see a success message indicated the new API is working
6. Run `nitro db import ~/.nitro/backups/nitro-dev/<backup.sql>` for each of the databases you backed up
7. You should be able to see the sites using the domain name you setup (e.g. http://craft.nitro)

Let me know if that resolved your issue!

**Comment by RyanRoberts** [comment]
@jasonmccallister OK so after causing myself a headache this morning and borking an update to the site before running your above steps I finally fixed everything and your steps sort out the original problem 👍

Thanks!

**Comment by a-am** [comment]
@jasonmccallister I ran the steps above however `mysqldump` is still not installed. 
I followed the steps to create the logs: https://www.dropbox.com/s/bo4lmyehzkr3d58/cloud-init.tar.gz?dl=0

Multipass Version 1.5.0
Nitro 1.1.1

**Comment by jasonmccallister** [comment]
@a-am might be easier to install the tools manually. Try this:

1. `nitro ssh`
2. `sudo apt install -y mysql-client`

That should make the tools available in the virtual machine.
