### ISSUE TITLE
Error: nitro version

### ISSUE THREAD

**Issue by bencroker** [craftcms/nitro#199]
### Description

Running `nitro version` results in the version being displayed, followed by `Error: invalid character '<' looking for beginning of value`.

![Screenshot 2020-08-11 at 21 50 24](https://user-images.githubusercontent.com/57572400/89942393-c45f5b00-dc1c-11ea-922b-26d7690e03c8.png)

### Additional info

- Nitro version: 1.0.0
- Multipass version: 1.4.0 on Mac

**Comment by jasonmccallister** [comment]
@bencroker thanks! Looks like the IDE refactor got me with this change: https://github.com/craftcms/nitro/commit/b95315f95681865c8babf3ea67fb2982ae9a9ee2#diff-09efe290bb4b1b6f325778bbcc16ac5f.

I'll update this an push a fix soon, I had mix feelings about making a API request when running that command...
