### ISSUE TITLE
Add remote command to share application

### ISSUE THREAD

**Issue by jasonmccallister** [craftcms/nitro#2]
This would act similar to ngrok.io and create a randomly generated port to map to a machine and host.

```
nitro remote --host=example.test
```

**Comment by michaelrog** [comment]
Worth looking into: 

*[Expose](https://github.com/beyondcode/expose)* is "a beautiful, fully open-source, tunneling service, written in pure PHP."

docs: https://beyondco.de/docs/expose/introduction
repo: https://github.com/beyondcode/expose

Would be really cool to have a `nitro expose` command to automate [client configuration](https://beyondco.de/docs/expose/client/configuration), [SSL](https://beyondco.de/docs/expose/server/ssl), etc.

**Comment by ademers** [comment]
Would this allow us to log into the Craft CP without CORS issues? Thanks!

See: https://github.com/craftcms/cms/issues/4085

**Comment by AugustMiller** [comment]
I was recently testing some Stripe webhooks, and realized there was one additional bit required for basic Ngrok use:

```
ngrok http -hostname=some-reserved-subdomain.ngrok.io -host-header=my-site-name.test my-site-name.test:80
```

(The `-host-header` param was required so Nitro knew which virtual host to send traffic to!)

**Comment by jasonmccallister** [comment]
This was included with the v2 betas, closing this ticket out! Thanks everyone!
