### ISSUE TITLE
Tweak the default PHP config

### ISSUE THREAD

**Issue by benface** [craftcms/nitro#200]
I believe the default values for some of the php.ini options should be changed to match most Craft CMS dev workflows:

- `display_errors` should be set to `On`, which is the recommended value for development as per the comments in `php.ini`.
- `display_startup_errors` should also be set to `On`.
- `max_input_vars` should be set to `2000` or even `5000`, as `1000` is often too low when saving entries with lots of matrix fields (or the settings for such matrix fields).
- `post_max_size` (default value: `8M`), `upload_max_filesize` (default value: `2M`), `max_file_uploads` (default value: `20`) could all be at least doubled IMO (I personally set them much higher but I understand that too high is not good either). `2M` for `upload_max_filesize` in particular is really low.

**Comment by lindseydiloreto** [comment]
These all seem like reasonable defaults IMO, I probably would have asked for much higher limits. 😄

I especially agree with `max_input_vars = 5000`, and the highest possible memory limits.

**Comment by brettgullan** [comment]
+1 for increasing upload defaults. 
I tend to use values in the range of 16M-64M to allow for image uploads that can support various transformations. A retina resolution (2x) full-width image for a desktop breakpoint can easily exceed 3200px width. Which makes for some chunky master image sizes.

**Comment by jasonmccallister** [comment]
We just released 1.1.0 that adds `display_errors` to `iniset` and also enables `display_errors` on start up. I think we only need to add `display_startup_errors` to resolve this ticket, which we can do post 1.1.0,

**Comment by remcoov** [comment]
Yeah, +1, the `upload_max_filesize` is extremely low.

**Comment by jasonmccallister** [comment]
The defaults have been improved in v2 and there is a new `nitro iniset` command to tweak settings on a per site basis. Please see the documentation for further details - https://craftcms.com/docs/nitro/2.x/php-settings.html
