### ISSUE TITLE
The files in "vendor/bin" point to a path on the host, and therefore cannot be found

### ISSUE THREAD

**Issue by alinnert** [craftcms/nitro#203]
### Description

If I run `composer install` from inside Nitro (through a SSH connection from a Windows host) the files in the folder `vendor/bin` seem to be created in a weird state. They are symlinks but their target is a Windows path. Running `ll` prints the following (I've only replaced the actual project folder with `my-project`):

~~~
ubuntu@nitro-dev:~/sites/my-project/vendor/bin$ ll
total 20
drwxrwxrwx 1 ubuntu ubuntu  0 Aug 15 21:43 ./
drwxrwxrwx 1 ubuntu ubuntu  0 Aug 15 20:50 ../
lrwxrwxrwx 1 ubuntu ubuntu 83 Aug 15 20:49 composer -> D:/projects/my-project/website/vendor/composer/composer/bin/composer
lrwxrwxrwx 1 ubuntu ubuntu 79 Aug 15 20:49 jsonlint -> D:/projects/my-project/website/vendor/seld/jsonlint/bin/jsonlint
lrwxrwxrwx 1 ubuntu ubuntu 79 Aug 15 20:49 markdown -> D:/projects/my-project/website/vendor/cebe/markdown/bin/markdown
lrwxrwxrwx 1 ubuntu ubuntu 96 Aug 15 20:49 validate-json -> D:/projects/my-project/website/vendor/justinrainbow/json-schema/bin/validate-json
lrwxrwxrwx 1 ubuntu ubuntu 69 Aug 15 20:49 yii -> D:/projects/my-project/website/vendor/yiisoft/yii2/yii
~~~

But trying to access those files directly fails:

~~~
ubuntu@nitro-dev:~/sites/my-project/vendor/bin$ ll markdown
lrwxrwxrwx 1 ubuntu ubuntu 79 Aug 15 20:49 markdown -> D:/projects/my-project/website/vendor/cebe/markdown/bin/markdown

ubuntu@nitro-dev:~/sites/my-project/vendor/bin$ cat markdown
cat: markdown: No such file or directory
~~~

Running `composer install` also prints the following error (reformatted to make it more readable):

~~~
[ErrorException]
file_put_contents(/home/ubuntu/sites/my-project/vendor/bin/markdown): failed to open stream: No such file or directory

Exception trace:
()
  at phar:///usr/local/bin/composer/src/Composer/Installer/BinaryInstaller.php:167

Composer\Util\ErrorHandler::handle()
  at n/a:n/a

file_put_contents()
  at phar:///usr/local/bin/composer/src/Composer/Installer/BinaryInstaller.php:167

Composer\Installer\BinaryInstaller->installUnixyProxyBinaries()
  at phar:///usr/local/bin/composer/src/Composer/Installer/BinaryInstaller.php:161

Composer\Installer\BinaryInstaller->installSymlinkBinaries()
  at phar:///usr/local/bin/composer/src/Composer/Installer/BinaryInstaller.php:88

Composer\Installer\BinaryInstaller->installBinaries()
  at phar:///usr/local/bin/composer/src/Composer/Installer/LibraryInstaller.php:170

Composer\Installer\LibraryInstaller->ensureBinariesPresence()
  at phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php:147

Composer\Installer\InstallationManager->ensureBinariesPresence()
  at phar:///usr/local/bin/composer/src/Composer/Installer.php:313

Composer\Installer->run()
  at phar:///usr/local/bin/composer/src/Composer/Command/InstallCommand.php:122

Composer\Command\InstallCommand->execute()
  at phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php:245

Symfony\Component\Console\Command\Command->run()
  at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:835

Symfony\Component\Console\Application->doRunCommand()
  at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:185

Symfony\Component\Console\Application->doRun()
  at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:281

Composer\Console\Application->doRun()
  at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:117

Symfony\Component\Console\Application->run()
  at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:113

Composer\Console\Application->run()
  at phar:///usr/local/bin/composer/bin/composer:61

require()
  at /usr/local/bin/composer:24
~~~

Ultimately, this prevents some features and functions to work correctly, like updating Craft to a newer version.

Also, if I try to open that file on the host in VS Code I get the following error:

~~~
Unable to open 'composer': Unable to read file 'd:\Projects\my-project\website\vendor\bin\composer' (EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open 'd:\Projects\my-project\website\vendor\bin\composer').
~~~

Trying to open that file in Windows Notepad prints (roughly translated): "The syntax of the filename, directory name or volume label is wrong."

### Steps to reproduce

On a Windows host:

- run `nitro ssh`
- cd into your project folder
- run `composer install`

### Additional info

- Host: Windows 10 2004
- Nitro version: 1.0.1
- Multipass version: 1.4.0+win

**Comment by alinnert** [comment]
Small update on this one:

Running `composer install` from the host system works. But updating Craft from the UI still fails, because it still tries to run Composer inside Nitro and causes the problems mentioned above (probably if it tries to update one of the binaries).

**Comment by jasonmccallister** [comment]
@alinnert out of curiosity, did you set the file mutex as described in the Windows 10 docs? https://craftcms.com/docs/nitro/usage.html#adding-sites

**Comment by alinnert** [comment]
I don't know if I did that correctly. I read the one box below and added `IS_WINDOWS=true` to my `.env`. Now that you mention it, I cannot tell if that's a replacement for the entire `mutex` setting or just for the single hardcoded `true` value and I still have to add that block but read the value from my `.env` manually.

**Comment by Etsur** [comment]
Having the same issue

**Comment by alinnert** [comment]
@jasonmccallister I just tried it again (removed and re-added the db, reverted all project files) but with the `isWindows` option set to `true` exactly like in the docs. Sadly, it doesn't resolve the problem. `composer install` only works from the host system, updating Craft fails.

**Comment by Etsur** [comment]
@alinnert same. I did a complete fresh setup, might abandon Nitro until a better fix comes along.

**Comment by jasonmccallister** [comment]
@alinnert I'm going to have to spend some time diving into that issue. I don't use Windows too often but I definitely want to get this resolved.

**Comment by sa3dany** [comment]
I've ran into similar issues when running `composer install` inside the VM while working with Vagrant too recently. I haven't migrated to nitro yet since I have some sites using Vagrant and I need Hyper-V off for some VMs.

Anyway I gave up and just changed the `vendor` directory path to somewhere outside the shared folder between the vm and the host. I've chosen `/usr/local/lib/craft`.

> Make sure the directory you chose exists and has the [necessary permissions](https://craftcms.com/docs/3.x/installation.html#step-2-set-the-file-permissions).

- I've overridden the [`CRAFT_VENDOR_PATH`](https://craftcms.com/docs/3.x/config/#craft-vendor-path) PHP constant in `craft` (CLI) and `web/index.php` to  point to the new location
- Added the [`vendor-dir`](https://getcomposer.org/doc/06-config.md#vendor-dir) config options in composer.json, also pointing to the new location

This way I still keep `composer.json` in version control, but when doing `composer install/update` all the dependencies will be installed outside the synced vm mount.

I haven't tested this extensively yet, but I was able to run `composer install` then install craft with no issues.

**Comment by jasonmccallister** [comment]
We just released Nitro 2 where we switched from Multipass to Docker and added a ton of new features. Please see the [announcement for more details](https://craftcms.com/blog/nitro-2).

This issue was specific to Multipass so we are going to close this out. Please see the documentation on upgrading from [Nitro 1](https://craftcms.com/docs/nitro/2.x/upgrade.html).
