### ISSUE TITLE
Sessions End Up with Odd Behavior after Stop and Start

### ISSUE THREAD

**Issue by simeon-smith** [craftcms/nitro#204]
### Description

When I've had to restart my physical computer and then restart Nitro their ends up being weird behavior related to this issue in Craft Commerce https://github.com/craftcms/commerce/issues/1634.

After restarting my computer and Nitro the user will remain logged in. However, it causes the cart in Craft Commerce to be recreated any time you try to use it. These carts are assigned to the user but they don't get retrieved and instead get recreated. When I log out or clear cache/session/cookies in browser this issue goes away. I can't confirm that this happens ever time I restart my computer. It do know that doesn't happen every time I stop and restart nitro. I also can't confirm if this is only happening when Nitro gets shut down in an ungraceful way. This morning my computer had restarted due to an error and it was an issue. Will update if I can provide more precise details about the exact situation in which this happens.

### Steps to reproduce

1. Log into Craft that has Craft Commerce
2. Add something to the cart.
3. Restart computer.
4. Start nitro again.
5. You should still be logged in.
6. The item you added to the cart in step 2 will not be there.
7. Add another item to the cart.
8. Refresh.
9. The item from step 7 will not be there.

### Additional info

- Nitro version: 1.0.0-beta.10
- Multipass version: 1.3.0+mac
- Craft version: 3.5.5
- Commerce version: 3.2.2.1

**Comment by angrybrad** [comment]
@simeon-smith can you update to the official Nitro 1.0 release and Multipass 1.4.0 and see if you're still able to reproduce with that?

**Comment by angrybrad** [comment]
As a follow-up, I tried this on the latest of everything and was with you up until your step 6. The item I added was still there in the cart.

**Comment by jasonmccallister** [comment]
@simeon-smith how is Craft configured to use session? Are you using the redis or default file system?

**Comment by simeon-smith** [comment]
@angrybrad I updated and the issue seems to have disappeared. I'll update you here if it happens again but am closing for now.

@jasonmccallister I'm using the default session setup.
