### ISSUE TITLE
SSH error status 2 using Nitro (suddenly)

### ISSUE THREAD

**Issue by dglovernfa** [craftcms/nitro#205]
### Description

I was working all week no issue, and all day today, when suddenly it stopped. Receiving the following error:

- ssh connection failed: 'Timeout connecting to nitro-dev.mshome.net'
- Error: exit status 2

That error happens when I try to run Nitro Info, Start, Refresh, etc..

When I run Nitro Stop, it says "Stopped nitro-dev". When I follow that with Nitro Start, it says "The nitro-dev machine is already running.".

Per discussion w/ @angrybrad I've installed the latest Multipass and Nitro, though sadly that did not resolve the issue.

I have confirmed that Internet Sharing (Windows 10) is not enabled.

### Additional info

- Nitro version: 1.0.1
- Multipass version: 1.4.0

**Comment by jasonmccallister** [comment]
@dglovernfa ok, I have my suspicions on whats causing this based on the conversation you had with Brad on Discord. There is a strange setting on Windows that has something to do with internet sharing where the IP address in the hosts.ics does not match the IP address on the hypervisor. 

Next time this occurs, can you run the following?

1. `multipass info --all` and record the IP address of the `nitro-dev` machine
2. The IP address located in the hosts.ics file (first link related to the .ics file https://www.hexacorn.com/blog/2018/03/31/the-little-known-i-think-secret-of-hosts-ics/)

Those IP addresses should not match and that is the issue. I think the ultimate resolution is to completely disable internet sharing, but that feels like it only takes affect _some_ of the time.

**Comment by dglovernfa** [comment]
Thanks for the response @jasonmccallister. I'll keep an eye and report back if this happens again. I have been having more instances of Nitro just up and stopping at (seemingly) random, but so far beyond this reported instance I have been able to get back up and running with what I normally have to do when I boot my PC:

`nitro stop`
`nitro start`
`nitro apply`
`nitro info` (grab the IP and add to .env for db connection)

**Comment by jasonmccallister** [comment]
We just released Nitro 2 where we switched from Multipass to Docker and added a ton of new features. Please see the [announcement for more details](https://craftcms.com/blog/nitro-2).

This issue was specific to Multipass so we are going to close this out. Please see the documentation on upgrading from [Nitro 1](https://craftcms.com/docs/nitro/2.x/upgrade.html).
