### ISSUE TITLE
upload_max_filesize is not being set

### ISSUE THREAD

**Issue by jasonmccallister** [craftcms/nitro#207]
### Description

Referencing this comment (https://github.com/craftcms/nitro/issues/201#issuecomment-678267068) the upload_max_filesize is not being set to the provided value.

### Steps to reproduce

1. `nitro php iniset upload_max_filesize 20M`
2. `nitro php iniget upload_max_filesize`

### Additional info

- Nitro version: 1.0.1
- Multipass version: 1.4

**Comment by sa3dany** [comment]
It is actually being set (confirmed inside vm) but `nitro php iniget upload_max_filesize` is not reporting updated value for some reason.

**Comment by jasonmccallister** [comment]
@sa3dany I just confirmed this and pushed a bug fix for `iniset`. I found the issue with `iniget` and looking at the best option for resolving that as well.

**Comment by mmorkt** [comment]
@jasonmccallister is there any solution or workaround for this? Got the same problem with max_input_vars.

```
[User] ~ % nitro php iniset max_input_vars 2000
Successfully changed the ini setting for max_input_vars to 2000

[User] ~ % nitro php iniget max_input_vars
The setting "max_input_vars" is currently set to 1000
```

PHP-info shows that max_input_vars = 1000
Running the latest Multipass 1.4, Nitro 1.0.1 and updated the machine

**Comment by harryfk** [comment]
Same issue here, also on the latest versions, upgraded from one of the early betas.

**Comment by harryfk** [comment]
@mmorkt @jasonmccallister Any idea how I would set a PHP variable manually? I tried editing the `php.ini` inside the VM directly, restarted everything, but no dice (in `/etc/php/7.4/cli/php.ini`).

**Comment by jasonmccallister** [comment]
@mmorkt I'm preparing a release with a lot of changes around `php iniget` and `php iniset` that will resolve these issues. I think the release will go out tomorrow when I am done giving it the once over.
