### ISSUE TITLE
Connection refused on Xdebug.

### ISSUE THREAD

**Issue by ryanpcmcquen** [craftcms/nitro#208]
### Description
```
λ nitro -d xdebug on
Error: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 192.168.65.2:50051: connect: connection refused"
```

### Steps to reproduce

1. Enable xdebug.

### Additional info

- Nitro version: 1.0.1
- Multipass version: 1.4.0

**Comment by ryanpcmcquen** [comment]
It's worth noting that Xdebug worked perfectly before, I did just update Nitro, so that may be related? I also updated the packages on my container:
```sudo apt-get update && sudo apt-get dist-upgrade -y```

**Comment by ryanpcmcquen** [comment]
I noticed that all the ips for the Nitro machines went from `192.168.64.x` to `192.168.65.x` ... not sure if that is related.

**Comment by jasonmccallister** [comment]
@ryanpcmcquen I am assuming that you are running Windows? The IP address from the hypervisor will change more than it does/should on other OS's. If you configured the XDebug to use the IP, try switching it to the hostname and then updating your hosts files to point to the new IP address.

**Comment by ryanpcmcquen** [comment]
I am on Mac OS, should I be modifying `/etc/php/7.4/mods-available/xdebug.ini` or something else?

**Comment by ryanpcmcquen** [comment]
It seems like `nitro xdebug on` completely ignores that file @jasonmccallister. I even tried rebooting and restarting `php7.4-fpm`.

**Comment by ryanpcmcquen** [comment]
I had to rebuild the entire machine:
```
multipass delete --all -p
nitro init
```

**Comment by jasonmccallister** [comment]
@ryanpcmcquen if the IP address changed and the hosts file was updated, it should have worked. That is strange that it did not. If this occurs again I would be happy to hop on a call to troubleshoot and see if we can resolve.
