### ISSUE TITLE
Nitro unable to edit hosts file (requires elevated privileges)

### ISSUE THREAD

**Issue by yoroshikun** [craftcms/nitro#213]
### Description
As the title describes, nitro is unable to edit the hosts file on a linux system without the use of elevated privileges.
Nitro attempts to escalate the permissions by asking for sudo, however by escalating to sudo user nitro then attempts to read the nitro configuration from the wrong place (it does not exist in the sudo user, but under the current user) which returns the following error.

```bash
nitro apply
Applied changes from $HOME/.nitro/nitro-dev.yaml
<attempts sudo here>                        
There are no sites in the config file.
```

### Steps to reproduce

1. Add a new site to the nitro config (either though `nitro add`or directly with the 
2. Site is not added to /etc/hosts

### Additional info

- Nitro version: 1.0.1
- Multipass version: 1.4.0

### Possible solution
Ensure that even in elevated user, that the config is read from the user that initially called the command.

### Workaround
As a work around for now you can edit the /etc/hosts file directly with any text editor you like.

```bash
sudo nano /etc/hosts
```
And add a new entry anywhere with the IP Address gathered with `nitro info`

```
# Nitro
# IP  HOST
XX.57.78.XX craft.test
```

**Comment by jasonmccallister** [comment]
@yoroshikun I can reproduce this problem on my setup as well. 

When you run `nitro apply`, it will try to edit the hosts file again. The command to modify hosts is hidden but it is `nitro hosts`. We had to make some changes for that command on Windows machines and apparently it broke linux host editing.

I'm going to see if there is a quick fix in the mean time. However, to ignore editing the hosts file, you can set the `NITRO_EDIT_HOSTS` environment variable to `false` ([documented here](https://craftcms.com/docs/nitro/advanced.html#nitro-edit-hosts)).

I think the work around is to add a flag to the config file on the `hosts` command which will hard code which config file to use, regardless of the user calling it.

**Comment by jasonmccallister** [comment]
I just pushed this https://github.com/craftcms/nitro/commit/e4c4581d3ea68cc31484fadea85977db5b23d53e to `develop` and that should resolve the issue. I'm going to wrap up some features for the next release and then test it on a linux machine to verify.

**Comment by jasonmccallister** [comment]
@yoroshikun I just tagged 1.1.0 which should resolve this for you. I will be testing on my ubuntu machine asap.

**Comment by yoroshikun** [comment]
@jasonmccallister What was the expected workflow? I have upgraded nitro to 1.1.0 and tried adding a new site however have encountered the same error

```
❯ nitro add
Enter the hostname [site] site.test
Enter the webroot [web] 
Added site.test to config file
Apply changes from config? [yes] yes
Mounting ~/share/dev-universal/site to nitro-dev
Adding site site.test to nitro-dev
Applied changes from /home/user/.nitro/nitro-dev.yaml                        
[sudo] password for user:         
There are no sites in the config file.
``` 

```
❯ nitro version
nitro 1.1.0
```
```
❯ nitro apply
Applied changes from /home/user/.nitro/nitro-dev.yaml
# looks like it sudos here
There are no sites in the config file.
```
Some system info if it helps
![image](https://user-images.githubusercontent.com/1892447/96075813-663c4600-0ef3-11eb-99ce-4d91a958a7b9.png)

**Comment by ajanec01** [comment]
Just a side note, if nitro is set to edit the hosts file it removes the IPs and hostnames entered manually when you apply any changes, e.g. removing one site removes all nitro sites from the host file.

**Comment by jasonmccallister** [comment]
The next update will resolve this issue with editing the hosts file and will introduce a custom "block" for Nitro to read from which also will ensure we only _touch_ what Nitro knows about.

Here is the hosts file from my machine with the changes:

```
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1        localhost
255.255.255.255  broadcasthost
::1              localhost

127.0.0.1        kubernetes.docker.internal
127.0.0.1        kubernetes.docker.internal
# Added by Docker Desktop
# To allow the same kube context to work on the host and the container:
127.0.0.1 kubernetes.docker.internal
# End of section

# <nitro>
<ip-addr>	id.craftcms.test plugins.craftcms.test api.craftcms.test composer.craftcms.test plugins-dev.nitro
# </nitro>
```

**Comment by jasonmccallister** [comment]
We released v2 with a greatly improved host editing capability and a transition to a Docker backend without the config. Please see the documentation for further details and an upgrade guide - https://craftcms.com/docs/nitro/2.x/
