### ISSUE TITLE
Failed to open redis DB connection 

### ISSUE THREAD

**Issue by a-am** [craftcms/nitro#214]
### Description
I keep running into error.  I have the `yiisoft/yii2-redis` package installed.

#### Error Output
```
Database Exception – yii\db\Exception
Failed to open redis DB connection (tcp://127.0.0.1:6379, database=0): 111 - Connection refused
Error Info: Connection refused
```
#### App.php config file.
```php
use craft\helpers\App;

return [
    'components' => [
        'deprecator' => [
            'throwExceptions' => YII_DEBUG,
        ],
        'redis' => [
            'class' => yii\redis\Connection::class,
            'hostname' => getenv('REDIS_HOSTNAME'),
            'port' => getenv('REDIS_PORT'),
            'database' => getenv('REDIS_DEFAULT_DB'),
        ],
        'cache' => [
            'class' => yii\redis\Cache::class,
            'defaultDuration' => 86400,
            'keyPrefix' => App::env('APP_ID') ?: 'CraftCMS',
        ]
    ],
];
```

#### Environment Vars for Redis
```env
# Redis settings
REDIS_HOSTNAME=127.0.0.1
REDIS_PORT=6379
REDIS_DEFAULT_DB=0
```

When I do try to access `nitro redis` I get this output in the terminal `bash: redis-cli: command not found`.  Is it possible redis never installed?

### Steps to reproduce

1. Accessing site via `http://sitename.test/admin`

### Additional info

- Nitro version: 1.0.1
- Multipass version: 1.4.0

**Comment by jasonmccallister** [comment]
@a-am that is strange it did not install. Can you run `nitro ssh` and run `sudo apt install redis`. That should resolve it for you. 

Did you by chance install nitro from a beta version?

**Comment by a-am** [comment]
@jasonmccallister Installing Redis worked, thank you.
I did install Nitro from the beta version.

**Comment by benface** [comment]
@jasonmccallister I am experiencing this with Nitro 2. More specifically, when trying to install Craft in an empty database:

```
/app $ ./craft install
Email: **********@icloud.com
Exception 'yii\db\Exception' with message 'Failed to open redis DB connection (tcp://localhost:6379, database=0): 99 - Address not available'
```

It's weird that it's trying to connect to `tcp://localhost:6379`, because I have this config in `app.php`: 

```php
return [
    'components' => [
        'redis' => [
            'class' => \yii\redis\Connection::class,
            'hostname' => getenv('REDIS_HOST'),
            'port' => getenv('REDIS_PORT'),
            'password' => getenv('REDIS_PASSWORD') ?: null,
        ],
// ...
```

and these in `.env`:

```
REDIS_HOST="redis.service.nitro"
REDIS_PORT="6379"
REDIS_PASSWORD=""
```

No `localhost` anywhere.

**Comment by benface** [comment]
Huh, weird, looks like it was a file system sync issue. The changes I made to `.env` were not visible in the VM for some reason. A `nitro restart` fixed it. Nevermind me!

**Comment by jasonmccallister** [comment]
Glad to hear that @benface!
