### ISSUE TITLE
Init command results in "Error: exit status 2"

### ISSUE THREAD

**Issue by Kravimir** [craftcms/nitro#215]
### Description

When I tried setting up a VM directly in Multipass (on Win10), I had problems with using Ubuntu 20.0.4, but Ubuntu 18.0.4 seems to work. Is there any way to force Nitro to use a different Ubuntu image?

### Additional info

- Nitro version: 1.0.1
- Multipass version: 1.4.0

**Comment by jasonmccallister** [comment]
@Kravimir thank you for reporting this issue. There is no way to specify the version of ubuntu, I am going to look at the issue and try to create on my end.

In the mean time, can you [grab the multipass logs](https://multipass.run/docs/accessing-logs) for the `nitro-dev` machine and email them to support@craftcms.com? I would normally ask you to post here but I'm not confident in the content of the logs, so better safe than sorry.

**Comment by Kravimir** [comment]
It's strange. I get a different error when I use HyperV instead of VirtualBox:

> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies:
>  php-imagick : Depends: libmagickcore-6.q16-6 (>= 8:6.9.10.2) but it is not installable
>                Depends: libmagickwand-6.q16-6 (>= 8:6.9.10.2) but it is not installable
>                Recommends: ghostscript but it is not going to be installed
>                Recommends: ttf-dejavu-core but it is not installable
>  php7.4-mbstring : Depends: libonig5 (>= 6.8.1) but it is not installable
> E: Unable to correct problems, you have held broken packages.
> Error: exit status 100

I've emailed the event logs for both.

**Comment by jasonmccallister** [comment]
We just released Nitro 2 where we switched from Multipass to Docker and added a ton of new features. Please see the [announcement for more details](https://craftcms.com/blog/nitro-2).

This issue was specific to Multipass so we are going to close this out. Please see the documentation on upgrading from [Nitro 1](https://craftcms.com/docs/nitro/2.x/upgrade.html).
