### ISSUE TITLE
Error in adding nitro to project

### ISSUE THREAD

**Issue by agthetpaing** [craftcms/nitro#216]
### Description

I have tried to install nitro machine and add it to my project but I got errors when I do that. 
First time when I tried to add nitro to my project, it says it timed out as shown below.

![image](https://user-images.githubusercontent.com/66248799/94505888-73003f00-024f-11eb-9f55-4e122a74818b.png)

Then after, I rerun `nitro add` again and it exited with error status 127 as shown below.
![image](https://user-images.githubusercontent.com/66248799/94505962-a4790a80-024f-11eb-9f04-8f61027da845.png)

I tried to run `nitro add` again and this time it says it has already been set, but I still can't access to the host name [http://craftcms/](url)

![image](https://user-images.githubusercontent.com/66248799/94506056-dbe7b700-024f-11eb-9e2d-f9db2439097e.png)

I then tried running `nitro remove` and `nitro add` but it is still giving the same error ( but it seems like it does the job though)
![image](https://user-images.githubusercontent.com/66248799/94506211-2c5f1480-0250-11eb-99b5-af71e018b514.png)

How do I fix this? Thank you.

### Additional info

- Nitro version: 1.0.1
- Multipass version: 1.5.0

**Comment by jasonmccallister** [comment]
@agthetpaing if you are getting an error during the `init` process, nothing else will work as expected. It also looks like you are running multipass version 1.5.0 which is not officially released yet.

Can you run `multipass info --all` and verify there is a `nitro-dev` machine?

**Comment by agthetpaing** [comment]
@jasonmccallister I had the same error as [https://github.com/canonical/multipass/issues/1746](url) which suggested to download build. 

Yes, there is indeed a `nitro-dev` machine 

![image](https://user-images.githubusercontent.com/66248799/94630472-398c0a00-0309-11eb-82d2-280ac2d5b650.png)

**Comment by jasonmccallister** [comment]
@agthetpaing that means the init process did not complete. I have not tested Nitro on the 1.5.0 version of Multipass. Also if you are using Virtualbox, that has not been tested either, so I am not sure if Nitro will work completely as expected with that setup.

Also, can you attach the contents of `/var/log/cloud-init-output.log` and `/var/log/cloud-init.log` from the nitro-dev machine?

Here are some steps to get those files from the machine to your host:

1. `multipass transfer nitro-dev:/var/log/cloud-init-output.log cloud-init-output.log`
2. `multipass transfer nitro-dev:/var/log/cloud-init.log cloud-init.log`

**Comment by alexisRippstein** [comment]
I get the error very similar:
When I want to add a **new** project I get the same error code back and the following message:

```
ls: cannot access '/etc/nginx/sites-enabled': No such file or directory
Error: exit status 127
```
When I use `nitro apply` I get the same error back again.

I install nginx on my Mac (Catalina) with homebrew

### Additional info
Nitro version: 1.0.1 and 1.1.0 (try it with both)
Multipass version: 1.4.0

**Comment by jasonmccallister** [comment]
@alexisRippstein can you attach the contents of `/var/log/cloud-init-output.log` and `/var/log/cloud-init.log` from the `nitro-dev` machine?

Here are some steps to get those files from the machine to your host:

`multipass transfer nitro-dev:/var/log/cloud-init-output.log cloud-init-output.log`
`multipass transfer nitro-dev:/var/log/cloud-init.log cloud-init.log`

**Comment by alexisRippstein** [comment]
[cloud-init-output.log](https://github.com/craftcms/nitro/files/5360332/cloud-init-output.log)
[cloud-init.log](https://github.com/craftcms/nitro/files/5360333/cloud-init.log)

**Comment by jamiematrix** [comment]
I'm also getting the error
```
ls: cannot access '/etc/nginx/sites-enabled': No such file or directory
Error: exit status 127
```

I also had several errors when installing Nitro:
```
Package php-imagick is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package php-xdebug is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package php7.4-fpm is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Unable to locate package php7.4-mbstring
E: Couldn't find any package by glob 'php7.4-mbstring'
E: Couldn't find any package by regex 'php7.4-mbstring'
E: Package 'php7.4-fpm' has no installation candidate
E: Unable to locate package php7.4-intl
E: Couldn't find any package by glob 'php7.4-intl'
E: Couldn't find any package by regex 'php7.4-intl'
E: Unable to locate package php7.4-zip
E: Couldn't find any package by glob 'php7.4-zip'
E: Couldn't find any package by regex 'php7.4-zip'
E: Unable to locate package php7.4-soap
E: Couldn't find any package by glob 'php7.4-soap'
E: Couldn't find any package by regex 'php7.4-soap'
E: Unable to locate package php7.4-bcmath
E: Couldn't find any package by glob 'php7.4-bcmath'
E: Couldn't find any package by regex 'php7.4-bcmath'
E: Package 'php-xdebug' has no installation candidate
E: Package 'php-imagick' has no installation candidate
E: Unable to locate package blackfire-agent
E: Unable to locate package blackfire-php
Error: exit status 100
```

nitro-dev is running.

Log files are attached.
[cloud-init-output.log](https://github.com/craftcms/nitro/files/5523478/cloud-init-output.log)
[cloud-init.log](https://github.com/craftcms/nitro/files/5523480/cloud-init.log)

**Comment by solidevolution** [comment]
Getting this error too after fresh multipass & nitro install with brew

**Comment by warpkid** [comment]
Getting the same error as you jamiematrix on Ubuntu 20.10.

Running the steup shell script completes with the error regarding moving nitro. However, trying to init, or add a site using nitro results in the following error:
`ls: cannot access '/etc/nginx/sites-enabled': No such file or directory`

The nitro-dev machine is up and running.

**Comment by jasonmccallister** [comment]
Can you try running the `nitro refresh` command followed by `nitro restart` and see if that resolves the issue?

**Comment by jasonmccallister** [comment]
We just released Nitro 2 where we switched from Multipass to Docker and added a ton of new features. Please see the [announcement for more details](https://craftcms.com/blog/nitro-2).

This issue was specific to Multipass so we are going to close this out. Please see the documentation on upgrading from [Nitro 1](https://craftcms.com/docs/nitro/2.x/upgrade.html).
