### ISSUE TITLE
Allow custom DB

### ISSUE THREAD

**Issue by sidneywidmer** [craftcms/nitro#218]
### Description
Currently Nitro is hardcoded in the SetupController and it is not possible to use a DB outside of the VM. Also the VM somehow seems to ignore the DB specific ENV Vars defined in .env. Our team shares a DB which is on a server in our network so it would be nice if we still would be able to ignore the whole `isNitro` stuff or somehow overwrite it?

I also understand that nitro is highly opiniated so if my request is out of scope feel free to close the issue.

### Steps to reproduce

1. Set the DB_DSN to any IP with a runing DB instance
2. Try to load Craft -> it will result in an error saying `Craft CMS can’t connect to the database with the credentials in config/db.php.` (because I havent event set up the nitro DB inside the VM)

### Additional info

- Nitro version: 1.1.0
- Multipass version: 1.40

**Comment by jasonmccallister** [comment]
@sidneywidmer when you run `nitro ssh` can you connect to the database using the CLI client (e.g `mysql`)?

**Comment by sidneywidmer** [comment]
@jasonmccallister Yes i can connect from the nitro machine to the "external" DB. I think my issues is related to #119 

I also found out, that nitro respects my `DB_DSN` but overwrites `DB_USER` and `DB_PASSWORD` with the value `nitro`. So as a workaround i could create a user `nitro` on my external DB and now I can connext and everything works. But using my own credentials via the .env file is currently not possible.

**Comment by jasonmccallister** [comment]
We just released Nitro 2 where we switched from Multipass to Docker and added a ton of new features. Please see the [announcement for more details](https://craftcms.com/blog/nitro-2).

This issue was specific to Multipass so we are going to close this out. Please see the documentation on upgrading from [Nitro 1](https://craftcms.com/docs/nitro/2.x/upgrade.html).

**Comment by sidneywidmer** [comment]
Thanks for the great work with v2.0, everything works as expected :fire:
