### ISSUE TITLE
Nitro 1.1.0 - Linux silently fails importing db 

### ISSUE THREAD

**Issue by yoroshikun** [craftcms/nitro#219]
### Description
In the latest version 1.1.0 attempting to import a db silently fails.

### Steps to reproduce

1. Install nitro 1.1.0
2. run `nitro import db ./db.sql`
3. output looks like below, exits early with no error
```
❯ nitro db import db.sql
Detected a "mysql" backup file...
Enter the database name to create for the import: db
Will create the database db
Uploading "db.sql" into "nitro-dev" (large files may take a while)...
```

4. nitro version 1.0.1 works with the following output
```
❯ nitro db import db.sql
Enter the database name to create for the import db
Uploading "db.sql" into "nitro-dev" (large files may take a while)...
Created database db
Successfully imported the database backup into mysql_5.7_3306
```

### Additional info

- Nitro version: 1.1.0
- Multipass version: 1.4.0
- Linux version: 
![image](https://user-images.githubusercontent.com/1892447/96079618-b370e580-0efc-11eb-9c6a-b9e7b1a47e98.png)

**Comment by jasonmccallister** [comment]
@yoroshikun can you run the following commands in a separate terminal and then try the import command again?

- `nitro ssh`
- `journalctl -u nitrod -f`

Then on the host machine, run `nitro db import db.sql` and add the logs to this ticket. That should give me enough start troubleshooting.

**Comment by jasondibenedetto** [comment]
Getting this same error on mac catalina 10.15.6.

Tried running the commands you posted @jasonmccallister but not seeing any logs outputted.

**Comment by jasonmccallister** [comment]
Alright, I think I know what's going on. Can you run `nitro refresh` and `nitro restart` and try the import again?

**Comment by jasondibenedetto** [comment]
It looks like that has resolved the issue – thanks @jasonmccallister

**Comment by jasonmccallister** [comment]
@jasondibenedetto sorry about that! Right now the CLI and API are detached. When you update the Nitro CLI it does not automatically update the API on the virtual machine. 

There are several ways to perform this, but I am looking into this [Go package](https://github.com/minio/selfupdate) to make upgrades automatic on the API. It did not make it into this release but I will work on prioritizing that feature so `nitro refresh` becomes a thing of the past.

@yoroshikun can you perform the same steps and verify that resolves the issue for you as well?

**Comment by yoroshikun** [comment]
@jasonmccallister Running the following commands worked like a charm and imports now work as intended.
```
nitro self-update (to 1.1.0)
nitro refresh
nitro restart
nitro db import db.sql
```

Thing to note when running `nitro self-update` in non sudo mode (unconfirmed with sudo mode) the installer creates artifacts ([unintentional?] `temp_nitro_extract` and [intentional] `nitro` bin to copy as per instructions) temp is not removed before bailout I am guessing.

**Comment by jasonmccallister** [comment]
@yoroshikun those are intentional. I plan, soon hopefully, to make these official packages (snap, flatpak, and brew) at some point. I'm not sure which Mint supports (snap or flatpak) but that will hopefully help with updating the CLI.

I'm going to close this out as it resolved the issue! I will be looking at hosts file on linux soon.
