### ISSUE TITLE
Multipass installation

### ISSUE THREAD

**Issue by angrybrad** [craftcms/nitro#22]
See if it's possible to check if Multipass is installed and if not, automatically download

**Comment by jasonmccallister** [comment]
Maybe instead of downloading, we can check if they have something like brew installed and then print the brew (or suitable package manager) instructions:

e.g.

```
We are unable to location multipass, to install please run:

    brew install multipass

When multipass is installed, please run this command again.
```

**Comment by angrybrad** [comment]
If we do this, we have to link to their license and prompt the end-user to accept.
