### ISSUE TITLE
Unable to turn Xdebug on or off

### ISSUE THREAD

**Issue by jeromecoupe** [craftcms/nitro#220]
### Description

When I am trying to turn Xdebug on or off I get the following message

> Error: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 192.168.64.2:50051: connect: connection refused"

### Steps to reproduce

1. `nitro start`
2. Type `nitro xdebug off` or `nitro xdebug on`

### Additional info

- Nitro version: nitro 1.1.0
- Multipass version: multipass  1.4.0+mac // multipassd 1.4.0+mac

**Comment by jasonmccallister** [comment]
@jeromecoupe can you try the following?

nitro refresh
nitro restart

And see if the command will complete successfully?

**Comment by jeromecoupe** [comment]
Works like a charm, thank you.
Closing this

> jeromecoupe@jeromes-MacBook-Pro iad_craft % nitro refresh
Downloading the latest refresh script.
Running...
installing nitrod and nitrod.service
Created symlink /etc/systemd/system/multi-user.target.wants/nitrod.service → /etc/systemd/system/nitrod.service.
Refreshed the templates and configs for the machine to 1.1.0
jeromecoupe@jeromes-MacBook-Pro iad_craft % nitro xdebug on
Enabled xdebug for PHP 7.4
jeromecoupe@jeromes-MacBook-Pro iad_craft % nitro xdebug off
Disabled xdebug for PHP 7.4
