### ISSUE TITLE
Cant set PHP max_input_vars

### ISSUE THREAD

**Issue by J-Protz** [craftcms/nitro#222]
### Description
Trying to increase input_vars for php so I can add a new module but it is not working.

### Steps to reproduce

1.   nitro php iniset max_input_vars 2000:
`Successfully changed the ini setting for max_input_vars to 2000`
2.  nitro php iniget max_input_vars : 
`The setting "max_input_vars" is currently set to 1000`

### Additional info

- Nitro version:1.1.1
- Multipass version:  
``` multipass version
multipass  1.4.0+mac
multipassd 1.4.0+mac
```

**Comment by angrybrad** [comment]
Not able to reproduce this on Nitro 1.1.1 and Multipass 1.5.0.

```
❯ nitro php iniset max_input_vars 5000
Successfully changed the ini setting for max_input_vars to 5000

❯ nitro php iniget max_input_vars
The setting "max_input_vars" is currently set to 5000
```

Try updating to Multipass 1.5.0?

**Comment by daltonrooney** [comment]
I'm using Nitro 1.1.1 and Multipass 1.5.0.

```
> nitro php iniset max_input_vars 5000
Successfully changed the ini setting for max_input_vars to 5000
> nitro php restart
Successfully restarted php-fpm 7.4
> nitro php iniget max_input_vars
The setting "max_input_vars" is currently set to 1000
```

When I ssh into the nitro machine and check the php.ini file, the line looks like this:

`;max_input_vars = 5000 = 1000`

**Comment by jasonmccallister** [comment]
Changing PHP settings has been greatly improved in v2 and there is a new `nitro iniset` command to tweak settings on a per site basis. Please see the documentation for further details - https://craftcms.com/docs/nitro/2.x/php-settings.html
