### ISSUE TITLE
Error running `db import` with a SQL file outside of working directory

### ISSUE THREAD

**Issue by brandonkelly** [craftcms/nitro#223]
### Description

When running `nitro db import`, an error is output if the given path is anything but a file in the current working directory:

```bash
> nitro db import /Volumes/Dev/happylager/happylager.sql
Error checking if the file is compressed, error: open happylager.sql: no such file or directory
```

```bash
> cd /Volumes/Dev/happylager
> nitro db import happylager.sql 
Detected a "mysql" backup file...
...
```

### Additional info

- Nitro version: 1.1.1
- Multipass version: 1.5.0

**Comment by jasonmccallister** [comment]
I have identified this issue and need to use [`filepath#Clean`](https://pkg.go.dev/path/filepath#Clean) on the argument to get the corrected path.

Will get this pushed up soon.

**Comment by jasonmccallister** [comment]
Closing this as resolved!
