### ISSUE TITLE
Cannot seem to change post_max_size using php iniset

### ISSUE THREAD

**Issue by toddpadwick** [craftcms/nitro#225]
### Description
I have set all other known defaults such as `max_execution_time`, `max_file_uploads`, `max_input_time`, `max_input_vars`, `memory_limit`, `upload_max_filesize` successfully. However it doesn't seem to be possible to run `nitro PHP iniset post_max_size`. doing so simply returns the available commands prompt. 

I can however, confirm that running `nitro PHP iniget post_max_size` works and returns the default 8M. 

This is a problem for me because I cannot upload files larger than 8M which is very low when dealing with files like video for example. I have changed `upload_max_filesize` to 100M but obviously `post_max_size` overrides this.

### Steps to reproduce

1. Run command `nitro PHP iniset post_max_size 100M`
2. 

### Additional info

- Nitro version: 1.1.1
- Multipass version:

**Comment by jasonmccallister** [comment]
@toddpadwick can you provide the contents of your `php.ini` file?

`cat /etc/php/7.4/fpm/php.ini | grep upload_max_filesize`

**Comment by toddpadwick** [comment]
Hi @jasonmccallister. I don't think there is a PHP.ini file for mac PHP according to this thread.... https://stackoverflow.com/questions/40515949/where-are-ini-files-on-macosx-sierra/46383843

There is no directory `/etc/php` on my machine.

if i run `PHP -v` i get the following:
```
PHP 7.3.9 (cli) (built: Feb 17 2020 12:46:14) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.9, Copyright (c) 1998-2018 Zend Technologies

```

**Comment by jasonmccallister** [comment]
@toddpadwick apologies for not being clear. Can you perform the following steps?

1. `nitro ssh`
2. `cat /etc/php/7.4/fpm/php.ini | grep upload_max_filesize`

Then paste the output here?

**Comment by jasonmccallister** [comment]
@toddpadwick I think I just found the problem, what version of PHP are you using?

**Comment by toddpadwick** [comment]
@jasonmccallister its the version Mac OS Catalina ships with which is `PHP 7.3.9`. Do i need to update this globally then?

**Comment by jasonmccallister** [comment]
@toddpadwick What version of PHP are you using in your `nitro.yaml` and nitro virtual machine (e.g. using `nitro ssh`)?

**Comment by jasonmccallister** [comment]
Changing PHP settings has been greatly improved in v2 and there is a new `nitro iniset` command to tweak settings on a per site basis. Please see the documentation for further details - https://craftcms.com/docs/nitro/2.x/php-settings.html
