### ISSUE TITLE
.env file is overwritten on nitro add

### ISSUE THREAD

**Issue by michaelroper** [craftcms/nitro#232]
### Description
When I tried to add an existing site using `nitro add`, it completely overwrote my existing `.env` file with only the updated DB details.

### Steps to reproduce

1. Have an existing site with a customised .env file 
2. Use the `nitro add` command to add the site to the environment
3. Notice that the customised .env file has been overwritten with the base database key/values

### Additional info

- Nitro version: 2.0.0-beta.1

**Comment by jasonmccallister** [comment]
This will be resolved with the next beta release. Thank you and sorry for the inconvenience!

**Comment by jasonmccallister** [comment]
This change has been released with 2.0.0-beta.2. Please let me know if you experience this again but I verified locally on multiple files. The main issue was it copied the example env _without_ checking for an existing `.env` file.. 

https://github.com/craftcms/nitro/blob/main/CHANGELOG-V2.md#200-beta2---2021-02-04
