### ISSUE TITLE
[2.0.0-beta.2] nitro destroy doesn't clean up /etc/hosts entries

### ISSUE THREAD

**Issue by tomdavies** [craftcms/nitro#235]
### Description

Thanks for Nitro!

Running `nitro destroy` doesn't clean up any entries that have added by nitro to `/etc/hosts`.

### Steps to reproduce

1. `nitro create hosts-test`
2. `nitro destroy`
3. `cat /etc/hosts`

```
# <nitro>
127.0.0.1       mysql-8.0-3306.database.nitro nitro-test.nitro
# </nitro>
```

### Additional info

- Nitro version: 2.0.0-beta.2
- Docker version: 3.1.0
- MacOS Mojave 10.14.6
- Installed nitro via homebrew

**Comment by jasonmccallister** [comment]
@tomdavies just pushed an update that will resolve this issue in https://github.com/craftcms/nitro/commit/3914773b375de4c86f258c139187ef014c9a2378. This will go out in the next beta release, thank you for the report!

**Comment by jasonmccallister** [comment]
This was resolved in the latest beta! Thank you!
