### ISSUE TITLE
[2.0.0-beta.2] nitro destroy doesn't clean up ~/.nitro/nitro.yaml

### ISSUE THREAD

**Issue by tomdavies** [craftcms/nitro#236]
### Description

Not sure if this is expected behaviour but running `nitro destroy` leaves `~/.nitro/nitro.yaml` in place

This means that the following will fail:

1. `nitro create nitro-test`
2. `nitro destroy`
3. `nitro create nitro-test`

with:

```Error: hostname already exists```

### Additional info

- Nitro version: 2.0.0-beta.2
- Docker version: 3.1.0
- MacOS Mojave 10.14.6
- Installed nitro via homebrew

**Comment by jasonmccallister** [comment]
@tomdavies the `destroy` command accepts the flag `--clean` which will remove the config file but default to false to allow people to rebuild the environment quickly. Is `--clean` not removing the file when running `nitro destroy --clean`?

**Comment by tomdavies** [comment]
@jasonmccallister ack, that makes sense. My failure to read the docs properly / poor mental model of what nitro is doing on my part :)

Can confirm `--clean` flag works as advertised.

Might be nice if it was interactive with sane default (`N`), as you're prompting for confirm already, or at least if the prompt was different when flag passed, i.e The prompt is always:

`Are you sure (this will remove all containers, volumes, and networks)` 

Whether passing `--clean` or not.
