### ISSUE TITLE
[2.0.0-beta.2] PHP RuntimeException on `nitro composer outdated`

### ISSUE THREAD

**Issue by tomdavies** [craftcms/nitro#239]
### Description

Running `nitro composer outdated`

On 2.0.2-beta2 on a clean nitro install / new site created with `nitro create`

results in:

```
  … checking /path/to/composer.json ✓


  [Symfony\Component\Console\Exception\RuntimeException]
  The "--ignore-platform-reqs" option does not exist.


outdated [-o|--outdated] [-a|--all] [--locked] [-D|--direct] [--strict] [-m|--minor-only] [-f|--format FORMAT] [--ignore IGNORE] [--no-dev] [--] [<package>]

composer outdated completed 🤘
```

While running `composer outdated` from composer in my host machine I get the expected output:

```
$ composer outdated
composer/composer       2.0.8   2.0.9   Composer helps you declare, manage and install dependencies of PHP projects. It ensures you have the right...
....
```

The same error happens on some other composer commands too:

- `composer about`
- `composer cc`
- `composer status`

There are probably others as I didn't check each one!

### Steps to reproduce

1. `nitro create composer-test`
2. `cd composer-test`
3. `nitro composer update`

### Additional info

- Nitro version: [2.0.0-beta.2]
- Docker version: 3.10 (51484)
- PHP (nitro) 8.0 
- Host PHP 8.0 / composer 2.0.8

**Comment by jasonmccallister** [comment]
@tomdavies wrapping up some work to resolve this an make it a little more flexible going forward.

https://user-images.githubusercontent.com/5354908/107094017-4c8d7a00-67d4-11eb-84e5-80241d68e1e4.mov

**Comment by tomdavies** [comment]
Nice work 👍

**Comment by jasonmccallister** [comment]
This went out with the last beta, you should be able to run this command now!

**Comment by tomdavies** [comment]
Confirmed fixed for me in beta 5
