### ISSUE TITLE
Can't install on Manjaro Raspberry Pi

### ISSUE THREAD

**Issue by MattWilcox** [craftcms/nitro#242]
### Description

Admittedly; this is the lowest of all priorities given the hardware and rareness of anyone running Manjaro on it; but...

```
[matt@pi4 ~]$ sudo nitro init
Checking Nitro…
  … creating network ✓
  … pulling image ✓
  … creating volume ✓
  … creating proxy ✓
Checking network…
  ✓ network ready
Checking proxy…
  ✓ proxy ready
Checking databases…
  … checking mysql-5.7-3306.database.nitro   … downloading mysql:5.7 ✗
Error: unable to create the container, Error response from daemon: No such image: mysql:5.7
```

### Additional info

- Nitro version: 2beta3
- OS: Manjaro Linux. ARM, Raspberry Pi 4
- Docker: From the package manager

```
[matt@pi4 ~]$ docker version
Client:
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.15.6
 Git commit:        2291f610ae
 Built:             Tue Jan 19 19:14:38 2021
 OS/Arch:           linux/arm64
 Context:           default
 Experimental:      true
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/version": dial unix /var/run/docker.sock: connect: permission denied
```

**Comment by MattWilcox** [comment]
(Why am I running on Raspberry Pi!? ... Well my personal iMac is from 2009 and I can't run OSX 10.13 or higher, so I don't have Docker for it...)

**Comment by jasonmccallister** [comment]
**YES! THIS ISSUE MADE MY DAY!** 

I'm running Ubuntu on my Raspberry Pi 4 and here is the best news... _It is supported_! 

However, relating to [this issue](https://github.com/craftcms/nitro/issues/234) the MySQL image is not ARM compatible.. 

The current solution to work around this is to update your config for the database to look like the following:

```yaml
databases:
    - engine: mariadb
      version: "10.x" # replace with your version
      port: "3306"
```

Then run `nitro apply` to make sure everything is up to date. 

We did ship a change in `2.0.0-beta.3` to automatically suggest mariadb on macos ARM but I think we can change that to any ARM based OS to broaden support.

I'll get this worked into the next release!

**Comment by MattWilcox** [comment]
Amazing! I'll give that a try tomorrow, thanks very much! I've also figured out how to not need sudo for nitro commands thanks to a little Googling for following Docker configuration after initial install via the package manager.

I forget "real" MySQL is still a thing, I switched to Maria a long while back and just seem to forget some distros still mean actual MySQL and not an aliased command!

**Comment by MattWilcox** [comment]
Boom, that works! Though now the https cert install is failing, but I'll raise that as a new bug if I can't work that out. Thanks Jason!

**Comment by jasonmccallister** [comment]
We just pushed [beta.4](https://github.com/craftcms/nitro/releases/tag/2.0.0-beta.4) that will check for any Arm-based device and select database images appropriately.
