### ISSUE TITLE
Automate SSL support on Linux

### ISSUE THREAD

**Issue by MattWilcox** [craftcms/nitro#244]
### Description

Fails https cert copy on Manjaro Linux on Raspberry Pi4.

### Steps to reproduce

ran nitro init...

```
Updating hosts file (you might be prompted for your password)
[sudo] password for matt: 
Adding sites to hosts file…
  … modifying hosts file ✓
  … getting certificate for Nitro… ✓
Installing certificate (you might be prompted for your password)
mv: cannot move '/tmp/nitro-cert304261744' to '/usr/local/share/ca-certificates/nitro.crt': No such file or directory
Unable to automatically add certificate

To install the certificate, run the following command:
  sudo mv /tmp/nitro-cert304261744 /usr/local/share/ca-certificates/nitro.crt
  sudo update-ca-certificates
Nitro is ready! 🚀
[matt@pi4 .nitro]$ sudo mv /tmp/nitro-cert304261744 /usr/local/share/ca-certificates/nitro.crt
mv: cannot move '/tmp/nitro-cert304261744' to '/usr/local/share/ca-certificates/nitro.crt': No such file or directory
[matt@pi4 share]$ sudo update-ca-certificates
sudo: update-ca-certificates: command not found
```

/tmp/nitro-cert304261744 does exist, but `/usr/local/share/ca-certificates` does not and i'm thinking the destination directory isn't being made via the above command.

I've made it myself and moved the cert - so that's there now, but the suggested update-ca-certificates isn't a utility ?

### Additional info

- Nitro version: 2beta3

**Comment by MattWilcox** [comment]
Not sure I'm following you, but there is no such package in the Manjaro or any Arch based distro - `update-ca-certificates` appears to be Ubuntu specific.

https://wiki.archlinux.org/index.php/User:Grawity/Adding_a_trusted_CA_certificate

**Comment by MattWilcox** [comment]
On Arch based Linux it appears the nitro.crt should be stored at `/etc/ca-certificates/trust-source/anchors` and then the utility should be run as `sudo update-ca-trust`

This appears to have run correctly - though I've not tested an actual Nitro project yet...

**Comment by jasonmccallister** [comment]
Alright, I might have to make this tricky to support multiple distros... 

Can you provide the output of `lsb_release --description`?

On Ubuntu based devices it outputs the following:

```
$ lsb_release --description
Description:	Ubuntu 20.04.2 LTS
``` 

I might be able to write a "finder" interface for the linux distro based on the description to make the commands more automatic..

I should probably be more clear on the errors (e.g. path does not exists (but we are prompting for root permissions so we could make those directories)...

**Comment by MattWilcox** [comment]
```
[matt@pi4 test]$ lsb_release --description
Description:	Manjaro ARM Linux
```

I'm a little surprised it doesn't reference Arch, but then I'd also have expected yours to reference Debian.

And yes I found it odd it couldn't make those directories via a `sudo mv` but I believe that might be an optional flag, or just an issue with where it was trying to make the path. Either way, that was the wrong path for Arch based distros, and I didn't have an issue moving it with `sudo mv nitro.crt /etc/ca-certificates/trust-source/anchors`

**Comment by jasonmccallister** [comment]
@MattWilcox I don't have Manjaro but I'm fairly confident in the changes to the `trust` command mentioned above. Here is a linux arm build (marked as beta 3) but will be the next beta with the changes to certificate installation.

[nitro_linux_arm64.tar.gz](https://github.com/craftcms/nitro/files/5984253/nitro_linux_arm64.tar.gz)

**Comment by jasonmccallister** [comment]
@MattWilcox beta 5 is out with changes to the certificate installation on linux machines. Closing this out. Thank you for the report!
