### ISSUE TITLE
Machine does not have an IP Address

### ISSUE THREAD

**Issue by KarlBishop** [craftcms/nitro#246]
### Description

After running `nitro init` my default machine IP Address reports as "N/A"

### Steps to reproduce

1. Follow [other setup instructions](https://craftcms.com/docs/nitro/1.x/installation.html#windows-10-pro-with-hyper-v-enabled)
2. Run `nitro init`

### Additional info
My environment:
- Windows 10 Home
- Nitro 1.1.1
- Multipass 1.5.0+ (multipass-1.5.0+win-win64.exe) 
- VirtualBox 6.1 (VirtualBox-6.1.18-142142-Win.exe)

Nitro machine spec:
```
How many CPU cores? [4]
How much memory? [4G]
How much disk space? [40G]
Which version of PHP? [7.4]
Which database engine? [mysql]
Which version of mysql? [5.7] 8
```

Some error messages that appeared in the log ([full output attached](https://github.com/craftcms/nitro/files/5962404/nitro_init.log)):
```
Unable to disable xdebug, err:  rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: lookup N/A: no such host"
Composer is now installed on "nitro-dev".
Unable to enable display_errors, err:  rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: lookup N/A: no such host"
Nitro installed, ready for something incredible at N/A.

```

How can I change the IP Address?

**Comment by KarlBishop** [comment]
Couple other things to note:
- After running `nitro init`, I can right-click Multipass in the taskbar and see "nitro-dev (Running)"
- I can also click "Open Shell" and get a PowerShell window with prompt `ubuntu@nitro-dev:~$`

**Comment by jasonmccallister** [comment]
@KarlBishop thank you for reporting this issue. Unfortunately, on v1, running with VirtualBox is not really tested and we have officially started the process of moving from Multipass to a Docker based backend as Multipass and Windows had a lot of problems with networking and specifically Windows 10 Home support, which is your OS. See [this troubleshooting documentation](https://multipass.run/docs/troubleshooting-networking-on-windows) for Multipass and Windows 10.

Switching to Docker made it a lot easier to support Windows 10 and add a lot more features for local development. You can read more [about the v2 beta here](https://craftcms.com/docs/nitro/2.x/). 

The documentation does specify "_Nitro 2 is currently in beta and currently doesn’t support Windows_" but we are working on getting the next beta out with the changes needed for Windows 10 along with a detailed documentation for installation. Windows 10 Home will require WSL2 be installed (which is also part of the [Docker installation for Windows 10 Home](https://docs.docker.com/docker-for-windows/install-windows-home/)).

**Comment by KarlBishop** [comment]
OK, thanks for the response. Hope the v2 Windows support is coming along nicely!

**Comment by jasonmccallister** [comment]
We just released Nitro 2 where we switched from Multipass to Docker and added a ton of new features. Please see the [announcement for more details](https://craftcms.com/blog/nitro-2).

This issue was specific to Multipass so we are going to close this out. Please see the documentation on upgrading from [Nitro 1](https://craftcms.com/docs/nitro/2.x/upgrade.html).
