### ISSUE TITLE
[2.0.0-beta.4] Restarting Nitro breaks MySQL?

### ISSUE THREAD

**Issue by alexr8** [craftcms/nitro#247]
### Description
When i set up Nitro v2, I imported some databases, connected them up to my sites that I added via `nitro add`, and all worked fine. However, as soon as I restart Nitro (e.g. nitro restart, or stopping nitro and starting again later), MySQL ceases to function:

- All my sites display the error:  `Database Exception – yii\db\Exception
SQLSTATE[HY000]: General error: 1449 The user specified as a definer ('mysql.infoschema'@'localhost') does not exist
The SQL being executed was: SHOW TABLES`
- When i connect to nitro through my GUI (Sequel Ace), none of the databases i had previously are present, not even the default nitro databases etc.

So far the only way i can fix this is to `nitro destroy` then `nitro init` and then reimport my databases again.

### Steps to reproduce

1. Install nitro v2, create some databases
2. Restart nitro

### Additional info

- Nitro version: 2.0.0-beta.4
- MySQL 8 (and also happened second time where i had MySQL 5.7 set up too via nitro edit)

![image](https://user-images.githubusercontent.com/35040195/107951449-45165f80-6f90-11eb-8ef8-ffce5b52d742.png)

**Comment by alexr8** [comment]
After further exploring, I think it might be the way in which I imported my databases that might be the cause. I had previously been running my import via Sequel Ace - i had an export of all db's from nitro v1 in one .sql file so i was importing that, and I had to suppress a few warnings about innodb tables - could this be the source of the issue? I'm now going through and manually importing fresh exports of each database from the live sites, one by one, via the nitro CLI on a fresh nitro init, then restarting nitro and I am not recreating the issue so far.

**Comment by jasonmccallister** [comment]
@alexr8 can you try clearing your local caches? That is a strange error but referencing localhost, which would not work in Docker (it needs the `db.database.nitro` hostname).

**Comment by alexr8** [comment]
I think this can probably be closed - I've not reencountered the issue slowly reimporting databases one by one, rather than my single export from nitro 1 of all databases. Just for the record in case this pops up in future, how it got to that issue was:

- I'd exported a single sql file of all dbs from nitro v1 using `nitro db backup`
- deleted nitro v1 as per the uninstall directions in the docs
- installed v2
- imported my old databases via a gui, at which point some warnings/errors around innodb tables were thrown which i proceeded anyway
- stopping and restarting nitro which resulted in the above
