### ISSUE TITLE
[2.0.0-beta.5] nitro destroy removes any docker containers present

### ISSUE THREAD

**Issue by jamesmacwhite** [craftcms/nitro#250]
### Description

Running `nitro destroy` removed all Docker containers present on my system, even one's completely unrelated to Nitro itself, not sure if that was the intended result, but if so it's pretty dangerous and should be clarified.

**Comment by jasonmccallister** [comment]
Hi @jamesmacwhite you are right and that is a bug, we are creating a filter for nitro containers but not passing it properly here: https://github.com/craftcms/nitro/blob/develop/command/destroy/destroy.go#L67

I'll push up that change and get a release out asap, thank you for the report and apologies for missing that!

**Comment by jamesmacwhite** [comment]
Well glad that was found in the beta! Luckily it didn't kill the data of the non Nitro related containers, which a simple `docker-compose up` will sort.

**Comment by jasonmccallister** [comment]
We just released 2.0.0-beta.6 with this change, should be available shortly!
