### ISSUE TITLE
General questions around Windows support with Nitro V2

### ISSUE THREAD

**Issue by jamesmacwhite** [craftcms/nitro#251]
### Description

I'm currently using the Docker images at craftcms/docker as I'm on Windows and I know Nitro v2 doesn't support Windows currently. I'm curious though in terms of the Windows support, as based on my testing and experimenting after sacking off Nanobox and every other VM solution prior the key thing I found unless Docker is ran through WSL 2 i.e. with a real Linux kernel, the performance is horrible when running a development environment for Craft 3. Docker themselves also recommend projects should be mounted on a WSL distro filesystem path not a Windows path i.e. C:\ or /mnt/c due the performance issues you will likely encounter and Craft 3 really does struggle on Windows FS path (dev mode on or off) when virtualisation is involved. I've tried Vagrant, Nanobox and some others, they all have horrible performance because of the combination of virtualisation and Windows filesystem layer. At one point I literally thought about just using IIS...

I myself am probably jaded have experienced much pain with any Virtualisation layer when a Windows FS mountpoint is involved, ranging from symlink shenanigans (looking at you npm), to even Yii2 itself breaking when it didn't know the difference being on a Linux environment hosted on a Windows FS (was fixed). Being quite late to the Docker party, I finally at least found that Docker with a WSL backend seems to be fairly performant and very workable, certainly similar to any environment on macOS or Linux. This is largely thanks to WSL2 having a proper Linux kernel inside Windows, which Docker can take advantage of, so when you have a WSL2 distro, let's say (Ubuntu) and Docker Desktop linked to that WSL distro all the sys calls and hence performance is so much better. So happy days?

So really my TL;DR question is what is the Windows support going to look like, will it involve WSL2, or are you trying to support it natively? If native, it will be interesting to see the performance of Nitro as given it's using a Docker backend, it's possibly likely to encounter the same general problems Docker Desktop on Windows has without WSL2.

Thanks!

P.S I know this isn't a bug, but I can't create an issue that's not a bug or security issue, so please ignore the bug tag!

**Comment by angrybrad** [comment]
> will it involve WSL2

WSL2 will be required.

You can read the WIP docs for Nitro 2 and Windows here:

https://github.com/craftcms/docs/blob/feature/nitro2-windows/docs/nitro/2.x/installation.md

https://github.com/craftcms/docs/blob/feature/nitro2-windows/docs/nitro/2.x/windows.md

That last link covers performance. The latest Nitro release is fairly solid on Windows if you want to test it, but there are a couple more issues to work through before we merge the docs in.

**Comment by jamesmacwhite** [comment]
Ah thanks @angrybrad. I wasn't looking hard enough for existing information on the topic clearly! Confirms what I thought around WSL2 and similar guidance for performance and recommendations.

I will certainly take a look at Nitro at some point, for now I am using the general Docker images at https://github.com/craftcms/docker which work well.
