### ISSUE TITLE
[2.0.0-beta.4] 413 Request Entity Too Large

### ISSUE THREAD

**Issue by Tam** [craftcms/nitro#252]
### Description

Getting `413 Request Entity Too Large` when uploading a video file at 36.1 MB.

### Steps to reproduce

1. Create a volume (in my case using DO Spaces)
2. Upload a semi-large file

### Additional info

- Nitro version: 2.0.0-beta.4

**Comment by jasonmccallister** [comment]
@Tam I will take a look at the current limit and most likely increase those in the upstream Docker images.

**Comment by angrybrad** [comment]
@Tam if you run `nitro update` to pull in the latest images, this should be resolve. Might as well update to the latest Nitro 2 beta release while you're at it. :P

https://github.com/craftcms/nitro/releases/tag/2.0.0-beta.7
