### ISSUE TITLE
WSL hostname output text wonkiness

### ISSUE THREAD

**Issue by angrybrad** [craftcms/nitro#253]
### Description

If you run a command in WSL that modifies the hosts file, Nitro correctly detects you're running in WSL and outputs something like this:

```
For your hostnames to work, add the following to `C:\Windows\System32\Drivers\etc\hosts`:
---- COPY BELOW ----
# <nitro>
127.0.0.1\t[mysql-8.0-3307.database.nitro craft4.nitro]
# </nitro>
---- COPY ABOVE ----
```

Note the `\t` tab character and `[]` around the host names.

- Nitro version: 2.0 beta 6

**Comment by jasonmccallister** [comment]
This looks like the Go code was not properly converted... I will take a look.

**Comment by angrybrad** [comment]
Resolved in https://github.com/craftcms/nitro/releases/tag/2.0.0-beta.7
