### ISSUE TITLE
WSL SSL certs

### ISSUE THREAD

**Issue by angrybrad** [craftcms/nitro#254]
We need to take the output of `nitro trust --output-only` and save it to a file on the WSL filesystem (i.e. `~/caddy.crt`).

Then tell the user to open terminal on the windows host machine and run

    certutil -addstore -f "Root" \\wsl$\Ubuntu-20.04\home\brad\caddy.crt

We can get the name of the WSL instance from the `WSL_DISTRO_NAME` env var in WSL ("Ubuntu-20.04” in this case).

This is a one-time operation that would probably need to happen on the first `nitro init` run on WSL?

**Comment by jamesmacwhite** [comment]
I'm glad this has been mentioned. I was testing this on Windows and noticed the docs said you need to run a command but didn't mention what. I ended up poking in the container and extracting the Caddy certs to install into my Windows Local Machine Certificate store. Anything to make it more straightforward for Windows welcome!

**Comment by jasonmccallister** [comment]
Should this be a documentation thing or something we output in the terminal? I think it would be helpful to have the paths setup dynamically. 

Also, I'm wondering if we should place this is the `.nitro` directory on the linux machine to keep things tidy. Can someone verify they can access a hidden directory using that share?

**Comment by jamesmacwhite** [comment]
Doing a basic `dir` from Command Prompt at the \\wsl$ share works, so references file paths with certutil should have no issues in the .nitro directory I'd imagine.

```
C:\Users\james>dir \\wsl$\Ubuntu-20.04\home\jameswhite\.nitro
 Volume in drive \\wsl$\Ubuntu-20.04 has no label.
 Volume Serial Number is 0000-0000

 Directory of \\wsl$\Ubuntu-20.04\home\jameswhite\.nitro

22/02/2021  22:18    <DIR>          backups
24/02/2021  14:23               338 nitro.yaml
25/02/2021  13:41    <DIR>          ..
25/02/2021  13:41    <DIR>          .
               1 File(s)            338 bytes
               3 Dir(s)  237,488,480,256 bytes free
```

**Comment by jasonmccallister** [comment]
Awesome, thank you @jamesmacwhite! Can you also run an `env` command in the linux machine and verify the `USER` env is set?

**Comment by jamesmacwhite** [comment]
@jasonmccallister Confirmed `USER` is present.

```
jameswhite@DWC100-3XSPC:~$ env | grep USER
USER=jameswhite
```

**Comment by jasonmccallister** [comment]
Fantastic, thank you! Was pretty sure WSL would not deviate from the standard env... but you never know...

**Comment by jamesmacwhite** [comment]
Ha ha, always good to never assume with anything Microsoft! Shout if you need any more WSL specific info, happy to help test. Nitro looks really promising, just needs a few upstream Docker parts resolving for me but the overall Nitro 2.x package is looking great.

**Comment by angrybrad** [comment]
Resolved in https://github.com/craftcms/nitro/releases/tag/2.0.0-beta.7
