### ISSUE TITLE
OSX BigSur installation issue

### ISSUE THREAD

**Issue by MattWilcox** [craftcms/nitro#255]
### Description

https://craftcms.com/docs/nitro/2.x/installation.html

`4. Move the binary into your path with sudo mv ./nitro /usr/local/bin.`

On a fresh install of a new OSX, this fails. Trying to cd to /usr/local/bin also fails with "not a directory"

- Nitro version: 2beta6
- OSX version: 11.2.1

**Comment by jasonmccallister** [comment]
@MattWilcox can you provide the output of this command?

`echo $PATH`

**Comment by MattWilcox** [comment]
```
mattwilcox@Matts-iMac nitro_darwin_x86_64 % cd /usr/local/bin 
cd: not a directory: /usr/local/bin
mattwilcox@Matts-iMac nitro_darwin_x86_64 % echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

OSX is also apparently zsh now rather than bash... I am not entirely happy about that.

**Comment by MattWilcox** [comment]
```
mattwilcox@Matts-iMac nitro_darwin_x86_64 % cd /usr/local
mattwilcox@Matts-iMac local % ls -la
total 29976
drwxr-xr-x   3 root        wheel        96 25 Feb 16:42 .
drwxr-xr-x@ 11 root        wheel       352  1 Jan  2020 ..
-rwxr-xr-x@  1 mattwilcox  staff  15343840 24 Feb 23:19 bin
```

Doesn't seem to be a symlink either - but I'm not used to zsh's output.

**Comment by MattWilcox** [comment]
Willing to be that /bin didn't exist and the command has put the `nitro` file _as_ bin. Not got it booted at the moment, but will check... may need to pass a -p flag on the command to ensure if bin isn't there it gets created.

**Comment by MattWilcox** [comment]
That appears to have been the issue - on a default new OSX 11 install, there is no /usr/local/bin directory.

Now I've manually made that the instruction works, but trying to run `nitro` results in

```
“nitro” cannot be opened because the developer cannot be verified.
macOS cannot verify that this app is free from malware.
```

**Comment by MattWilcox** [comment]
Right Click > Open allows that to run.
Then did `xattr -dr com.apple.quarantine /usr/local/bin/nitro`

Then got the following error...

```
mattwilcox@Matts-iMac ~ % nitro init
Checking Nitro…
  … creating network ✓
  … pulling image ✓
  … creating volume ✓
  … creating proxy ✓
Checking network…
  ✓ network ready
Checking proxy…
  ✓ proxy ready
Checking databases…
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x16a2295]

goroutine 1 [running]:
github.com/craftcms/nitro/command/apply.NewCommand.func2(0xc00038e000, 0x1d96ad8, 0x0, 0x0, 0x195f640, 0x1d96ad8)
	/home/runner/work/nitro/nitro/command/apply/apply.go:235 +0x695
github.com/craftcms/nitro/command/initialize.NewCommand.func1(0xc000395340, 0x1d96ad8, 0x0, 0x0, 0x0, 0x0)
	/home/runner/work/nitro/nitro/command/initialize/initialize.go:107 +0x696
github.com/spf13/cobra.(*Command).execute(0xc000395340, 0x1d96ad8, 0x0, 0x0, 0xc000395340, 0x1d96ad8)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0x1d5aa20, 0x0, 0x174d720, 0xc00007e058)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
main.main()
	/home/runner/work/nitro/nitro/cmd/nitro/main.go:11 +0x2a
mattwilcox@Matts-iMac ~ %
```

**Comment by jasonmccallister** [comment]
Can you provide the output of `echo $PATH` to show what the default paths are on your machine?

**Comment by MattWilcox** [comment]
```
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

It's in the path, but by default on this fresh machine, /usr/local didn't have a bin directory, and I _think_ it was totally empty. It now has a lib directory, but I've installed other things since then.

**Comment by jasonmccallister** [comment]
I wonder if Brew is adding that path as most of use have that running. I will look into this a little more.

**Comment by MattWilcox** [comment]
Just for clarification; I'm not using Brew (I avoid it in general).

**Comment by angrybrad** [comment]
Resolved in docs here: https://github.com/craftcms/docs/commit/4c401645bf71ac8cf8f36164709b10296d835b27
