### ISSUE TITLE
[2.0.0-beta7] WSL certutil message potentially wants new line break inserting

### ISSUE THREAD

**Issue by jamesmacwhite** [craftcms/nitro#257]
### Description

Super picky and minor but the WSL certificate guidance does not have a new line after, which means the "certificates are now trusted" message gets wrapped with it in console. Example:

```
  … getting Nitro’s root site certificate… ✓
Installing certificate (you might be prompted for your password)
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
Users on WSL will need to open a command prompt or terminal on Windows and run the following command:
certutil -addstore -f "Root" \\wsl$\Ubuntu-20.04\home\jameswhite\.nitro\nitro.crtNitro certificates are now trusted 🔒
```

**Comment by jasonmccallister** [comment]
Ah, good catch @jamesmacwhite! I will fix that for the next release!

**Comment by jamesmacwhite** [comment]
@jasonmccallister Might also be worth clarifying certutil needs to be run as administrator. So an elevated Command Prompt/PowerShell session is needed. Maybe something like:

> Users on WSL will need to open an elevated (run as administrator) Command Prompt or terminal on Windows and run the following command:

**Comment by jasonmccallister** [comment]
This was released with the latest beta!
