### ISSUE TITLE
Detect WSL for correct hosts file path to be modified

### ISSUE THREAD

**Issue by jamesmacwhite** [craftcms/nitro#258]
### Description

Currently Nitro 2.x under WSL will write hosts file contents to `/etc/hosts` within the WSL distribution, which has to be manually copied to C:\Windows\System32\drivers\etc\hosts. 

Looking in hosts.go there is a Windows condition using runtime: https://github.com/craftcms/nitro/blob/develop/command/hosts/hosts.go#L40-L44 but this will evaluate to false as the runtime will appear as Linux I'd imagine.

WSL will expose the Windows host filesystem through `/mnt/c/` and the hosts file of the Windows system can be accessed through `/mnt/c/Windows/System32/drivers/etc/hosts`. With elevated permissions with sudo WSL should be able to write to this file. Detecting WSL should be possible through an env var like `WSL_DISTRO_NAME` which will be set in whatever distribution used.

Just as a future addition to remove one less manual step for WSL usage.

**Comment by jasonmccallister** [comment]
@jamesmacwhite thank you for the heads up, we are using that environment variable here: https://github.com/craftcms/nitro/blob/develop/pkg/certinstall/certinstall.go#L76 but can certainly take advantage of that in the hosts file. 

It might make sense for WSL users to can both the WSL and Windows host files edited. The last time I looked into WSL it was not possible to edit the windows file, but I will certainly take another look!

**Comment by jamesmacwhite** [comment]
Ah, you might be right. So my test case fails even with sudo:

```
jameswhite@DWC100-3XSPC:~$ echo 'write test' | sudo tee -a /mnt/c/Windows/System32/drivers/etc/hosts > /dev/null
[sudo] password for jameswhite:
tee: /mnt/c/Windows/System32/drivers/etc/hosts: Permission denied
```

However, if the WSL session is "run as administrator", you can write to the hosts file with sudo. So unless the WSL has elevated privileges, Nitro isn't going to be able to write to hosts easily I don't think.

**Comment by jasonmccallister** [comment]
Ok that makes a little more sense, if you run as an administrator it will write to the windows file though?

**Comment by jamesmacwhite** [comment]
Yes if the WSL console was started with "run as administrator" and I then repeat the same command with sudo "write test" is appended to the Windows hosts file at C:\. The main requirement is an elevated session to begin with though.

**Comment by jasonmccallister** [comment]
We had the same setting for running v1, maybe we should consider this as well @angrybrad?

**Comment by angrybrad** [comment]
I'll play around with this a bit.

**Comment by angrybrad** [comment]
@jasonmccallister WSL1, if I recall, told you they definitely didn't want you to edit Linux files from Windows, but you could go the other way around. I believe WSL2 resolved most of those issues, though.

I guess the question is, will we be able to access `/mnt/c/Windows/System32/drivers/etc/hosts` from Golang to append whatever we want?

If so, I've got no problem updating the docs to require WSL users to launch their WSL instance using administrator privileges (we required that for Nitro 1, too).

**Comment by jasonmccallister** [comment]
I'm pretty sure we can close this issue out with the changes we have made to the 2.0.x releases?

**Comment by jasonmccallister** [comment]
Closing this out, if this is still an issue we can open a new issue referencing this issue for history!
