### ISSUE TITLE
[2.0.0-beta.7] Configured webroot always seems to be web for nginx?

### ISSUE THREAD

**Issue by jamesmacwhite** [craftcms/nitro#260]
### Description

I don't know how well Craft 2 sites are technically supported with Nitro 2 but I decided to test it out, given I've already got some Docker based environments based on the Craft CMS docker images. It seems the webroot despite being set to public in the nitro site config, nginx has been configured to look within /app/web. 

I get 404 on any requests when the webroot is "public", however if I create a web folder and then a simple PHP file, it then works, so this suggests nginx is always pointed to /app/web? Assuming this might be upstream from the main docker images?

I have Craft 2 projects using the Docker images at craftcms/docker, but with a modified nginx configuration, so I guess that's probably why it doesn't work.

**Comment by jasonmccallister** [comment]
@jamesmacwhite can you verify your sites webroot is not set to "web". We check that and modify the configuration at the container start time. However, we have identified a bug that could cause errors during the process and already fixed for the next release.

Also, can you run `nitro logs` on the site and provide the output here?

**Comment by jamesmacwhite** [comment]
Weirdly after provisioning the site again from scratch, the webroot is now respected and it's pointing to public. Not sure how it ended up at web in the first place, strange!

**Comment by jasonmccallister** [comment]
It was most likely related to the bug identified last week and will be resolved in the next release.

**Comment by jamesmacwhite** [comment]
Great. Nice that Nitro works with older Craft 2 projects as well!

**Comment by jasonmccallister** [comment]
This was released in the latest beta!
