### ISSUE TITLE
[2.0.0-beta.7] nitro self-update fails without elevated privileges  

### ISSUE THREAD

**Issue by jamesmacwhite** [craftcms/nitro#265]
### Description

Running `nitro self-update` without sudo errors with a permission denied error, because it can't copy the new binary to `/usr/local/bin`, would it be possible to check for elevated privileges before attempting the command or similar to how the hosts file is modified, ask to be elevated when the new binary needs to be copied?

```
jameswhite@LWC100-RAZBL15:~$ nitro self-update
Checking for updates
  … found version 2.0.0-beta.7 updating ✓
Updating to Nitro 2.0.0-beta.7!
Error: open /usr/local/bin/.nitro.new: permission denied
jameswhite@LWC100-RAZBL15:~$ sudo nitro self-update
[sudo] password for jameswhite:
Checking for updates
  … found version 2.0.0-beta.7 updating ✓
Updating to Nitro 2.0.0-beta.7!
```

**Comment by jasonmccallister** [comment]
@jamesmacwhite thank you for the report, I'm not sure if we should check/require elevated permissions as there are installations that do not require sudo. 

I would resort to the `self-update` command as more of a last resort, we are contemplating adding .deb files for the builds to make the process of installing/updating easier on Linux distributions so I would be curious to hear your thoughts.

**Comment by jamesmacwhite** [comment]
Me being lazy, I've just been using `nitro self-update` to replace the beta binaries, rather than having to manually extract a tar and mv the binary! Interesting it's not required on all environments. I figured because of the path being /usr/local/bin it would need to be elevated, this was on WSL, as you probably know I use.

Package management would be interesting. Although, `nitro self-update` would seem to be a easy way to do without having to be involved with building a .deb or package. The issue you'll have in Linux land is .deb is just one of the many package formats for certain distributions (in this case anything Debian based). Perhaps if it's contained within nitro itself it's a bit more Linux distro agnostic with a compiled static binary. Even with WSL, while typically Ubuntu is a common choice, there's also a Fedora which would be rpm, openSUSE and other options. That's the problem with Linux and building software, if you go down the package management route, you suddenly realise the amount of formats, .deb, rpm, there's now also the use of snap as well. FUUUUUN.

**Comment by jasonmccallister** [comment]
I'm all about being lazy when it comes to updating and the `self-update` command is exactly what that is for :)

We use a tool called goreleaser that makes all of these integrations easy for us to add. Specifically the `npmfs` tool which supports all of the common distros... In fact I added it this morning to build on the next release: https://github.com/craftcms/nitro/commit/b23fa702d1c761f58077145268664936c4b86ae6.

**Comment by jamesmacwhite** [comment]
Ah nice! Offload that complicated mess to some other library, it's the way forward! That's what the cloud is all about right?! Package versions is certainly a good way forward then, I may still use nitro self-update, because again.. lazy ha ha.

**Comment by jasonmccallister** [comment]
@jamesmacwhite not sure if we are going to require sudo permissions to run this command as it enforces the binary to require sudo permissions.

Alternatively, we are entertaining the idea of creating a small apt repository to allow `apt-get install nitro` so we most likely will not force sudo users before running this command.

Did `sudo nitro self-update` work for you?

**Comment by jamesmacwhite** [comment]
Yes. Doing `sudo nitro self-update` works. I'll condition myself to just prepend sudo before it, so it's fine. I wondered if it was something required all on environments but sounds like it isn't, so could just be an additional Windows specific reference in the docs perhaps.

**Comment by jasonmccallister** [comment]
Going to close this out. Thank you @jamesmacwhite!
