### ISSUE TITLE
`nitro: command not found` on install using curl command

### ISSUE THREAD

**Issue by kblizeck** [craftcms/nitro#272]
### Description
- Following [Documentation here](https://craftcms.com/docs/nitro/2.x/installation.html#installing-nitro) for installing Nitro

### Steps to reproduce

1. Installed Docker Desktop 3.1.0 (made sure it was running)
2. Opened an iTerm window and ran `bash <(curl -sLS http://installer.getnitro.sh)`
3. Receive below message

```
~/Local Sites  > bash <(curl -sLS http://installer.getnitro.sh)
/dev/fd/11: line 119: [: /Users/kblizeck/Local: binary operator expected
Downloading package https://github.com/craftcms/nitro/releases/download/2.0.3/nitro_darwin_x86_64.tar.gz to /Users/kblizeck/Local Sites/temp_nitro_extract/nitro_darwin_x86_64.tar.gz

curl: (23) Failed writing body (0 != 927)
/dev/fd/11: line 197: nitro: command not found
```

### Additional info

- Nitro version: N/A
- Docker version: 3.1.0

**Comment by jasonmccallister** [comment]
@kblizeck it might be the space in your path that is causing the error, can you try running the install command from your home directory and not `Local Sites`?

**Comment by angrybrad** [comment]
Fixed in https://github.com/craftcms/nitro/commit/e1da66122b225744a09e0ce9fe775f6415847165

The installer will now work if it is run from a working directory that has spaces in the path.

**Comment by kblizeck** [comment]
Thank you @angrybrad!
