### ISSUE TITLE
Database not created with 'nitro add', errors when trying to add later with 'nitro db add' or mySQL GUI

### ISSUE THREAD

**Issue by artmem** [craftcms/nitro#275]
### Description
Running a  new install of Docker and Nitro. 'Nitro add' seems to work -- asks if I want to add a database, asks for the name, says it was created, etc. But it doesn't seem to be creating the databases.

When I load the site, I get a 503 error.
If I run 'nitro db remove', there are no databases: 
`  … removing nitro Error: rpc error: code = Internal desc = error removing database: Exit Status: 1
Commands: --user=nitro --host=mysql-8.0-3306.database.nitro -pnitro -e DROP DATABASE IF EXISTS nitro;
`

If I run 'nitro db add' it asks for the db name, and then I get this error:
`  … creating database test Error: rpc error: code = Internal desc = error creating database: Exit Status: 1
Commands: --user=nitro --host=mysql-8.0-3306.database.nitro -pnitro -e CREATE DATABASE IF NOT EXISTS test;
`

I can connect to mySQL using Sequel Ace, via mysql-8.0-3306.database.nitro, but the only database is an empty 'nitro' db. If I try to add a db using the app, I get this error:
`Couldn't create database. MySQL said: Access denied for user 'nitro'@'%' to database 'test'`

Not sure if it is related, but the first time I tried to create a database, I got the warning: "✗ database must not include any special characters except underscores". I then changed the name, and it said the db was created, but it wasn't.

### Steps to reproduce
1. Install Nitro
2. Nitro Add
3. Try to interact with a database.

- Nitro version: 2.0.4
- Docker version: 20.10.3
-  macOS 11.2.2

**Comment by pom-pom** [comment]
I'm having the exact same issue as described, also on a Mac

**Comment by jasonmccallister** [comment]
@artmem and @pom-pom, I have identified the issue and will resolve this with the next release.

**Comment by jasonmccallister** [comment]
To fix this now, you can run the following commands, which should have been run during the init process. You should only have to do this once!

1. `nitro db ssh`
2. `mysql -uroot -pnitro -e "CREATE USER IF NOT EXISTS 'nitro'@'localhost' IDENTIFIED BY 'nitro';"`
3. `mysql -uroot -pnitro -e "GRANT ALL PRIVILEGES ON *.* TO 'nitro'@'%';"`
4. `mysql -uroot -pnitro -e "GRANT ALL PRIVILEGES ON *.* TO 'nitro'@'localhost';"`
5. `mysql -uroot -pnitro -e "FLUSH PRIVILEGES;"`

**Comment by ctmaloney** [comment]
This is still a thing...

nitro version 2.0.9
docker 20.10.12
MacOS 12.1
