### ISSUE TITLE
Test Windows/Linux support

### ISSUE THREAD

**Issue by angrybrad** [craftcms/nitro#28]

**Comment by nevsie** [comment]
Willing to Windows Test
Win10 Pro - Build 18362 Currently

**Comment by simeon-smith** [comment]
I can test on Windows.

**Comment by angrybrad** [comment]
Thanks, all... Linux support is solid and Windows is a WIP you can follow in this [issue](https://github.com/craftcms/nitro/issues/88) - getting pretty close to done now.  Going to go ahead and close this one.
