### ISSUE TITLE
PDO Drivers are limited?

### ISSUE THREAD

**Issue by MattWilcox** [craftcms/nitro#282]
### Description

Yii supports PHP PDO and ought to be able to connect to many database types. I was using the Connect plugin to try to connect to an MSSQL database externally; but it looks like the Nitro images only include PDO drivers for mysql and pgsql; which means it's not possible to use Connect or Yii with other database types.

https://github.com/nystudio107/craft-connect/issues/11

Would it be possible to include the PDO drivers for other database types than what Craft itself runs on?

- Nitro version: 1.0

**Comment by jasonmccallister** [comment]
@MattWilcox Craft does not support MSSQL out of the box so we do not install the drivers for interacting with that type of database. 

If you are on Nitro 2, you can run `nitro ssh --root` and install additional packages with `apk add <package>`. A complete list of packages is [available here](https://pkgs.alpinelinux.org/packages). 

It does not appear there is a mssql package in Alpine (I have not worked with that database in ages), so it may require manual installation? Perhaps just the plain pdo driver would work? You can see a lit of extensions available with `nitro extensions`.

**Comment by jasonmccallister** [comment]
I did find this instruction from the Microsoft documentation for setting the drivers in Alpine Linux: https://docs.microsoft.com/en-us/sql/connect/php/installation-tutorial-linux-mac?view=sql-server-2017#installing-the-drivers-on-alpine-311-and-312

**Comment by MattWilcox** [comment]
Yeah, I'm only after the PDO driver. The database is offsite and off server, but the docs would indicate that Yii2 should be able to connect to MSSQL no issue; the problem appears to be only that Nitro does not ship with the PDO Drivers for anything other than mysql and pgsql.

**Comment by MattWilcox** [comment]
Thanks for looking into this Jason. I've not managed to get the drivers installed manually as there's some issue with the scripts MS provide...

```
/app # pecl install sqlsrv
xtension=pdo_sqlsrv.so >> `php --ini | grep "Scan for additional .ini files" | sed -e "s|.*:\s*||"`/10_pdo_sqlsrv.ini
echo extension=sqlsrv.so >> `php --ini | grep "Scan for additional .ini files" | sed -e "s|.*:\s*||"`/00_sqlsrv.ini
downloading sqlsrv-5.9.0.tgz ...
Starting to download sqlsrv-5.9.0.tgz (189,701 bytes)
.........................................done: 189,701 bytes
34 source files, building
running: phpize
Configuring for:
PHP Api Version:         20190902
Zend Module Api No:      20190902
Zend Extension Api No:   320190902
Cannot find autoconf. Please check your autoconf installation and the
$PHP_AUTOCONF environment variable. Then, rerun this script.

ERROR: `phpize' failed
```

Not to mention this "would be ephemeral" as the nitro ssh --root warning mentions.

I don't think working with MSSQL is a go, and this is clearly outside of the scope of Nitro and Craft's goals at the moment.
