### ISSUE TITLE
`nitro start myproject.nitro`

### ISSUE THREAD

**Issue by lindseydiloreto** [craftcms/nitro#283]
I've recently been trying (and failing) to start only a single project using the following command...

```
nitro start myproject.nitro
```

I soon came to discover that `nitro start` does not work like that, and the project specification was being ignored.

Could it though? It would be awesome if we could only start a single project at a time (and its related dependencies).

**Comment by jasonmccallister** [comment]
Just released 2.0.7 with this change!

**Comment by lindseydiloreto** [comment]
Awesome, thanks @jasonmccallister! 🍺

**Comment by lindseydiloreto** [comment]
Finally got a chance to test this in the real world, and it worked perfectly! Thanks again! 👏
