### ISSUE TITLE
Can't remove database: "rpc error"

### ISSUE THREAD

**Issue by jskrivanek** [craftcms/nitro#286]
### Description

Would like to remove a database via `$ nitro db remove`.

Error message after executing the command above:
```… removing Database Error: rpc error: code = Internal desc = error removing database: unable to start the command: fork/exec /usr/bin/mysql: invalid argument```

### Steps to reproduce

1. `$ nitro start`
2. `$ nitro db remove`

### Additional info

- Nitro version: 2.0.5
- Docker version: 3.2.1 (61626)

**Comment by jasonmccallister** [comment]
@jskrivanek did you happen to create your environment on an earlier version of Nitro? 

The command is saying the mysql tool is not installed, you might be able to run `nitro update` to pull the latest Docker images from Docker Hub and Nitro will recreate the containers for you. That should resolve it but let us know if it does not!

**Comment by jskrivanek** [comment]
@jasonmccallister Correct, did `nitro update` now and restarted (though `nitro update` is automatically executed after `nitro self-update`). Now I get an extended error:

```… removing ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) Error: rpc error: code = Internal desc = error removing database: Exit Status: 1
Commands: --user=nitro --host=mysql-8.0.23-3306.database.nitro -pnitro -e DROP DATABASE IF EXISTS ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2);```

Same with a backup (only one project):

```❯ nitro db backup
Getting ready to backup…
There is only one database to backup…
Preparing backup…
  … creating backup Database-2021-03-10-152552.sql ✗
Error: unable to backup the database, Error response from daemon: lstat /var/lib/docker/overlay2/63795f4e15e2c459ac51e9c957a0971b6fbcfd8a6df886ca9e13f424d9b52053/merged/tmp/Database-2021-03-10-152552.sql: invalid argument```

**Comment by ademers** [comment]
On 2.0.6, and was getting `removing example_craft3 Error: rpc error: code = Internal desc = error removing database: Exit Status: 1` I did what you suggested above and was able to then run command without error.

**Comment by reachpriti12** [comment]
Hello, I want to remove this unnecessary database  `rDatabase` from my MYSQL container. I am not sure why it is created and what is the purpose of it. I have never created database called `rDatabase`
<img width="823" alt="Screen Shot 2022-03-29 at 9 46 17 PM" src="https://user-images.githubusercontent.com/31907075/160572165-24a18ecd-8d47-42fe-9662-7b9fefdcb273.png">




When I try to remove this via `nitro db remove`, I keep getting this error
`  … removing rDatabase Error: rpc error: code = Internal desc = error removing database: unable to start the command: fork/exec /usr/bin/mysql: invalid argument`

**Comment by jasonmccallister** [comment]
Hi, we are closing this issue as we have decided to retire Nitro, so no additional work will occur on this project. You can read the official blog post here https://craftcms.com/blog/retiring-craft-nitro. We appreciate everyones feedback and involvement and we look forward to refocusing our efforts on Cloud! 

If you're looking for a new local development environment, we recommend DDEV and have a knowledge base article to help you with the transition: https://craftcms.com/knowledge-base/migrating-from-craft-nitro-to-ddev.
