### ISSUE TITLE
Windows `trust` command suggestion includes newline and cruft

### ISSUE THREAD

**Issue by mattstein** [craftcms/nitro#291]
### Description

When running `nitro trust` in WSL2, this exact output is printed as shown:

```
Users on WSL will need to open an elevated (run as administrator) Command Prompt or terminal on Windows and run the following command:
certutil -addstore -f "Root" \\wsl$\Ubuntu-20.04\home\username\.nitro\nitro.crt\nNitro certificates are now trusted 🔒
```

If one literally copies the following as instructed, disappointment will follow:

```
certutil -addstore -f "Root" \\wsl$\Ubuntu-20.04\home\username\.nitro\nitro.crt\nNitro certificates are now trusted 🔒
```

But the line should obviously read:

```
certutil -addstore -f "Root" \\wsl$\Ubuntu-20.04\home\username\.nitro\nitro.crt
```

### Steps to reproduce

1. Make sure Nitro is running in Windows and open an Ubuntu shell.
2. Run the `nitro trust` command.
3. Observe output as stated above.
4. Run corrected `certutil` command before line break and rejoice, but with hesitation.

### Additional info

- Nitro version: 2.0.5
- Docker Desktop 3.2.1, Docker API 1.41
- Ubuntu 20.04 WSL2
- Windows 10 Pro 10.0.19041

**Comment by jamesmacwhite** [comment]
Possible regression from: https://github.com/craftcms/nitro/issues/257

**Comment by jamiematrix** [comment]
Will this also fix the same message displayed when running `nitro init` using WSL? Assuming init process also runs `nitro trust` at the completion stage?

**Comment by jasonmccallister** [comment]
@jamiematrix yes that is correct. The `init` command calls the `trust` command right after so fixing it there will resolve both.
