### ISSUE TITLE
Alternate TLD suffix

### ISSUE THREAD

**Issue by lindseydiloreto** [craftcms/nitro#292]
By default, Nitro assumes that we want our local URLs to end in `.nitro`. Would it be possible to override the default TLD?

For example, we use the common practice of having a `.test` suffix. It would be great if we could specify that as the default!

I love that Nitro will automatically assume the folder name for the local URL. If we could specify the TLD, it would make that feature even more helpful. 🙂

**Comment by jamesmacwhite** [comment]
I believe this is possible through environment variables.

https://craftcms.com/docs/nitro/2.x/customizing.html#nitro-environment-variables

`NITRO_DEFAULT_TLD`

**Comment by jasonmccallister** [comment]
@lindseydiloreto... @jamesmacwhite literally beat me to the punch there!

You can add the following to your `~/.zshrc` file to set the environment variable:

```
export NITRO_DEFAULT_TLD="test"
```  

That will be used the next time to open your shell!

**Comment by mattstein** [comment]
Oh come on. Actually knew something and showed up three minutes too late.

**Comment by lindseydiloreto** [comment]
Ahh, fantastic! Can that same approach be used to address #259?
