### ISSUE TITLE
Specify database name in db import command

### ISSUE THREAD

**Issue by stenvdb** [craftcms/nitro#293]
Would be handy to be able to specify the database name in the nitro db import command. That way it would be a single command without the extra prompt and is easier to integrate with some pipeline / deployment process.

**Comment by jasonmccallister** [comment]
@stenvdb would something like `nitro db import --name mydb my backup.sql` and having it skip the prompt work?

**Comment by stenvdb** [comment]
Yes exactly! I have a bash script that fetches a remote db and imports it, this would help.
