### ISSUE TITLE
nitro craft command doesn't accept flags

### ISSUE THREAD

**Issue by michaelroper** [craftcms/nitro#301]
Not sure if this related to one of the other issues you mentioned that you're already working on (#285), but the `nitro craft` command doesn't seem to accept passing flags through either?

It doesn't work from my local machine:
```sh
➜ nitro craft resave/entries --element-id 13899
Error: unknown flag: --element-id
```

but from within the container works as expected:
```sh
➜ nitro ssh
connecting to www-cms.test
/app $ ./craft resave/entries --element-id 13899
Resaving 1 entry ...
    - [1/1] Resaving About us (13899) ... done
Done resaving entry.
```

### Additional info

- Nitro version: 2.0.6
- Docker version: 20.10.5 (the engine version, right?)

**Comment by jasonmccallister** [comment]
Just pushed this up for the next release, also added the same to the `queue` command. Will go out with the next release!
