### ISSUE TITLE
Add command to remove custom containers

### ISSUE THREAD

**Issue by ademers** [craftcms/nitro#303]
### Description

Add a command `nitro container remove` or `nitro container rm` to remove custom containers created via the existing `nitro container new` command. This command should remove the relevant key/value pairs in the `nitro.yaml` file, so that the containers don't get recreated.

See Discord: https://discord.com/channels/456442477667418113/707324026577485934/821858164877819995

Thanks for your consideration!

**Comment by jasonmccallister** [comment]
Just pushed this change up and it will go out with the next release! The next release will also include a lot of aliases for commands (e.g. `nitro container remove` can be called with `nitro container rm`).
