### ISSUE TITLE
File/image uploading issues: "Does not appear to be an image"

### ISSUE THREAD

**Issue by jayhlee** [craftcms/nitro#305]
### Description
When I try to upload an image, I get error stating that `The file "/app/storage/runtime/temp/myimage-6054d5e1566465.0909298.jpg" does not appear to be an image.` The file is definitely an image, however. I set the permissions on my "storage" folder to 777 (in case it was a permissions issue), but that didn't resolve the issue. Adding an image directly within my assets folder and then rebuilding the asset index seems to work and show the file within the CP, although curiously, the thumbnail of my images don't show. Just the default Craft JPG icon shows.

For my asset volume: 
`Volume Type` is set to `Local Folder`
`Base URL` is set to `https://mysite.test/assets/images/portraits`
`File System Path` is set to `@webroot/assets/images/portraits`

### Steps to reproduce

1. Try to upload an image via an asset field in an entry or directly within Assets area of CP.

### Additional info

- Nitro version: nitro version 2.0.0-beta.4
- Docker version: 20.10.1, build 831ebeae96
- Running Mac M1, MacOS 11.2.3

**Comment by angrybrad** [comment]
Are you using PHP 8?

**Comment by angrybrad** [comment]
Also, probably worth updating to the latest 2.0.6 release - you're still running a beta version.

**Comment by jayhlee** [comment]
@angrybrad Yes, running PHP 8. I also just upgraded to Nitro 2.0.6 (and restarted Nitro), but that didn't seem to iron out the issue.

**Comment by jayhlee** [comment]
@angrybrad Just downgraded to PHP 7.4 and all seems to work. I guess it's a PHP 8 thing.

**Comment by angrybrad** [comment]
You're probably uploading an image in a format that GD doesn't support and Imagick doesn't have an official PHP 8 release yet because of https://github.com/Imagick/imagick/issues/358

So you'll probably need to stick with PHP 7.x for now.
