### ISSUE TITLE
Craft install error -  Function must be enabled in php.ini by setting 'xdebug.mode' to 'develop'

### ISSUE THREAD

**Issue by johnwbaxter** [craftcms/nitro#308]
### Description

I'm on Pop_Os 20.10

I ran `nitro create` and after installing the site ( i had permissions issues too https://github.com/craftcms/nitro/issues/280 ) I then ran through the craft installed and it got the install part and then failed with this error:

[21-Mar-2021 16:55:12 UTC] PHP Warning:  Function must be enabled in php.ini by setting 'xdebug.mode' to 'develop' in /app/vendor/yiisoft/yii2/base/ErrorException.php on line 50

### Steps to reproduce

1. Be on Linux
2. Run nitro create
3. Run the craft installer

### Additional info

- Nitro version: 2.0.6
- Docker version: 20.10.4 build d3cb89e

**Comment by jasonmccallister** [comment]
@johnwbaxter I'm going to look into this this week, It did not prevent you from using Nitro though since it was a warning right? I'll be using my Pop_Os computer most of this week to also focus on the permissions issues as well. Do you have xdebug enabled on that site by chance?

**Comment by jasonmccallister** [comment]
Can you verify your ErrorException.php class in your vendor folder matches this? https://github.com/yiisoft/yii2/blob/master/framework/base/ErrorException.php#L50

**Comment by johnwbaxter** [comment]
Yep, it does!

**Comment by jasonmccallister** [comment]
Just released 2.0.7 with better support on Linux machines.
