### ISSUE TITLE
Nitro 2 and missing databases

### ISSUE THREAD

**Issue by cbad-mvd** [craftcms/nitro#309]
### Description
My system crashed while docker/nitro was open. After a reboot and restarting docker/nitro it appears all my databases are missing. Here's the response when trying to do nitro db commands:

» nitro db ssh
Select a database to connect to:
Enter your selection:

No databases to select from. Before the crash, there were four or maybe five databases. Any ideas on how to proceed?

### Steps to reproduce

1. I wish I had something to provide. I don't think this happens every time a crash occurs, but hard to say. 

### Additional info
I haven't done anything in case there is some useful information available. But I do need to move forward, maybe by just attempting to recreate the databases that are missing. I have fairly recent, 

- Nitro version: 2.04
- Docker version: 3.2.1 (61626)

**Comment by jasonmccallister** [comment]
@cbad-mvd your databases are stored in volumes, so unless to ran `nitro destroy` or manually pruned the Docker system, it should still be there. Can you run `nitro start` and verify it creates all of the sites and databases you have defined in your `nitro.yaml`?

**Comment by cbad-mvd** [comment]
I agree it seems like they should be there, but I can't access them any longer. Here is the result from nitro start:

`» nitro start
Starting Nitro…
  … starting craftpro.nitro ✓
  … starting craftsolo.nitro ✓
  … starting promark.nitro ✓
  … starting redis.service.nitro ✓
  … starting mysql-5.7-3306.database.nitro ✓
  … starting nitro-proxy ✓
Nitro started 👍`

I haven't run nitro destroy, but I did run 'nitro db remove' on a couple databases. These databases appeared to be left over from sites I had removed with 'nitro remove'. They databases were not removed by that command. After the 'nitro db remove', all sites still ran correctly until after the crash, and then all databases were gone.

They all used one engine (mysql-5.7-3306.database.nitro). Is that the best way to do it or is it better to create a new engine for each site?

**Comment by jasonmccallister** [comment]
> The databases were not removed by that command

By default, `nitro remove` does not remove the database to make sure we protect any data and prevent accidental deletion.

> but I can't access them any longer

Can you run `docker volume ls`? You should have volumes with the same name as the databases. 

Also, can you run `docker container ls` and verify the mysql database container is running?

**Comment by cbad-mvd** [comment]
```
» docker volume ls
DRIVER    VOLUME NAME
local     54fa599added53b7bf0a357c16581404a0006c66f6edfbbe7942db4c420e476c
local     109aa9b6e5873f7971faba7b257ec3f01e8c5dda3c37c7942d19b49f357ffe20
local     423b6a3b6dfc295474e678bc40c1b0178833d6285adecd6cca89eb292aac0cf1
local     bbe54fe6f7de46d33f2b80e1c3855d5dc20ef34cd17576ea60692dfb9b2d0244
local     mysql-5.7-3306.database.nitro
local     nitro
local     users_cbad_websites_nitro_test_cms_composer_7.4
```
and 
```
» docker container ls
CONTAINER ID   IMAGE                        COMMAND                  CREATED        STATUS             PORTS                                                                    NAMES
745adab71999   craftcms/nginx:7.4-dev       "/usr/bin/supervisor…"   43 hours ago   Up About an hour   8080/tcp, 9000/tcp, 9003/tcp                                             craftpro.nitro
1128c22133f3   craftcms/nginx:7.4-dev       "/usr/bin/supervisor…"   44 hours ago   Up About an hour   8080/tcp, 9000/tcp, 9003/tcp                                             craftsolo.nitro
2356defd856a   412226ba49f7                 "/usr/bin/supervisor…"   11 days ago    Up About an hour   8080/tcp, 9000/tcp, 9003/tcp                                             downlink.nitro
9c24de03b413   412226ba49f7                 "/usr/bin/supervisor…"   2 weeks ago    Up About an hour   8080/tcp, 9000/tcp, 9003/tcp                                             promark.nitro
e40ff8904e93   redis:latest                 "docker-entrypoint.s…"   2 weeks ago    Up About an hour   127.0.0.1:6379->6379/tcp                                                 redis.service.nitro
809eda8525e0   craftcms/nitro-proxy:2.0.4   "/usr/bin/supervisor…"   2 weeks ago    Up About an hour   127.0.0.1:80->80/tcp, 127.0.0.1:443->443/tcp, 127.0.0.1:5000->5000/tcp   nitro-proxy
```
No database names there and it doesn't appear the database engine container is running either (unless I'm missing something).

Thanks for looking at this!

**Comment by jasonmccallister** [comment]
The good news is that you have a volume for the databases, the fact the database does not show up means it's not running. 

1. Are you on macOS, Linux, or WSL?
2. If running Docker Desktop, how much RAM and CPU are allocated to the docker virtual machine (_preferences > resources)_?
3. Can you send the output of `docker container ls -a` (will show all containers regardless of their current status)?

MySQL containers can often crash when not enough resources (RAM and CPU) have been assigned.

**Comment by cbad-mvd** [comment]
I'm running macOS Catalina. Number of CPUs is 4. The memory was at 2 GB with a swap file of 1 GB. I upped memory to 4 GB with a swap file of 1.5 but didn't make a difference.
```
» docker container ls -a
CONTAINER ID   IMAGE                        COMMAND                  CREATED       STATUS                          PORTS                                                                    NAMES
745adab71999   craftcms/nginx:7.4-dev       "/usr/bin/supervisor…"   2 days ago    Up About a minute               8080/tcp, 9000/tcp, 9003/tcp                                             craftpro.nitro
1128c22133f3   craftcms/nginx:7.4-dev       "/usr/bin/supervisor…"   2 days ago    Up About a minute               8080/tcp, 9000/tcp, 9003/tcp                                             craftsolo.nitro
2356defd856a   412226ba49f7                 "/usr/bin/supervisor…"   12 days ago   Up About a minute               8080/tcp, 9000/tcp, 9003/tcp                                             downlink.nitro
9c24de03b413   412226ba49f7                 "/usr/bin/supervisor…"   2 weeks ago   Up About a minute               8080/tcp, 9000/tcp, 9003/tcp                                             promark.nitro
e40ff8904e93   redis:latest                 "docker-entrypoint.s…"   2 weeks ago   Up About a minute               127.0.0.1:6379->6379/tcp                                                 redis.service.nitro
3bf8c44a2552   mysql:5.7                    "docker-entrypoint.s…"   2 weeks ago   Exited (1) About a minute ago                                                                            mysql-5.7-3306.database.nitro
809eda8525e0   craftcms/nitro-proxy:2.0.4   "/usr/bin/supervisor…"   2 weeks ago   Up About a minute               127.0.0.1:80->80/tcp, 127.0.0.1:443->443/tcp, 127.0.0.1:5000->5000/tcp   nitro-proxy
d89ee1f0e2da   docker101tutorial:latest     "/docker-entrypoint.…"   2 weeks ago   Exited (0) 2 weeks ago                                                                                   wonderful_pascal
13ffe7327dc4   alpine/git:latest            "git --help"             2 weeks ago   Exited (0) 2 weeks ago                                                                                   Alpine-Git
8a30c52ef356   docker101tutorial            "/docker-entrypoint.…"   2 weeks ago   Created                                                                                                  docker-tutorial
3952be11338a   alpine/git                   "git clone https://g…"   2 weeks ago   Exited (0) 2 weeks ago                                                                                   repo
```
I just ran an update on Docker Desktop and ran this output just after I did a nitro start. It does show the mysql exiting right away.

**Comment by cbad-mvd** [comment]
Any update on this, need more info?

**Comment by jasonmccallister** [comment]
@cbad-mvd when you updated the RAM and restarted Docker, did you run `nitro start` again? Is the container still showing the exit status?

**Comment by cbad-mvd** [comment]
Yes, that output was provided after increased the RAM and then performed a nitro start. It exits on during initialization. I just tried it again with the same results. Maybe the docker log for the mysql container will help. Here it is at the point the errors start. If the full log would be more helpful, I can provide it.
```
2021-03-24T14:14:49.019470Z 0 [ERROR] InnoDB: Ignoring the redo log due to missing MLOG_CHECKPOINT between the checkpoint 127614250 and the end 127613952.
2021-03-24T14:14:49.019511Z 0 [ERROR] InnoDB: Plugin initialization aborted with error Generic error
2021-03-24T14:14:49.625407Z 0 [ERROR] Plugin 'InnoDB' init function returned error.
2021-03-24T14:14:49.625489Z 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
2021-03-24T14:14:49.625501Z 0 [ERROR] Failed to initialize builtin plugins.
2021-03-24T14:14:49.625505Z 0 [ERROR] Aborting
2021-03-24T14:14:49.625511Z 0 [Note] Binlog end
2021-03-24T14:14:49.625656Z 0 [Note] Shutting down plugin 'CSV'
2021-03-24T14:14:49.629318Z 0 [Note] mysqld: Shutdown complete
```
Let me know if something more would help...

**Comment by jasonmccallister** [comment]
That is a strange error I will need to lookup, do have a lot of databases in the container?

**Comment by cbad-mvd** [comment]
I think I have five maybe six. Maybe it has something to do with running nitro db remove to get rid of a couple databases?

**Comment by jasonmccallister** [comment]
Can you run `docker logs mysql-5.7-3306.database.nitro >> db_logs.txt` and send the complete output?

**Comment by cbad-mvd** [comment]
That command would output the full logo to screen but the file only included log items with the [Note] tag. So I included the full log as well in case it is useful. See attached.
[db_logs_full.txt](https://github.com/craftcms/nitro/files/6198304/db_logs_full.txt)
[db_logs.txt](https://github.com/craftcms/nitro/files/6198305/db_logs.txt)

**Comment by cbad-mvd** [comment]
It appears my databases are unrecoverable and I need to start over with Nitro. Shall I just do a nitro destroy to kill everything? Should I start over with a fresh copy of Docker as well, or will the destroy adequately clean it out?

Ideally going forward, I would like each site to be isolated from one another. Then if something like this happens again in the future, it only affects the site I'm currently working on. Is there a way currently to set Nitro up to do this?

**Comment by jasonmccallister** [comment]
@cbad-mvd to be frank, I'm not sure why the MySQL container data is corrupted. I read a little to see what I could find and this seemed relevant. We have had other people have the same issue with too little RAM and MySQL, but upping the resources and a restart helped.

If you are unable to get the database backup and running, I would recommend the following:

1. Remove the container with `docker container rm -f mysql-5.7-3306.database.nitro`
2. Remove the volume with `docker volume rm mysql-5.7-3306.database.nitro`
3. Then run `nitro apply` to recreate the container and volume

I'll keep an eye out for this issue but I have been running Docker with similar resources for a while now trying to reproduce...

**Comment by cbad-mvd** [comment]
@jasonmccallister after not hearing back I went the nitro destroy route. It had errors connecting to the mysql server, but that was no surprise. 

I then did a nitro init and since the nitro.yaml file was still there, it was painless. I imported my backup DBs and things just worked. I only lost data for the one site that was being actively worked on. So all in all not too bad.

There are two databases in there I don't recognize, I assume they are nitro databases. One is named QDatabase and one is named nitro. Am I right those are yours and shouldn't really be touched?

Anyway, thanks for your help. I still think it would be nice to have each site isolated from the others. Maybe something to think about.

**Comment by jasonmccallister** [comment]
@cbad-mvd those a defaults for the system, you can use the nitro database if you like. Glad you got it working, there is also the `nitro db backup` command to get a quick backup or you can use the control panel utility to back up.

Each site is its own container and isolated, but the databases are shared to reduce resource usage. @mattstein created a nice graphic on the [how it works](https://craftcms.com/docs/nitro/2.x/how-nitro-works.html#nitro-docker) page.
