### ISSUE TITLE
Nitro SSL cert is only valid 12 hours

### ISSUE THREAD

**Issue by tamlyn** [craftcms/nitro#311]
### Description

Every morning when I try to access my local Craft Nitro site I get an "Invalid certificate" warning page in Chrome. I have to run `nitro trust` to generate a new cert. But the cert it generates is only valid for 12 hours.

![image](https://user-images.githubusercontent.com/115310/112281660-36e9ec00-8c7e-11eb-82e3-6570acb40667.png)

### Steps to reproduce

I'm guessing this doesn't happen for everyone, but for me:

1. Run `nitro trust` 
2. Wait 12 hours

Expected: certificate to still be valid.

Actual: certificate is not valid.

### Additional info

- Nitro version: 2.0.4
- Docker version: 20.10.5

**Comment by jamesmacwhite** [comment]
You aren't the only one, I've noticed this as well for WSL. Restarting or stopping and starting Nitro also resolves it. I assume it's down to the Caddy Automatic HTTPS feature:

https://caddyserver.com/docs/automatic-https

I believe they are deliberately short life certs.

**Comment by jasonmccallister** [comment]
@tamlyn @jamesmacwhite is correct, this is the Caddy server setting short lived TLS. 

To resolve this, use `nitro restart` and the certificates will be renewed. 

We will be making some changes to the Caddy server with the next release, I will look to see if there is a way to increase the duration.

**Comment by jasonmccallister** [comment]
@tamlyn there is no way to increase the certificates creating for sites past 12 hours when creating local certificates.

However, I did read your original issue description incorrectly the first time. The certificate imported during `nitro trust` is the root certificate and we don't import the individual site certificates. Simply running `nitro restart` will refresh to certificates and the `nitro trust`  command only needs to be run one time.

I did speak with the lovely folks at Caddy and they did confirm that Caddy should be reissuing certificates about 8 hours in, so I'm not sure what is causing the certificates to expire. 

I'm going to keep the open and leave nitro running for 12+ hours so I can look into this more.

**Comment by mholt** [comment]
Browsers are notorious for not re-negotiating TLS connections when you leave tabs open, thus trying to reuse the same TLS cert. Guess they aren't cut out for short-lived certificates. (You can always verify with `curl -v` whether a cert is _actually_ trusted. The Caddy logs will also tell you if/when they get renewed. If you see a renewal but the browser still gives you an error, it's probably the browser.)

**Comment by jasonmccallister** [comment]
After some research, we are going to close this ticket out as we cannot increase the lifespan of certificates locally.
