### ISSUE TITLE
PHP 8's GD library isn't compiled to support JPGs

### ISSUE THREAD

**Issue by angrybrad** [craftcms/nitro#314]
### Description

You can't upload JPGs using PHP 8 in Craft using Nitro. You'll get this error:

> Upload failed. The error message was: “The file “(path to file in runtime temp path)” does not appear to be an image.

If you check phpinfo output, there should be a "JPEG Support: enabled" property, but it's missing.

This is unfortunate as Imagick also doesn't work in PHP 8: https://github.com/Imagick/imagick/issues/358

### Additional info

- Nitro version: 2.0.6
- Docker version: 3.2.2

**Comment by khalwat** [comment]
re: Imagick, this is not working for you? https://github.com/Imagick/imagick/issues/358#issuecomment-768586107

**Comment by khalwat** [comment]
To fix this for GD change this: https://github.com/craftcms/docker/blob/main/8.0/Dockerfile#L53

```
    docker-php-ext-configure gd && \
```

to this: https://github.com/nystudio107/docker-images/blob/master/php-prod-base/php-8.0-alpine/Dockerfile#L60

```
    docker-php-ext-configure \
        gd --with-freetype=/usr/include/ --with-jpeg=/usr/include/ \
```

**Comment by jasonmccallister** [comment]
We have an existing issue on the Docker images here: https://github.com/craftcms/docker/issues/25

I'll try to squeeze that into a release ASAP, working on the release for tomorrow right now.

**Comment by angrybrad** [comment]
This was resolved upstream in the docker images. You can run `nitro update` to pull them in.
