### ISSUE TITLE
Image transforms format webp/jpg broken

### ISSUE THREAD

**Issue by Paulexe** [craftcms/nitro#315]
Hi,

image transforms with target format webp/jpg are broken for me:

`TypeError
call_user_func_array(): Argument #1 ($callback) must be a valid callback, function "imagejpeg" not found or invalid function name`

`1. in /app/vendor/pixelandtonic/imagine/src/Gd/Image.php line 672`

Same problem as in #314 ?

### Steps to reproduce

1. Use image transform with target format webp/jpg

### Additional info

- Nitro version: 2.0.6 (WSL2)
- Docker version: Windows latest
- php version: 7.4 & 8

**Comment by angrybrad** [comment]
This should be resolved in the upstream Docker images if you want to `nitro update`.

Going to go ahead and close, but if you still run into it, comment back and we'll re-open.
