### ISSUE TITLE
webroot retains previous value after change

### ISSUE THREAD

**Issue by micahmorgan1** [craftcms/nitro#326]
### Description
I added a site with the wrong webroot (whlc.nitro), so I deleted and reinstalled the site with the correct webroot (web).  It shows correctly now in config webroot:web, but it throws a 404.  But when I make a whlc.nitro folder, it will launch from there.   

### Steps to reproduce

1.Install with incorrect webroot
2. delete site
3. reinstall site with same name/location setting webroot to (web)

### Additional info

- Nitro version:2.0.6
- Docker version:3.2.2

**Comment by jasonmccallister** [comment]
@micahmorgan1 I can confirm this and will work on getting this corrected!

**Comment by jasonmccallister** [comment]
This will go out with the next release, you may have to recreate the containers to get the new labels.
