### ISSUE TITLE
Version of Composer should be persisted (stored in site config in nitro.yaml)

### ISSUE THREAD

**Issue by benface** [craftcms/nitro#332]
I had a problem with my Docker installation and lost all my containers, so I had to recreate them with `nitro init`. Thanks to `nitro.yaml`'s declarative config, the new containers are identical to the old ones *except* for the version of Composer. I have some sites that aren't compatible with Composer 2, so I had followed the documented steps for [downgrading to Composer 1](https://craftcms.com/docs/nitro/2.x/composer.html#using-composer-1). I wish the version of Composer was a site setting that was stored in `nitro.yaml` and used when setting up a site's container. Would that be possible?

**Comment by jasonmccallister** [comment]
Hi @benface! We gave this some thought and since [composer 1 is now considered EOL](https://blog.packagist.com/deprecating-composer-1-support/) and there are instructions to downgrade to version 1 in Nitro, we are not going to support defining the composer version on a sites configuration.
