### ISSUE TITLE
Issue Pulling Database with Craft Scripts

### ISSUE THREAD

**Issue by clarknelson** [craftcms/nitro#334]
### Description
I would like to use these scripts (https://github.com/nystudio107/craft-scripts) to manage the database and assets between my live and development environments. When I try to connect to use pull_db.sh, I get this message: 'mysqldump: Got error: 1044: Access denied for user 'nitro'@'%' to database 'mydatabase' when selecting the database`.

It seems like I am able to connect fine using the mysql command in the cli. I don't really know where the `%` is coming from. 

### Steps to reproduce

1. Set up example.env.sh to connect to remote server and nitro db machine
2. Use pull_db.sh command to attempt to pull database

### Additional info

- Nitro version: 2.0.7
- Docker version: 20.10.5

**Comment by jasonmccallister** [comment]
@clarknelson took a quick look at the script, looks like you need to set the server hostname for the database to your information from `nitro context`.

**Comment by clarknelson** [comment]
I believe my problem was I did not have `php-mysql` installed
