### ISSUE TITLE
[FR] Please don't re-alphabetize YAML (or delete comments)

### ISSUE THREAD

**Issue by lindseydiloreto** [craftcms/nitro#335]
### Description

Every time a new project is added, the YAML file gets completely rewritten. It takes all of my projects and re-alphabetizes them (after I had intentionally sorted them). On a related note, it also erased all of my comments. 😕

Can we have the "add project" process be a little less intrusive? Maybe just append new projects to the end of the file?

**Comment by jasonmccallister** [comment]
Hi, we are closing this issue as we have decided to retire Nitro, so no additional work will occur on this project. You can read the official blog post here https://craftcms.com/blog/retiring-craft-nitro. We appreciate everyones feedback and involvement and we look forward to refocusing our efforts on Cloud! 

If you're looking for a new local development environment, we recommend DDEV and have a knowledge base article to help you with the transition: https://craftcms.com/knowledge-base/migrating-from-craft-nitro-to-ddev.
