### ISSUE TITLE
Connected to imported database not working

### ISSUE THREAD

**Issue by jayhlee** [craftcms/nitro#337]
### Description
I'm trying to migrate an existing site to use Nitro. I created and imported an existing database successfully using `nitro db import` and set all the correct `.env` values. But when I go to the Craft Control Panel, it takes me to the fresh install page. Seems like the db connection isn't being recognized. 

I'm not sure if it's related, but when I try to `nitro db backup`, I get an error:
`Error: unable to backup the database, Error response from daemon: lstat /var/lib/docker/overlay2/...: invalid argument.`

When I try to `nitro db remove`, I also get an error:
`removing Database Error: rpc error: code = Internal desc = error removing database: unable to start the command: fork/exec /usr/bin/mysql: invalid argument`

### Steps to reproduce
1. `nitro db import` (imported db is a MySql 5.7 file; db engine is mariadb 10.5)
2. Go to Craft CP. Shows fresh install page rather than CP admin login page.

### Additional info

- Nitro version: 2.0.7
- Docker version: 20.10.0 (Mac M1)

**Comment by jasonmccallister** [comment]
@jayhlee can you provide the `DB_*` configuration from your `.env`?

**Comment by jayhlee** [comment]
Sure. I actually destroyed everything and re-created everything, and everything seems to work now. However, I still get the same errors when I try to run `nitro db backup` and `nitro db remove`.

```
DB_DRIVER=mysql
DB_SERVER=mariadb-10.5-3306.database.nitro
DB_PORT=3306
DB_DATABASE=mydatabase
DB_USER=nitro
DB_PASSWORD=nitro
DB_SCHEMA=public
DB_TABLE_PREFIX=craft
```

**Comment by jasonmccallister** [comment]
@jayhlee can you run `nitro version` and send the output?

**Comment by jayhlee** [comment]
```
Nitro CLI: 	 2.0.7
Nitro gRPC: 	 2.0.7
Docker API: 	 1.41 (1.12 min)
Docker CLI: 	 1.41
```

**Comment by jasonmccallister** [comment]
@jayhlee can you provide the output of `docker system info`?

**Comment by jayhlee** [comment]
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., unknown)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.3.5)

Server:
 Containers: 10
  Running: 10
  Paused: 0
  Stopped: 0
 Images: 23
 Server Version: 20.10.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.104-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 6
 Total Memory: 11.69GiB
 Name: docker-desktop
 ID: UCXN:KGRL:MLHC:2A3Y:SAWW:KPSA:TDJJ:JTIX:DY57:F27H:MK7W:VVNX
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Comment by CharlieGentle** [comment]
FWIW, I am also having the same problem of going to the install screen after importing with `nitro db import` but when I import the same file through Sequel Pro, I don't have a problem. Running pretty much the same setup, going from MySql 5.7 file to mariadb 10.5 on a Mac M1 chip.

**Comment by jasonmccallister** [comment]
Hi, we are closing this issue as we have decided to retire Nitro, so no additional work will occur on this project. You can read the official blog post here https://craftcms.com/blog/retiring-craft-nitro. We appreciate everyones feedback and involvement and we look forward to refocusing our efforts on Cloud! 

If you're looking for a new local development environment, we recommend DDEV and have a knowledge base article to help you with the transition: https://craftcms.com/knowledge-base/migrating-from-craft-nitro-to-ddev.
