### ISSUE TITLE
Include SVGO, JPEGOPTIM, CWEBP, and OPTIPNG libraries

### ISSUE THREAD

**Issue by angrybrad** [craftcms/nitro#343]
### Description

Enough image manipulation plugins in the Craft ecosystem use the SVGO, JPEGOPTIM, CWEBP, and OPTIPNG libraries that we should consider including them by default.

Adding this to the Nitro repo, but not sure if we do it in Nitro itself or upstream in the docker images.

Currently, the only solution is to SSH into the site container and add them via NPM, Homebrew, etc. ephemerally, which is not ideal.

**Comment by aloco** [comment]
I would like to see them in the docker images since we are using them also on our servers.

**Comment by alexagui** [comment]
If anyone here because they're trying to figure out how to install Image Processors & Variant Creators in Nova.

Nova uses Alpine so you'll need to use [apk](https://wiki.alpinelinux.org/wiki/Alpine_Linux_package_management).

1. nitro ssh --root
2. apk add jpegoptim

**Comment by jasonmccallister** [comment]
We just published and pushed (thanks @timkelty) updates to the Docker images that should have the image processing libraries you need. Can you run `nitro update` and `nitro apply` to make sure you have the latest image from Docker Hub and try to use the image libraries again?

**Comment by jasonmccallister** [comment]
Hi, we are closing this issue as we have decided to retire Nitro, so no additional work will occur on this project. You can read the official blog post here https://craftcms.com/blog/retiring-craft-nitro. We appreciate everyones feedback and involvement and we look forward to refocusing our efforts on Cloud! 

If you're looking for a new local development environment, we recommend DDEV and have a knowledge base article to help you with the transition: https://craftcms.com/knowledge-base/migrating-from-craft-nitro-to-ddev.
