### ISSUE TITLE
Nitro Deploy

### ISSUE THREAD

**Issue by khalwat** [craftcms/nitro#347]
The ability to spin up a new project to work on in local dev is only a part of the battle; I'd then also like to be able to just type:

```
nitro deploy
```

or

```
nitro deploy staging
```

...or the like to take the local stuff I have, and deploy it to a remote server. Perhaps the ability to pick and choose what gets deployed too (code, database, static assets, etc.)

Might require some additional work on the remote server end of things, but ultimately closing the loop of development would be fantastic.

**Comment by jasonmccallister** [comment]
We have given this a lot of thought internally and had quite a few discussions about something similar, nothing to share yet though :)

**Comment by khalwat** [comment]
Yep, I figured

**Comment by frank-laemmer** [comment]
We (fortrabbit) are of course interested to make our [Craft Copy](https://github.com/fortrabbit/craft-copy) tool work with Craft Nitro. That way we could recommend Craft Nitro to our clients. 

We see: 

* That there is no way to [share the SSH keys](https://github.com/craftcms/nitro/issues/297) from the host system. 
* Some dependencies such as `ssh`, `rsync`, `zcat` are missing with Craft Nitro

Our questions: 

* What is the current suggested workflow to deploy a website that lives in Craft Nitro?
* Can you share a possible future workflow for this? Maybe adding the above features or opening up network capabilities?

**Comment by khalwat** [comment]
e.g.: https://ddev.readthedocs.io/en/stable/users/providers/acquia/

**Comment by jasonmccallister** [comment]
Hi, we are closing this issue as we have decided to retire Nitro, so no additional work will occur on this project. You can read the official blog post here https://craftcms.com/blog/retiring-craft-nitro. We appreciate everyones feedback and involvement and we look forward to refocusing our efforts on Cloud! 

If you're looking for a new local development environment, we recommend DDEV and have a knowledge base article to help you with the transition: https://craftcms.com/knowledge-base/migrating-from-craft-nitro-to-ddev.
