### ISSUE TITLE
Nitro Up... Shrink wrap the devops

### ISSUE THREAD

**Issue by khalwat** [craftcms/nitro#348]
A fantastic feature of Docker is that you can "shrink wrap" the devops of a project as config. So I can onboard someone by telling them to just pull down a Git repo, and type a single command, e.g.:

```
docker-compose up
```

or
```
make dev
```

...or the like, and it'll do everything that needs doing to spin up the local dev environment.

With Nitro currently, people have to clone the project down, have Nitro installed, and then create a new site, database, etc. for each project, so there's no way to have that zero-friction onboarding.

I'd love to see something in Nitro that'd be similar, e.g.:

```
nitro up
```

...and maybe as a bonus there being a way to specify a directory for the seed database when the project is first started up (or even better, a way to pull a database down from somewhere).

**Comment by khalwat** [comment]
> We also have planned to add support for project specific configs that can be included in the git repository for the project to allow teams to share configs (#259).

Right, this is what I'm referring to. With a pure Docker setup, it's easy to automate all of this, which makes onboarding wonderful. I'm glad you have plans for it.

Currently, there's no way automated way to do this.

> I'm not sure this is a Nitro concern, I would not want to automatically seed a database when running a command. I have seen people using composer scripts to meet this functionality, this allows them to run nitro composer <script> to automate that process for them. That would vary greatly from team to team so we should be careful not to enforce a workflow if that makes sense?

A feature that all of the various database containers offer is a [designated directory](https://onexlab-io.medium.com/docker-compose-mysql-database-seed-3bcbdfc51e8b) where if the database doesn't exist, the .sql, .gz, and .sh files in that directory are executed. This allows you to provide a seed db as part of the repo, which is super useful for project scaffolding purposes.

I'm just asking you to map this existing Docker feature into Nitro.

**Comment by jasonmccallister** [comment]
> I'm just asking you to map this existing Docker feature into Nitro.

This makes a lot of sense and I have done the [same in the past](https://stackoverflow.com/questions/43322033/create-database-on-docker-compose-startup/59653823#59653823). However, this is not a Docker feature and more of an image specific feature and there is no guarantee all images will have the same functionality. Nitro is setup to treat database containers as shared resources and forcing a seed process that is specific to an image and/or project does not really feel "right" - if that makes sense? I think it is better served as a composer script that can also be shared by the team.

_As a side note, I'm not a huge fan of sharing database dumps. I think this has the potential to expose a lot of PII._

**Comment by khalwat** [comment]
> Nitro is setup to treat database containers as shared resources and forcing a seed process that is specific to an image and/or project does not really feel "right" - if that makes sense?

Yeah, I'm thinking the shared database containers might be rethought -- for this reason, and also for memory/performance concerns.

People will accumulate dozens of projects over time, but typically only work on one or two of them at a time. I'm not sure the shared tenancy of the database container makes sense, but probably you have other reasons for doing that.

Having things degrade over time as more projects are added is probably not desired.

> As a side note, I'm not a huge fan of sharing database dumps. I think this has the potential to expose a lot of PII.

I agree with you normally, but for things like starter setups, it's beautiful. For this setup:

https://github.com/nystudio107/craft#setting-up-local-dev

You literally type two commands:

```
composer create-project nystudio107/craft PATH --no-install
make dev
```

...and you are up and running with a starter setup, everything provisioned, database seeded.

I of course agree with you for general use-cases re: sharing seed dbs. Better to pull it from production or elsewhere.

**Comment by angrybrad** [comment]
If I'm following, once https://github.com/craftcms/nitro/issues/259 is implemented, you're saying there should be a single command you can run that starts Nitro (if it isn't running), and automatically creates/updates the environment you just imported for ease of use? (automatic database importing aside)

**Comment by khalwat** [comment]
Right, for onboarding people, they should be able to do:

```
git clone
nitro start
```

...and everything would "just work" (database considerations aside) with it configuring all of the containers needed, any custom containers, everything. Wrapping the devops up with the project as config, just like you can do with a `docker-compose.yaml` file

**Comment by brandonkelly** [comment]
Sounds like we’re on the same page – this is basically the goal with #259. Will close this out in favor of that one.
