### ISSUE TITLE
Default nginx conf

### ISSUE THREAD

**Issue by angrybrad** [craftcms/nitro#35]
review https://github.com/nystudio107/nginx-craft/

**Comment by jasonmccallister** [comment]
Should we setup a production nginx configuration or is the current configuration sufficient?

**Comment by jasonmccallister** [comment]
@angrybrad I think we are good for a local development setup? Are we good to close this out?

**Comment by angrybrad** [comment]
I will want to do an audit - leaving it open and assigned to myself.

**Comment by khalwat** [comment]
In case it's useful -> https://github.com/nystudio107/nginx-craft/tree/master/sites-available

**Comment by jasonmccallister** [comment]
Closing this out since it shipped in beta 9, thank you @khalwat for the awesome config!
