### ISSUE TITLE
Changing MySQL Configuration Variables via my.cnf

### ISSUE THREAD

**Issue by seandelaney** [craftcms/nitro#350]
### Description

Following on from https://github.com/craftcms/nitro/issues/133, it would be nice if we could apply custom configurations to MySQL databases, overriding `/etc/mysql/my.cnf` with settings like `innodb_strict_mode = 0`.

**Comment by peet86** [comment]
Any update on this? In #133 some documentation was mentioned but I couldn't find any information how to solve this atm. Some craft projects require custom mysql configurations and not having an option to pass those makes your db abstraction impossible to use. I'm solving this via a separate local mysql instance atm where I have full control but I would really love to consolidate my setup and use nitro only.

**Comment by jasonmccallister** [comment]
Hi, we are closing this issue as we have decided to retire Nitro, so no additional work will occur on this project. You can read the official blog post here https://craftcms.com/blog/retiring-craft-nitro. We appreciate everyones feedback and involvement and we look forward to refocusing our efforts on Cloud! 

If you're looking for a new local development environment, we recommend DDEV and have a knowledge base article to help you with the transition: https://craftcms.com/knowledge-base/migrating-from-craft-nitro-to-ddev.
