### ISSUE TITLE
Add Support for Yarn

### ISSUE THREAD

**Issue by mizziness** [craftcms/nitro#354]
### Description

Currently, Nitro supports `npm` out of the box, but requires a few extra steps if your project uses `yarn`:

Workaround: 

```
$ nitro ssh
$ npm install yarn
$ ./node_modules/yarn/bin/yarn install
```

And you'll need to do this, or run a script to do it, each time you recreate the containers.  It would be very nice if `npm` and `yarn` were both supported options.

**Comment by jasonmccallister** [comment]
Hi, we are closing this issue as we have decided to retire Nitro, so no additional work will occur on this project. You can read the official blog post here https://craftcms.com/blog/retiring-craft-nitro. We appreciate everyones feedback and involvement and we look forward to refocusing our efforts on Cloud! 

If you're looking for a new local development environment, we recommend DDEV and have a knowledge base article to help you with the transition: https://craftcms.com/knowledge-base/migrating-from-craft-nitro-to-ddev.
