### ISSUE TITLE
[FR] Add site argument for alias command

### ISSUE THREAD

**Issue by mattstein** [craftcms/nitro#355]
### Description

Missed this one in [2.0.7](https://github.com/craftcms/nitro/blob/develop/CHANGELOG.md#207---2021-04-06)! Since `nitro alias` first prompts you for a site, it might as well behave like other commands and allow you to specify one as an argument.

Current:

```
$ nitro alias
 Select a site:
  1. plugins-dev.nitro
  2. tutorial.nitro
Enter your selection: 1
The following aliases are set for plugins-dev.nitro
   plugins.dev
Enter the alias domain for the site (use commas to enter multiple): plugins.nitro,playground.nitro
Adding aliases:
   plugins.nitro
   playground.nitro
Apply changes now [Y/n] y
```

Proposed support for maximum joy:

```
$ nitro alias plugins-dev.nitro
The following aliases are set for plugins-dev.nitro
   plugins.dev
Enter the alias domain for the site (use commas to enter multiple): plugins.nitro,playground.nitro
Adding aliases:
   plugins.nitro
   playground.nitro
Apply changes now [Y/n] y
```

**Comment by jasonmccallister** [comment]
I think this is working as expected? I just tried this on the latest build and got the following:

```
nitro alias blog.nitro
Enter the alias domain for the site (use commas to enter multiple): my-blog.nitro
Adding alias:
   my-blog.nitro
Apply changes now [Y/n]? 
Checking network…
  ✓ network ready
Checking proxy…
  ✓ proxy ready
Checking databases…
  … checking postgres-13-5432.database.nitro ✓
  … checking mysql-8.0-3306.database.nitro ✓
  … checking postgres-12-5433.database.nitro ✓
Checking services…
  … checking dynamodb service ✓
  … checking mailhog service ✓
  … checking redis service ✓
Checking sites…
  … checking blog.nitro ✓
  … checking tutorial.nitro ✓
Checking proxy…
  … updating proxy ✓
Updating hosts file (you might be prompted for your password)
[sudo] password for jasonmccallister: 
Cleaning up...
Nitro is up and running 😃
```

I don't think it has the autocomplete of site names though, is that what you mean? Also the documentation for `nitro help alias` is not showing you can add a site argument.

**Comment by mattstein** [comment]
You’re right @jasonmccallister, my mistake. Only difference is providing a site argument doesn’t list the existing aliases. Which would technically be a different issue/FR. Closing!

**Comment by jasonmccallister** [comment]
I can try to update the online documentation and look at the aliases not printing as well.

**Comment by mattstein** [comment]
I fixed the docs: https://craftcms.com/docs/nitro/2.x/commands.html#alias
