### ISSUE TITLE
Ports are not available: unable to list exposed ports

### ISSUE THREAD

**Issue by baukevanderlaan** [craftcms/nitro#359]
### Description

I consistently get this error after a long wait: `Error: unable to start the container, Error response from daemon: Ports are not available: unable to list exposed ports: Get "http://unix/forwards/list": context deadline exceeded (Client.Timeout exceeded while awaiting headers)`

I’m on MacOS 10.15, have a fresh install of Docker and Nitro, and it doesn't matter which database I select/install during initialization (Postgres or MySQL). As far as I know I don't have any other databases running outside Nitro that could conflict. I also destroyed and re-initialized nitro multiple times, but to no avail.

Full terminal output:

```
$ nitro init
Checking Nitro…
  … creating network ✓
  … pulling image ✓
  … creating volume ✓
  … creating proxy ✓
Checking network…
  ✓ network ready
Checking proxy…
  ✓ proxy ready
Checking databases…
  … checking mysql-8.0-3306.database.nitro ✗
Error: unable to start the container, Error response from daemon: Ports are not available: unable to list exposed ports: Get "http://unix/forwards/list": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

### Steps to reproduce

1. Run `nitro init`

### Additional info

- Nitro version: 2.08
- Docker version: 20.10.6

**Comment by jasonmccallister** [comment]
@baukevanderlaan do you have anything running on port 3306? You can try `nitro portcheck 3306` to test the port. It might also be running as part of MAMP or another local development tool so its best to have those turned off. However, that error code is a weird combination of HTTP and socket parameters.

I did find [this issue](https://github.com/docker/for-win/issues/9273) which suggests it worked after a reboot? I know it says Docker for Windows but one person mentioned macOS in the comment thread.

Can you try rebooting to see if that solves the issue?

**Comment by baukevanderlaan** [comment]
@jasonmccallister Thanks for helping!

`nitro portcheck` says port 3306 is still available. I then rebooted my computer, uninstalled and reinstalled Docker and still get the same error.

**Comment by mccombs** [comment]
Just wanted to +1 this. I'm running into a similar issue. Would be great if Nitro could tell me which port isn't free.

`Error: unable to start the nitro container, Error response from daemon: Ports are not available: port is already allocated.`

**Comment by smockensturm** [comment]
we are constantly restarting docker. and we are constantly getting this error. constantly having to kill processes to get nitro to play nice.

`(HTTP code 500) server error - Ports are not available: port is already allocated.`

`docker portcheck` will often say the exact opposite of what shows in docker dashboard (3000 is available!) no it's not.

yes, we also have valet installed. so what? re booting the machine definitely solves everything. for a while.

what are some tips to workaround all these nitro bugs without stopping and spinning nitro/docker/nitro up 10 times a day?

and yes I know these are not "bugs" per se, but this port business needs work.

**Comment by smockensturm** [comment]
Maybe I'm just not smart enough for Nitro development. Does this make sense?

<img width="703" alt="Screen Shot 2021-06-29 at 9 51 28 AM" src="https://user-images.githubusercontent.com/6586518/123813474-ef00e380-d8c2-11eb-84ea-9ba54072c69b.png">

**Comment by jasonmccallister** [comment]
Hi @smockensturm! I'm certain that is not the case! ;)

That error is returned directly from the Docker API and is hard to "catch" (if you will). We are working on improving this flow in the future.

Can you run the following commands and provide the output?

1. `nitro ls` 
2. `docker container ls`

Also, make sure you are not using/running something like MAMP (which would block that database port from being used).

**Comment by smockensturm** [comment]
Sure. Things are changing fast though. We have a ton of work to do and I can't be wrestling with this thing every morning for hours and hours. Not speedy.

I've snipped out about a dozen hosts. They're all the same and left the db and proxy stuff. Good luck. Thank you.

```
Hostname                          Type      Internal Ports         External Ports         Status   
food.test                         site      3000,3001,8080         (uses proxy ports)     running   
mariadb-10.5-3306.database.nitro  database  3306                   3306                   running   
nitro-proxy                       proxy     3000,3001,443,5000,80  3000,3001,443,5000,80  running 


CONTAINER ID   IMAGE                        COMMAND                  CREATED        STATUS         PORTS                                                                                                        NAMES
91071a52eb9d   craftcms/nginx:7.4-dev       "/usr/bin/supervisor…"   3 weeks ago    Up 4 minutes   3000-3001/tcp, 8080/tcp, 9000/tcp, 9003/tcp                                                                  food.test
5c73aa659711   mariadb:10.5                 "docker-entrypoint.s…"   3 weeks ago    Up 4 minutes   127.0.0.1:3306->3306/tcp                                                                                     mariadb-10.5-3306.database.nitro
2be1e274045e   craftcms/nitro-proxy:2.0.7   "/usr/bin/supervisor…"   3 weeks ago    Up 4 minutes   127.0.0.1:80->80/tcp, 127.0.0.1:443->443/tcp, 127.0.0.1:3000-3001->3000-3001/tcp, 127.0.0.1:5000->5000/tcp   nitro-proxy
```

Related: why can't we do `docker-compose` up and down? That might be faster than killing all processes and / or restarting the box to clean up the docker config. idk.

**Comment by smockensturm** [comment]
FYI: we are not running MAMP. Killed all the Valet stuff (I think). Shutdown brew mysql service. Lordy, what else?

**Comment by jasonmccallister** [comment]
> why can't we do docker-compose up and down?

Nitro is not a wrapper around Docker Compose, it uses the Docker API directly. You can run `nitro stop`, `nitro start`, or `nitro restart` to get the same impact. There is a complete list here: https://craftcms.com/docs/nitro/2.x/commands.html#start

> `docker portcheck` will often say the exact opposite of what shows in docker dashboard (3000 is available!) no it's not.

Just confirming, but I'm assuming you mean `nitro portcheck`? They way the `portcheck` command works is by checking the localhost address, not the "public" you would use on the LAN. You can specific the specific address/ip to check by passing `--hostname` to `portcheck`. You can see some examples with `nitro portcheck --help`. So if you grab your LAN IP (e.g. 192.x.x.x) and try `nitro portcheck --hostname <ip> 3306` that would give you a better check.

Can you try connecting to `localhost:3306` with the username `nitro` and password `nitro` to see if you get a valid connection?

It seems that something is running on your machine and using port 3306... Nitro does its best to check for port collisions, but we are definitely going to need to improve the checks in a future update.

**Comment by smockensturm** [comment]
I understand.

`It seems that something is running on your machine and using port 3306... Nitro does its best to check for port collisions, but we are definitely going to need to improve the checks in a future update.`

Pardon my ignorance, but how would I find that out? If you need to improve NItro, fine. But help people find their way please. Lots of folks have other dev stuff running besides yours.

**Comment by smockensturm** [comment]
What does this error mean please and what steps can I take to eliminate it?

`  … starting mariadb-10.5-3306.database.nitro Error: unable to start container mariadb-10.5-3306.database.nitro: Error response from daemon: Bad response from Docker engine`

**Comment by jasonmccallister** [comment]
> Pardon my ignorance, but how would I find that out?

The `portcheck` command is designed to help, but a port can only be used by one program at a time (e.g. mysql, postgres). We allow setting custom ports for databases, but we have no control over what you install and run on your machine, Nitro is there is make getting started and managing Docker development easier. FYI, I have used Docker (with Docker Compose) and if you forget to run `docker-compose down` when switching projects, you will still get a port collision if trying to allocate the same ports across projects.

>  But help people find their way please. Lots of folks have other dev stuff running besides yours.

I'm more than willing to help developers be productive, the entire thought behind Nitro was to make a local development environment easier. I've often jumped on Google Hangouts and Discord Screen Share sessions to help people troubleshoot Nitro or their other local development environments so I don't want you to feel as if we are not here to help because we are.

> Lots of folks have other dev stuff running besides yours.

The best part of being a developer are the choices we get to make on tools, languages, and etc. We hope Nitro works well for you but there are some basic networking and system limitations we (and other tools) cannot get around (duplicate ports, low system resources, under performing hard drives). If you have other tools that are running and causing those issues, we can only do so much to reduce that friction, if that makes sense?

**Comment by smockensturm** [comment]
This yields **nothing** on my host box btw

`lsof -nP -iTCP -sTCP:LISTEN | grep 3306`

**Comment by jasonmccallister** [comment]
Can you provide the following?

1. Which version of Docker and Nitro are you running?
2. What amount of Memory and CPU do you have allocated to Docker Desktop?

**Comment by smockensturm** [comment]
Yep. Definitely not smart enough for Nitro.

I cannot start Nitro yet to get that information, Jason. But I did just do a Nitro self-update if that helps. Docker is 3.5.1 and I have no idea how much memory and CPU I have allocated to Docker Desktop. How do I find that?

**Comment by jasonmccallister** [comment]
Assuming you are on macOS? You can find that information here: https://docs.docker.com/docker-for-mac/#resources

**Comment by smockensturm** [comment]
ok. ok. I see what you're getting at. Indeed, increasing resources (and after a little housekeeping) all seems great! Probably should have mentioned we have about 100 containers and 50 databases.

Just kidding. But it's a lot. Thank you for your guidance @jasonmccallister

**Comment by jasonmccallister** [comment]
@smockensturm ok that makes a lot more sense. I think this is whats happening:

1. The Docker API is telling us the port is in use, because a container is _supposed_ to be running but Docker might be out of system resources (because MySQL is notorious for issues with containers and resources) and is holding that port
2. The `portcheck` is checking the network device port, not the Docker API, and is technically "correct" because its free as in _not-in-use_

Can you provide the resources (memory and CPU) you had assigned to Docker Desktop as well as your host machine memory and CPU? There might be a way for us to examine the system information using the Docker API and host machine and see if that is a likely culprit.

**Comment by smockensturm** [comment]
Certainly. It's a 16 GB M1. Docker dashboard says:

Before
```
CPUs: 4
Memory: 2 GB
```

After
```
CPUs: 4
Memory: 8 GB
```

**Comment by jasonmccallister** [comment]
Putting this here for my future reference, this gets the amount of RAM allocated to Docker Desktop:

```go
package main

import (
	"context"
	"fmt"
	"log"

	"github.com/docker/docker/client"
)

func main() {
	// create the docker client
	docker, err := client.NewClientWithOpts(client.FromEnv)
	if err != nil {
		log.Fatal(err)
	}

	info, err := docker.Info(context.Background())
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println(info.MemTotal / 1000000000)
}
```
In my case, this return 6 as I have allocated 6G of RAM to Docker Desktop. We might be able to come up with a command or recommendation based on the memory allocated to the system and Docker Desktop...

**Comment by jasonmccallister** [comment]
Hi, we are closing this issue as we have decided to retire Nitro, so no additional work will occur on this project. You can read the official blog post here https://craftcms.com/blog/retiring-craft-nitro. We appreciate everyones feedback and involvement and we look forward to refocusing our efforts on Cloud! 

If you're looking for a new local development environment, we recommend DDEV and have a knowledge base article to help you with the transition: https://craftcms.com/knowledge-base/migrating-from-craft-nitro-to-ddev.
