### ISSUE TITLE
Server push?

### ISSUE THREAD

**Issue by proimage** [craftcms/nitro#363]
### Description
Does Nitro currently support server push? If not, can it? Pretty please? ;)

Once implemented, the Craft side of things is trivially simple. This code, for example, makes use of the Craft session cookie (using the [Craft Cookies plugin](https://plugins.craftcms.com/cookies)) to push the main CSS and JS files along with the HTML on a user's first visit, while presuming that their browser cache will have those files already cached locally for future visits (and thus not pushing them):
```
{% if not getCookie('CraftSessionId') %}
	{% set serverPushFiles = [
		"Link: </build/css/site.css>; as=style; rel=preload",
		"</build/js/site.js>; as=script; rel=preload"
	] %}
	{% header serverPushFiles|join(',') %}
{% endif %}
```

The performance benefits are out-of-this-world. :D

**Comment by jasonmccallister** [comment]
@proimage because the server push seems to be for specific paths (I might be wrong) this would only be useful on a per site basis. When #18 is implemented you should be able to customize the nginx config to add server push support.

**Comment by proimage** [comment]
The path-specific server push you're talking about looks like [the method covered here](https://medium.com/@mena.meseha/http-2-server-push-tutorial-d8714154ef9a), under the "Fourth, Nginx implementation" heading.

However, if you scroll down to the "Sixth, the backend implementation" heading, there's an alternate method shown that appears to be much more reliant on the file headers. That's the method my Twig code above is using.

**Comment by jasonmccallister** [comment]
Hi, we are closing this issue as we have decided to retire Nitro, so no additional work will occur on this project. You can read the official blog post here https://craftcms.com/blog/retiring-craft-nitro. We appreciate everyones feedback and involvement and we look forward to refocusing our efforts on Cloud! 

If you're looking for a new local development environment, we recommend DDEV and have a knowledge base article to help you with the transition: https://craftcms.com/knowledge-base/migrating-from-craft-nitro-to-ddev.
