### ISSUE TITLE
Twig templates cached after a few changes?

### ISSUE THREAD

**Issue by mattmesker** [craftcms/nitro#369]
### Description

After a few minutes of editing `.twig` files in the `/templates` folder, new changes to the templates stop appearing in the browser. Dev Mode is on, therefore the templates should not be cached. I'm not using any` {% cache %}` tags anywhere. Manually clearing all caches and invalidating data caches in the Utilities -> Caches menu doesn't fix anything. Shutting down and restarting Nitro restarts the clock, but after a few more minutes/changes, it inevitably stops recognizing template changes again.

Is there a setting somewhere I'm missing that's causing this?

### Steps to reproduce

1. Install Craft Nitro and create a new site as outlined in CraftQuest's [Local Development with Craft Nitro](https://craftquest.io/courses/local-development-localhosting-craft-nitro) tutorial.
2. Edit some `.twig` files in the `/templates` folder.
3. After a few minutes of editing and reloading, new changes to the twig templates stop appearing in the browser, as if the template is cached. 

### Additional info

- Nitro version: 2.0.8
- Docker version: 3.4.0.5223

**Comment by angrybrad** [comment]
@mattmesker Are you running this on MacOS? If so, how old is the hardware? Can you open Docker Desktop, go to Settings, then uncheck "Use gRPC FUSE for file sharing" if it is checked, restart Docker Desktop and see if the behavior changes?

**Comment by jasonmccallister** [comment]
@mattmesker if @angrybrad's recommendation resolves the issue, can you provide the version information from Docker Desktop?

**Comment by mattmesker** [comment]
@angrybrad Yes, I am on MacOS Big Sur 11.4 on a 2017 15" MacBook Pro. I unchecked "Use gRPC FUSE for file sharing", restarted Docker Desktop, and it seems to be working correctly. Weird!

@jasonmccallister It's Docker Desktop 3.4.0.5223. Is there something else within Docker Desktop you need the version number for?

**Comment by jasonmccallister** [comment]
@mattmesker no, was just wondering what version you are running. The 3.4 Docker release feels kind of buggy to me..

**Comment by estebancastro** [comment]
I ran into this bug, yes it working correctly after uncheck "Use gRPC FUSE for file sharing" **but** now every browser reload on the craft project load so slow, same for the craft control panel, so slow.

* MacBook Pro (Retina, 15-inch, Late 2013)
* MacOS Mojave 10.14.6 (18G6042)
* Docker 3.5.1 (66090)
* Nitro 2.0.8
* Craft CMS 3.6.17

**Comment by jasonmccallister** [comment]
Hi, we are closing this issue as we have decided to retire Nitro, so no additional work will occur on this project. You can read the official blog post here https://craftcms.com/blog/retiring-craft-nitro. We appreciate everyones feedback and involvement and we look forward to refocusing our efforts on Cloud! 

If you're looking for a new local development environment, we recommend DDEV and have a knowledge base article to help you with the transition: https://craftcms.com/knowledge-base/migrating-from-craft-nitro-to-ddev.
