### ISSUE TITLE
No Options Presented with "Select the database engine..."

### ISSUE THREAD

**Issue by kerns** [craftcms/nitro#371]
### Description
Both following `nitro create my-project` and a follow-up attempt with `nitro db add` no options are presented to choose from.

<img width="345" alt="Screen Shot 2021-06-19 at 11 40 21" src="https://user-images.githubusercontent.com/20254/122638195-22898400-d0f3-11eb-9550-441ceb791a46.png">

### Additional info

- Nitro version: 2.0.7
- Docker version: 20.10.6 / desktop: 3.3.3

**Comment by kerns** [comment]
I re-ran the operation without changing the default webroot (from web to public) and this time was prompted for a database name, but not given the option to select an engine.

FWIW both times I selected PHP 8.

**Comment by jasonmccallister** [comment]
Hmmm, was the database container running when you used create? `nitro ls` would give you the output.

**Comment by kerns** [comment]
@jasonmccallister Good question. :) If I run into the issue again I will pay more attention and let you know.

**Comment by jasonmccallister** [comment]
Hi, we are closing this issue as we have decided to retire Nitro, so no additional work will occur on this project. You can read the official blog post here https://craftcms.com/blog/retiring-craft-nitro. We appreciate everyones feedback and involvement and we look forward to refocusing our efforts on Cloud! 

If you're looking for a new local development environment, we recommend DDEV and have a knowledge base article to help you with the transition: https://craftcms.com/knowledge-base/migrating-from-craft-nitro-to-ddev.
