### ISSUE TITLE
Add support for private CA root certificates

### ISSUE THREAD

**Issue by Firefishy** [craftcms/nitro#373]
### Description
Some organisations man-in-the-middle requests to Github etc to allow their content firewalls (eg: FortiGate Next-Generation Firewalls) to inspect traffic. The HTTPS traffic is re-encrypted using a private organistation CA certificate chain.

Example `redactor` failing to install due private CA root certificate:
```
Installation failed, reverting ./composer.json and ./composer.lock to their original content.
  [Composer\Downloader\TransportException]                                                                                                                                                                        
  curl error 60 while downloading https://api.github.com/repos/craftcms/plugin-installer/zipball/23ec472acd4410b70b07d5a02b2b82db9ee3f66b: SSL certificate problem: self signed certificate in certificate chain  
```

Example `composer diagnose` error: 
```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: FAIL
[Composer\Downloader\TransportException] curl error 60 while downloading https://api.github.com/rate_limit: SSL certificate problem: self signed certificate in certificate chain
Checking disk free space: OK
Checking pubkeys: FAIL
Missing pubkey for tags verification
Missing pubkey for dev verification
Run composer self-update --update-keys to set them up
Checking composer version: You are not running the latest stable version, run `composer self-update` to update (2.0.12 => 2.1.3)
Composer version: 2.0.12
PHP version: 7.2.5 - Package overridden via config.platform, actual: 8.0.3
PHP binary path: /usr/local/bin/php
OpenSSL version: OpenSSL 1.1.1k  25 Mar 2021
cURL version: 7.76.1 libz 1.2.11 ssl OpenSSL/1.1.1k
zip: extension present, unzip present
```

**Comment by Firefishy** [comment]
For alpine linux I use the following to add the private CA chain support:
```
RUN apt-get update && apt-get install -y ca-certificates openssl curl
# PEM format with .crt file externsion required. 
COPY MyCorp_Root_CA.pem /usr/local/share/ca-certificates/MyCorp_Root_CA.crt
# Alternatively:
# RUN curl http://crl.example.com/certenroll/MyCorp%20Root%20CA.crt | openssl x509 -inform der -outform pem -out /usr/local/share/ca-certificates/MyCorp_Root_CA.crt
RUN update-ca-certificates
```

**Comment by jasonmccallister** [comment]
@Firefishy hey there! I'm not sure we are going to directly add support for private CA certificates... However, that does not mean we can't make it easier to add/configure those. Some of the upcoming changes in 3.0 (specifically the base image) will create a volume (allowing for some things to persist through the container lifecycle) for the following:

- The `nitro` user's home directory (e.g. `/home/nitro`)
- We mount the `nitro-proxy` data volume (which has the local certificates) to `/data`
- The nginx sites `/etc/nginx/sites-available` to support customizing the nginx site

I'm wondering if we can take the same approach to a private CA certificate? It's escaping my memory, but I _think_ it would be ok to place the certificate at `/home/nitro/certs` and then import it manually. It might copy the certificates into the `/usr/local/share/*` path which would not be mapped to a volume...

If we are already mounting the Caddy certificates, maybe we could automate the processing of trusting those as well and enabling the use of https from the sites container as well...

**Comment by Firefishy** [comment]
Yes, a volume for persistence would be good.

I am happy to PR docs / code as needed.

**Comment by jasonmccallister** [comment]
Hi, we are closing this issue as we have decided to retire Nitro, so no additional work will occur on this project. You can read the official blog post here https://craftcms.com/blog/retiring-craft-nitro. We appreciate everyones feedback and involvement and we look forward to refocusing our efforts on Cloud! 

If you're looking for a new local development environment, we recommend DDEV and have a knowledge base article to help you with the transition: https://craftcms.com/knowledge-base/migrating-from-craft-nitro-to-ddev.
