### ISSUE TITLE
Nitro Init failing on M1 Macbook

### ISSUE THREAD

**Issue by ryanlloydfrench** [craftcms/nitro#374]
### Description

Cannot run `nitro init` on M1 Macs without it failing when selecting MySQL.

I need our project to run on the M1 Mac as we use a MySQL db.

```
nitro init            
Setting up Nitro…
Would you like to use MySQL [Y/n]? y
Select the version of MySQL 
  1. 8.0
  2. 5.7
  3. 5.6
Enter your selection: 1
Would you like to use PostgreSQL [Y/n]? n
Would you like to use Redis [Y/n]? y
  … adding redis service ✓
Checking Nitro…
  … creating network ✓
  … pulling image ✓
  … creating volume ✓
  … creating proxy ✓
Checking network…
  ✓ network ready
Checking proxy…
  ✓ proxy ready
Checking databases…
  … checking mysql-8.0-3306.database.nitro   … downloading mysql:8.0 ✗
Error: unable to create the container, Error response from daemon: No such image: mysql:8.0
```

### Steps to reproduce

1. Run `nitro init`
2. You will be presented with the following error: `Error: unable to create the container, Error response from daemon: No such image: mysql:8.0`

### Additional info

- Nitro version: nitro version 2.0.8
- Docker version: Docker version 20.10.7, build f0df350

**Comment by jasonmccallister** [comment]
@ryanlloydfrench it should not prompt you to even select mysql (and should default to mariadb) on M1's. I'm going to put together a binary (and share the code so you are not running random executables) to run on your machine that will print the system information that we detect tomorrow.

What hardware are you running with the M1?

**Comment by ryanlloydfrench** [comment]
<img width="221" alt="Screen Shot 2021-06-30 at 7 35 10 am" src="https://user-images.githubusercontent.com/1711549/123870551-cdacff80-d975-11eb-81a1-8b4194e25054.png">

**Comment by MattWilcox** [comment]
Are you running the latest version of Nitro? I've not had this issue on my own M1 Macbook, it warned me I'd need to use Maria (can't remember the exact wording)

`nitro version` should show 2.0.8
if not, try `nitro self-update` and then `nitro update` before running `nitro init` again.

**Comment by ryanlloydfrench** [comment]
Yes I'm running the latest version of Nitro and I get the following after a fresh install of nitro.

```
Setting up Nitro…
Would you like to use MySQL [Y/n]? y
Select the version of MySQL 
  1. 8.0
  2. 5.7
  3. 5.6
Enter your selection: 1
Would you like to use PostgreSQL [Y/n]? n
Would you like to use Redis [Y/n]? y
  … adding redis service ✓
Checking Nitro…
  … creating network ✓
  … pulling image ✓
  … creating volume ✓
  … creating proxy ✓
Checking network…
  ✓ network ready
Checking proxy…
  ✓ proxy ready
Checking databases…
  … checking mysql-8.0-3306.database.nitro   … downloading mysql:8.0 ✗
Error: unable to create the container, Error response from daemon: No such image: mysql:8.0
```

**Comment by howells** [comment]
For what it's worth I'm seeing the same issue, with nitro 2.0.8. @ryanlloydfrench still a problem for you?

**Comment by ken-gladeye** [comment]
for anyone who got stuck because of this, the workaround for me is editing `~/.nitro.yaml` and replace `mysql` with `mariadb` which has native `arm64` image

```yaml
databases:
    - engine: mariadb
      version: "10.6"
      port: "3306"
    - engine: postgres
      version: "13"
      port: "5432"
...
```

after that run `nitro init` again seems to work.

**Comment by whoisgina** [comment]
I'm seeing the same issue with Nitro 2.0.10, though manually editing `~/.nitro.yaml` as described above did work for me.

**Comment by jasonmccallister** [comment]
Hi, we are closing this issue as we have decided to retire Nitro, so no additional work will occur on this project. You can read the official blog post here https://craftcms.com/blog/retiring-craft-nitro. We appreciate everyones feedback and involvement and we look forward to refocusing our efforts on Cloud! 

If you're looking for a new local development environment, we recommend DDEV and have a knowledge base article to help you with the transition: https://craftcms.com/knowledge-base/migrating-from-craft-nitro-to-ddev.
