### ISSUE TITLE
nitro create mixes up PHP version

### ISSUE THREAD

**Issue by hiasl** [craftcms/nitro#375]
### Description
I just used `nitro create` to setup a new project. The setup process worked fine, however the PHP version is somehow mixed up. It should be PHP8, composer.json is locked to 7.2 and the container is running 7.4 (on the nitro composer console).

### Steps to reproduce
- I selected PHP 8.0 as version in the setup wizard, also reflected in nitro.yaml.
```
sites:
    - hostname: vizy2.nitro
      path: ~/Projekte/vizy2
      version: "8.0"
      webroot: web
      xdebug: false
      blackfire: false
```
- composer.json has a platform setting locked to PHP 7.2, which was created automatically
```
    "platform": {
      "php": "7.2.5"
    }
```
- And the container seems to run 7.4 (at least composer is saying this), when I try to install via `nitro composer require verbb/vizy`:
```
nitro composer require verbb/vizy
  … checking /Users/xxx/Projekte/vizy2/composer.json ✓
Using version ^1.0 for verbb/vizy
./composer.json has been updated
Running composer update verbb/vizy
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - laminas/laminas-feed 2.14.1 requires php ^7.3 || ~8.0.0 -> your php version (7.2.5; overridden via config.platform, actual: 7.4.16) does not satisfy that requirement.
    - craftcms/cms 3.6.17 requires laminas/laminas-feed ~2.12.3|^2.13.1 -> satisfiable by laminas/laminas-feed[2.14.1].
    - craftcms/cms is locked to version 3.6.17 and an update of this package was not requested.


Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

- One additional note: There is only 1 more host in my nitro setup, which was setup with PHP 7.4
- And one more: I tried it a second time, with a different hostname, same thing

### Additional info

- Nitro version: 2.0.8
- Docker version: 20.10.7

**Comment by jasonmccallister** [comment]
@hiasl the `nitro create` command will not modify the projects php version, that is stored on the craft project itself here: https://github.com/craftcms/craft/blob/main/composer.json#L37.

Closing this out for now as Nitro is not going to modify the composer.json during the `create` command.
