### ISSUE TITLE
`nitro create` confusing argument parsing

### ISSUE THREAD

**Issue by timkelty** [craftcms/nitro#381]
It would seem when using git urls/shorthands, a path is _required_, otherwise it will silently fallback to using the `craftcms/craft`.

```
❯ nitro create timkelty/my-craft-starter
Downloading https://github.com/craftcms/craft/archive/HEAD.zip ...

❯ nitro create https://github.com/timkelty/my-craft-starter
Downloading https://github.com/craftcms/craft/archive/HEAD.zip ...

❯ nitro create https://github.com/timkelty/my-craft-starter my-project
Downloading https://github.com/timkelty/my-craft-starter/archive/HEAD.zip ...
```

If it truly is required, it should halt and tell you…but I suspect what we want is to just infer the path from the basename passed in (what `composer create-project` does)

**Comment by jasonmccallister** [comment]
Hi, we are closing this issue as we have decided to retire Nitro, so no additional work will occur on this project. You can read the official blog post here https://craftcms.com/blog/retiring-craft-nitro. We appreciate everyones feedback and involvement and we look forward to refocusing our efforts on Cloud! 

If you're looking for a new local development environment, we recommend DDEV and have a knowledge base article to help you with the transition: https://craftcms.com/knowledge-base/migrating-from-craft-nitro-to-ddev.
