### ISSUE TITLE
Non-Craft sites and Nitro

### ISSUE THREAD

**Issue by jamiematrix** [craftcms/nitro#383]
### Description
I had the crazy idea of using a non-Craft site with Nitro as we have a couple that are written in PHP with no database to use, just written in PHP. The sites themselves can be added as Nitro sites and the homepages load fine, but that's as far as they go. Any URL visited just loads the homepage of the site (the URL stays in the navigation bar, just the page content is still the homepage).
This happens in Windows (WSL) and Mac OSs

### Steps to reproduce

1. Create a Nitro site built in PHP
2. Navigate to a page that isn't the homepage

### Additional info

- Nitro version: 2.0.8
- Docker version: 20.10.7

**Comment by jasonmccallister** [comment]
@jamiematrix I am assuming this is because our default nginx config routes all pages to index.php? What types of PHP projects are you adding to Nitro? 

Also, we are actively working on the ability to override/customize the nginx config (outlined here https://github.com/craftcms/nitro/issues/18)

**Comment by jamiematrix** [comment]
We only have a couple of (basic) PHP sites, they're nothing over the top. The site I'm currently working on has a handful of pages and a contact form, that's all.

I've managed to get a workaround by having `http://siteurl.nitro/index.php?path=/path/to/file.` - this has worked OK so far.

**Comment by jasonmccallister** [comment]
Hi, we are closing this issue as we have decided to retire Nitro, so no additional work will occur on this project. You can read the official blog post here https://craftcms.com/blog/retiring-craft-nitro. We appreciate everyones feedback and involvement and we look forward to refocusing our efforts on Cloud! 

If you're looking for a new local development environment, we recommend DDEV and have a knowledge base article to help you with the transition: https://craftcms.com/knowledge-base/migrating-from-craft-nitro-to-ddev.
