### ISSUE TITLE
Switch from `sh` to `bash` in Nitro

### ISSUE THREAD

**Issue by lindseydiloreto** [craftcms/nitro#384]
It would be amazing if Nitro supported `zsh` within its containers! The standard shell is pretty weak by comparison.

`zsh` is now even the standard in Terminal. So when you `nitro ssh` into a container, the `bash` shell is a clear step down. Every time I instinctually type `ll`, the boring old shell throws an error at me.

**Comment by jasonmccallister** [comment]
@lindseydiloreto not sure if we are going to go with `zsh` but we are changing the default shell to `bash` in the next version.

**Comment by lindseydiloreto** [comment]
Sounds good to me!

**Comment by jasonmccallister** [comment]
Hi, we are closing this issue as we have decided to retire Nitro, so no additional work will occur on this project. You can read the official blog post here https://craftcms.com/blog/retiring-craft-nitro. We appreciate everyones feedback and involvement and we look forward to refocusing our efforts on Cloud! 

If you're looking for a new local development environment, we recommend DDEV and have a knowledge base article to help you with the transition: https://craftcms.com/knowledge-base/migrating-from-craft-nitro-to-ddev.
