### ISSUE TITLE
`version` looks like it has a bug if nitro isn't started (error handling + docs to fix)

### ISSUE THREAD

**Issue by olets** [craftcms/nitro#386]
### Description

`nitro version` errors if Nitro isn't running. 

```shell
% nitro stop
% nitro version
Error: unable to get version from the gRPC API
```

### Steps to reproduce

1. `nitro stop`
2. `nitro version`
3. See `Error: unable to get version from the gRPC API`
4. `nitro --version`
5. See version output
6. `nitro help`
7. See that the explanations of `version` and `--version` possibly hint at but don't clearly say they're different
8. `nitro --help`
9. See that it's the same as `nitro help`

### Suggestion

(Not a Go programmer so won't attempt a PR)

Update `help`:

```shell
% nitro help
# snip
  version     Displays version info for Nitro CLI ('nitro'), Nitro gRPC, Docker API, Docker CLI
# snip
  -h, --help      help for Nitro CLI ('nitro')
  -v, --version   version for Nitro CLI ('nitro')
```

Update `version`:

```shell
# if Docker running but Nitro not running
Nitro CLI:       <v>
Nitro gRPC:      Nitro is stopped
Docker API:      <v>
Docker CLI:      <v>
```

(Don't know if Docker needs to be running to look up the API version. If so, if Docker isn't running then `Docker API:      stopped`.)

### Additional info

- Nitro version: 2.0.8
- Docker version: 1.41

**Comment by jasonmccallister** [comment]
@olets you can get the version of Nitro (the CLI by itself) using `nitro --version`. The `version` command requires Docker to be running to talk to the Docker API and the Nitro API (that runs in the `nitro-proxy` container). We should make this output a little less error prone though!

**Comment by jasonmccallister** [comment]
Hi, we are closing this issue as we have decided to retire Nitro, so no additional work will occur on this project. You can read the official blog post here https://craftcms.com/blog/retiring-craft-nitro. We appreciate everyones feedback and involvement and we look forward to refocusing our efforts on Cloud! 

If you're looking for a new local development environment, we recommend DDEV and have a knowledge base article to help you with the transition: https://craftcms.com/knowledge-base/migrating-from-craft-nitro-to-ddev.
