### ISSUE TITLE
FR: Add installation flags to `nitro init`

### ISSUE THREAD

**Issue by mikesnoeren** [craftcms/nitro#387]
### Description
I'm trying to include Nitro in a linux post installation script but found out that Nitro is the only software that requires input to install. 

It would be great if we could use the `nitro init` command with installation flags like below:
`nitro init --mysql-8 --redis`

**Comment by jasonmccallister** [comment]
Hi, we are closing this issue as we have decided to retire Nitro, so no additional work will occur on this project. You can read the official blog post here https://craftcms.com/blog/retiring-craft-nitro. We appreciate everyones feedback and involvement and we look forward to refocusing our efforts on Cloud! 

If you're looking for a new local development environment, we recommend DDEV and have a knowledge base article to help you with the transition: https://craftcms.com/knowledge-base/migrating-from-craft-nitro-to-ddev.
