### ISSUE TITLE
Craft running slow on Nitro

### ISSUE THREAD

**Issue by ambidustrious** [craftcms/nitro#388]
### Description
I'm new to Nitro/Docker... but have built several dozen Craft sites.  This same site running on our remote production server is quite speedy, but not the case in Nitro.  

### Steps to reproduce

1. Any craft template... even a blank one takes 2-4 seconds to load
2. Static pages that run outside of craft are instantaneous

### Additional info

**Desktop / Nitro**
Docker Desktop Version 3.1.8
Docker version 20.10.7, build f0df350
nitro version 2.0.8
mySql version 8.0.26
PHP 8.0.3

MacBook Pro (16-inch, 2019)
2.3 GHz 8-Core Intel Core i9
32 GB 2667 MHz DDR4
SSD 

**Production**
PHP 7.3.29
MySql version 5.7.35

It doesn't seem to matter if I'm in Dev or Production mode - hoping you may have some immediate insight or thoughts on where I should start looking.

Thanks

**Comment by angrybrad** [comment]
Can you update to the latest Docker Desktop (3.5.2) and double-check that you have adequate resources assigned to it? https://craftcms.com/docs/nitro/2.x/#recommended-docker-resources

**Comment by ambidustrious** [comment]
Hello - I'm now running 3.5.2 and have plenty of resources - I'm only running one site. 

![image](https://user-images.githubusercontent.com/22107826/128553143-adf0bade-00ad-4e5d-80e0-e0a6c1485c81.png)

I turned on the debugger and I'm getting the following error on the front end...

Class "yii\mail\BaseMailer" not found

**Comment by angrybrad** [comment]
> Class "yii\mail\BaseMailer" not found

Can't imagine that's performance-related, but sounds like you're missing some required Craft files. Try deleting your vendor folder and composer.lock file and running `composer update` to pull in a fresh set of dependencies and see if it resolves that.

**Comment by ambidustrious** [comment]
I did that and it didn't seem to have any impact. So I did a nitro destroy and did a completely fresh install of nitro and new pull of my site - same results - No PHP errors in the logs

**Comment by ambidustrious** [comment]
I just installed a new project instead of clone an existing one from git... and the issue seems to be resolved. So I don't believe this is a nitro related issue.

**Comment by angrybrad** [comment]
Really weird, but glad you're all sorted!
