### ISSUE TITLE
Craft 2 Support ?

### ISSUE THREAD

**Issue by jamiematrix** [craftcms/nitro#393]
### Description
Setting up a Craft 2 site and I get an error that `The Mcrypt extension is required.`. The live host is on PHP 7.1, so I've got the Nitro host set to the same. Looking at the Nitro commands to add extensions, mcrypt isn't one that is available. Looking around the internet, it seems mcrypt was still part of PHP in 7.1?

### Steps to reproduce

1. Create Craft 2 site
2. Go to admin

### Additional info

- Nitro version: 2.0.8
- Docker version: 20.10.7

**Comment by jamiematrix** [comment]
For whatever reason, trashing the Nitro host, then recreating has fixed the error

**Comment by angrybrad** [comment]
Odd... PHP 7.2 removed the abandoned mcrypt, but Craft 2.7.0 added a software shim for it: https://github.com/craftcms/cms/blob/develop-v2/CHANGELOG-v2.md#270---2018-07-31

Regardless, glad you're all sorted, now.

**Comment by jamiematrix** [comment]
Error has returned, but only when trying to access /admin. I've changed the site to PHP 7 from 7.1 and still get the error. It's on Craft 2.6, so I'm guessing I'll have to update the local site to 2.7 to get the shim?

**Comment by angrybrad** [comment]
Right, you'll need to be on 2.7.0+ to get the mcrypt chim.

**Comment by jamiematrix** [comment]
Managed to download 2.9 and seems to have loaded admin now. Thanks again :)
