### ISSUE TITLE
CORS - No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by anovix** [craftcms/nitro#406]
### Description
'Access-Control-Allow-Origin' header is not present in my responses from Craft CMS.
I use Nuxt.js and Craft CMS in headless mode.

I first checked this issue: https://github.com/craftcms/nitro/issues/290#issuecomment-797501529
So I used `nitro ssh` and checked `/etc/nginx/conf.d/default.conf`. It looks like this:
```nginx
server {
    listen      8080 default_server;
    listen      [::]:8080 default_server;
    server_name _;
    set         $base /app;
    root        $base/web;

    # security
    include     craftcms/security.conf;

    # index.php
    index       index.php;

    # index.php fallback
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # additional config
    include craftcms/general.conf;

    # handle .php
    location ~ \.php$ {
        include craftcms/php_fastcgi.conf;
    }

    # Allow fpm ping and status from localhost
    location ~ ^/(fpm-status|fpm-ping)$ {
        access_log off;
        allow 127.0.0.1;
        deny all;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_pass 127.0.0.1:9000;
    }
}
```
I don't see any header with 'Access-Control-Allow-Origin'. It looks like it's the production config: https://github.com/craftcms/docker/blob/develop/nginx/default.conf and not the dev one: https://github.com/craftcms/docker/blob/develop/nginx/dev.default.conf
Also when I ssh-ed I didn't see the dev config in `/etc/nginx/conf.d/` directory.

Here is my nitro config:
```yaml
databases:
    - engine: mysql
      version: "8.0"
      port: "33060"
services:
    dynamodb: false
    mailhog: false
    minio: false
    redis: false
sites:
    - hostname: project-name-craft-nitro.nitro
      path: ~/Programming/nitro-craft-websites/project-name-craft-nitro
      version: "8.0"
      webroot: web
      xdebug: false
      blackfire: false
```
I also tried to use php version "7.4" but it was the same scenario.

Here is an example of the request from DevTools in Chrome:
```
General
Request URL: http://project-name-craft-nitro.nitro/actions/commerce/cart/get-cart
Referrer Policy: strict-origin-when-cross-origin

Response Headers
Cache-Control: no-store, no-cache, must-revalidate
Content-Encoding: gzip
Content-Length: 936
Content-Type: application/json; charset=UTF-8
Date: Mon, 06 Sep 2021 08:01:43 GMT
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Permissions-Policy: interest-cohort=()
Pragma: no-cache
Referrer-Policy: no-referrer-when-downgrade
Server: Caddy
Server: nginx
Set-Cookie: CraftSessionId=723458165fa3ffec4b028c22c668f172; path=/; HttpOnly
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Powered-By: Craft Commerce,Craft CMS
X-Robots-Tag: none
X-Xss-Protection: 1; mode=block

Request Headers
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate
Accept-Language: en,en-US;q=0.9,sk;q=0.8
Cache-Control: no-cache
Connection: keep-alive
DNT: 1
Host: project-name-craft-nitro.nitro
Origin: http://localhost:37821
Pragma: no-cache
Referer: http://localhost:37821/
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36
```

### Steps to reproduce

1. nitro init
2. nitro start
3.  Send GET request from Nuxt.js app to Craft CMS to `http://project-name-nitro.nitro/actions/commerce/cart/get-cart` (using axios).
4. Error in Chrome: `Access to XMLHttpRequest at 'http://project-name-craft-nitro.nitro/actions/commerce/cart/get-cart' from origin 'http://localhost:37821' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

Postman request worked (Don't know it CORS policy applies to postman, I suppose it doesn't).
Also GraphQL requests work (using vue-apollo).

### Additional info

- Nitro version: 2.0.8
- Docker version: 20.10.8, build 3967b7d
- Using `Windows 10 with WSL2` and Ubuntu is `Ubuntu 20.04.2 LTS`

**Comment by jamiematrix** [comment]
Any update on this? I'm getting the same error with the same version of Nitro CLI

I've checked the default.conf and the "access-control-allow-origin *" is there but it's not in the headers in the request

**Comment by StijnCoolen** [comment]
@jamiematrix I managed to create a temporary workaround by adding `header("Access-Control-Allow-Origin: *");` to `web/index.php`. Still looking for a real fix.

**Comment by jasonmccallister** [comment]
Hi, we are closing this issue as we have decided to retire Nitro, so no additional work will occur on this project. You can read the official blog post here https://craftcms.com/blog/retiring-craft-nitro. We appreciate everyones feedback and involvement and we look forward to refocusing our efforts on Cloud! 

If you're looking for a new local development environment, we recommend DDEV and have a knowledge base article to help you with the transition: https://craftcms.com/knowledge-base/migrating-from-craft-nitro-to-ddev.
