### ISSUE TITLE
Add "db shell" command

### ISSUE THREAD

**Issue by musicaljoeker** [craftcms/nitro#410]
### Description

Oftentimes while I'm developing with Craft, I want to open up a database shell for manual querying. This can be helpful for both debugging and developing new features in Craft. With Nitro, I don't see a very easy way to do this right now. It is possible to get a MySQL shell by ssh'ing into the DB container and running `mysql -h localhost -u nitro`. To be a little easier, might it be possible to add in a `nitro db shell` command to open the current site's database?

If this is desirable, I'd be happy to help develop this feature in Nitro and submit a pull request.

**Comment by jasonmccallister** [comment]
I think this is a great idea. It could work similar to `nitro db ssh` or `nitro craft`. If you have the time a PR would be 💯!

**Comment by jasonmccallister** [comment]
Hi, we are closing this issue as we have decided to retire Nitro, so no additional work will occur on this project. You can read the official blog post here https://craftcms.com/blog/retiring-craft-nitro. We appreciate everyones feedback and involvement and we look forward to refocusing our efforts on Cloud! 

If you're looking for a new local development environment, we recommend DDEV and have a knowledge base article to help you with the transition: https://craftcms.com/knowledge-base/migrating-from-craft-nitro-to-ddev.
