### ISSUE TITLE
Homebrew: Calling bottle :unneeded is deprecated

### ISSUE THREAD

**Issue by Jan10** [craftcms/nitro#416]
### Description
I get the following warning in my terminal:
```
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the craftcms/nitro tap (not Homebrew/brew or Homebrew/core):
  /opt/homebrew/Library/Taps/craftcms/homebrew-nitro/Formula/nitro.rb:10
```

### Steps to reproduce

1. install craftcms/nitro/nitro via brew

**Comment by jasonmccallister** [comment]
@Jan10 this was caused by the build tool and we just released [2.0.9](https://github.com/craftcms/nitro/releases/tag/2.0.9) which appears to have resolved this.
