### ISSUE TITLE
Add KDE distro's to certs identify method

### ISSUE THREAD

**Issue by lenvanessen** [craftcms/nitro#417]
### Description

Error: unable to find the distribution from the description: Description:       KDE neon User - Plasma 25th Anniversary Edition

PR incoming

**Comment by jasonmccallister** [comment]
I'll work on getting this adding to the list for 3.0 if you cannot make a PR. Thank you!

**Comment by jasonmccallister** [comment]
Hi, we are closing this issue as we have decided to retire Nitro, so no additional work will occur on this project. You can read the official blog post here https://craftcms.com/blog/retiring-craft-nitro. We appreciate everyones feedback and involvement and we look forward to refocusing our efforts on Cloud! 

If you're looking for a new local development environment, we recommend DDEV and have a knowledge base article to help you with the transition: https://craftcms.com/knowledge-base/migrating-from-craft-nitro-to-ddev.
