### ISSUE TITLE
Backup command

### ISSUE THREAD

**Issue by angrybrad** [craftcms/nitro#43]
Would be awesome if nitro had a way to backup and database from the host and restore without having to shell in.

**Comment by jasonmccallister** [comment]
I'm going to add a `backup` command that will work similar to the `logs`, `remove`, and `import` command. Meaning it will prompt you for a database to backup and export it into the current working directory.

**Comment by jasonmccallister** [comment]
I just pushed this change to `develop`. Will review early tomorrow morning and tackle the upgrade/change log as well.

**Comment by jasonmccallister** [comment]
Closing this, releasing with beta 3.
