### ISSUE TITLE
ini setting opcache_validate_timestamps doesn't seem to work

### ISSUE THREAD

**Issue by darrylhein** [craftcms/nitro#435]
### Description

I've set `opcache_validate_timestamps` to `true` through `nitro iniset` and confirmed it's in the config. I've applied and restarted a number of times but it doesn't seem to take effect. The ENV `PHP_OPCACHE_VALIDATE_TIMESTAMPS` is also 0 in the `phpinfo()`

Adding a `.user.ini` with the follow does enable it:

```
[opcache]
opcache.validate_timestamps=1
```

### Steps to reproduce

1. Set `opcache_validate_timestamps` to `true` using `nitro iniset`. Accept to apply immediately.
2. Create `phpinfo()` & check local value for `opcache.validate_timestamps`.

### Additional info

- Nitro version: 2.0.8
- Docker version: 20.10.10, build b485636

**Comment by wiljonbolten** [comment]
@darrylhein I provided a PR where this setting is working correctly, probably will be released in the future. For the time being you could checkout my branch, based on current version 2.0.9, which has the fix in it.

Note: it will require you to build Nitro yourself.

**Comment by jasonmccallister** [comment]
Just tagged [2.0.10](https://github.com/craftcms/nitro/blob/develop/CHANGELOG.md#2010---2022-05-19) with this change!

Let me know if this is still an issue for you!
