### ISSUE TITLE
Custom DB backup / export path

### ISSUE THREAD

**Issue by wallythewebdev** [craftcms/nitro#455]
Very lazy of me to request this, but: 

On running `nitro db backup` it would be great to be able to pass an optional path of where you want the backup to be sent to i.e. 
`nitro db backup ~/dev/Craft/tutorial` OR to have the option for the backup to be added to the current directory of the associated craft website i.e. the same location of the craft sites .env file. 

Simple reason is to stop having to copy and paste the DB file from the default .nitro/db directory to the craft sites website prior to adding the site to a git repository. 

Thanks - 
W

**Comment by jasonmccallister** [comment]
Hi, we are closing this issue as we have decided to retire Nitro, so no additional work will occur on this project. You can read the official blog post here https://craftcms.com/blog/retiring-craft-nitro. We appreciate everyones feedback and involvement and we look forward to refocusing our efforts on Cloud! 

If you're looking for a new local development environment, we recommend DDEV and have a knowledge base article to help you with the transition: https://craftcms.com/knowledge-base/migrating-from-craft-nitro-to-ddev.
