### ISSUE TITLE
Incorrect app context with similar names

### ISSUE THREAD

**Issue by timkelty** [craftcms/nitro#456]
Given these apps:

```
    - hostname: spoke.4.test
      path: ~/Repos/spoke-and-chain-craft4
      webroot: web
      php_version: "8.0"
    - hostname: spoke.test
      path: ~/Repos/spoke-and-chain
      webroot: web
      php_version: "8.0"
```

I'm seeing it always match on the shorter one:

```
~/Repos/spoke-and-chain-craft4 master* 1m39s
❯ nitro craft
connecting to spoke.test
```

- `nitro version 3.0.0`

Related: https://github.com/craftcms/nitro/pull/385

**Comment by jasonmccallister** [comment]
Hi, we are closing this issue as we have decided to retire Nitro, so no additional work will occur on this project. You can read the official blog post here https://craftcms.com/blog/retiring-craft-nitro. We appreciate everyones feedback and involvement and we look forward to refocusing our efforts on Cloud! 

If you're looking for a new local development environment, we recommend DDEV and have a knowledge base article to help you with the transition: https://craftcms.com/knowledge-base/migrating-from-craft-nitro-to-ddev.
