### ISSUE TITLE
Command from Nitro to trust certificate - syntax incorrect

### ISSUE THREAD

**Issue by darylknight** [craftcms/nitro#460]
### Description
Following the instructions here: https://craftcms.com/docs/nitro/2.x/windows.html#manually-trust-certificates-and-edit-the-hosts-file I ran `nitro trust`, and was told to enter this:

![image](https://user-images.githubusercontent.com/1250017/161750079-550d92b0-79a8-405b-b57c-0cf079c73318.png)

I opened an Administrator Command Prompty and entered `certutil -addstore -f "Root" \\wsl$\Ubuntu-20.04\home\darylknight\.nitro\nitro.crt82 <nil>` and got this error:

![image](https://user-images.githubusercontent.com/1250017/161750174-e511cfe6-98e9-493e-878e-c1d0bdd22cae.png)

### Additional info

- Nitro version: 2.0.9
- Docker version: Docker Desktop 4.6.1 (76265)
- Windows 11

**Comment by jasonmccallister** [comment]
@darylknight I see what the issue is an I will work on getting that into the next release... It appears we are not trimming the string correctly on the URL. If you remove the trailing 82 it should work. Can you verify it works when removing that and I will look at fixing it ASAP.

**Comment by darylknight** [comment]
Thanks Jason - it looks like this command worked:

`certutil -addstore -f "Root" \\wsl$\Ubuntu-20.04\home\darylknight\.nitro\nitro.crt` so also removing the <nil> mentioned in the instructions

The confirmation I get is:

```
C:\Windows\system32>certutil -addstore -f "Root" \\wsl$\Ubuntu-20.04\home\darylknight\.nitro\nitro.crt
Root "Trusted Root Certification Authorities"
Signature matches Public Key
Certificate "Caddy Local Authority - 2022 ECC Root" added to store.
CertUtil: -addstore command completed successfully.
```

I assume it works now, but can't test it - running any of my sites in the browser at sitename.nitro is still showing me this:

![image](https://user-images.githubusercontent.com/1250017/161908417-5a940857-7b5e-477d-9959-432a2e9447aa.png)

I have no idea why that's happening, and was hoping it was the certificate step.

**Comment by darylknight** [comment]
Problem solved. I just ran `nitro apply` and saw this:

![image](https://user-images.githubusercontent.com/1250017/161913944-10a6f435-29b8-4aa7-b73c-94eea1466bd1.png)

This step is not mentioned anywhere in the docs for running Nitro on Windows

**Comment by jasonmccallister** [comment]
@darylknight created a new issue to track that bug.

@mattstein maybe worth looking at the docs for Windows?

**Comment by mattstein** [comment]
It is [mentioned](https://craftcms.com/docs/nitro/2.x/windows.html#manually-trust-certificates-and-edit-the-hosts-file) with an explanation of why it’s required:

> The first time you add a Craft site, you’ll need to manually run a command on the Windows host machine to import a certificate file so SSL will work. You can follow the terminal output for exact instructions.

Will add an output example so it’s harder to miss and easier to search.

**Comment by darylknight** [comment]
Ok - so it looks like there are two points where things have to be manually added on Windows:

```The first time you add a Craft site, you’ll need to manually run a command on the Windows host machine to import a certificate file so SSL will work. You can follow the terminal output for exact instructions.```
This works - Nitro tells you that you have to run the `certutil` command, which is when I created this issue

```Nitro cannot edit the Windows hosts file at C:\Windows\system32\drivers\etc\hosts and will provide you with copy+paste instructions when it needs the file updated.```
The first time you add a site, Nitro doesn't tell you that you have to edit the hosts file. I only saw these copy/paste instructions when I ran `nitro apply` for a different reason

**Comment by mattstein** [comment]
I _think_ that’s expected because of when Nitro gets to certain internal updates—but @jasonmccallister can correct me if I’m wrong.

I’ll add a tip to the docs since it’s kind of confusing / unexpected.

**Comment by jasonmccallister** [comment]
@darylknight in your terminal, can you provide the output of the following commands?

```bash
echo $WSL_DISTRO_NAME
echo $USER
```

**Comment by darylknight** [comment]
I'm sorry, I don't have this all set up anymore

**Comment by jasonmccallister** [comment]
Ok, no worries!
