### ISSUE TITLE
Nitro 2 - Keys command

### ISSUE THREAD

**Issue by antoniojhun** [craftcms/nitro#463]
### Description
I was looking for the `keys` command for Nitro 2. I could not find thus function in Nitro 2.
After reading the thread #141, keys command seems to be a feature in Nitro 3, is it correct?

However, in Nitro 2, the command doesn't seem to exist. What command should I use to replicate the same function from Nitro 1 the`keys` command?

**Comment by jasonmccallister** [comment]
The `keys` command copied you local SSH keys into the (v1) virtual machine. It does not exist in v2 as the system moved to a container based environment and the container home directory is not persistent, so you would have to run that command on a regular basis.

Can you provide some context on what exactly you are trying to achieve and there might be a better method here.

**Comment by antoniojhun** [comment]
Hey @jasonmccallister, thank you for looking into this. 
Wanted to mention Nitro 2 made such an  ease to start a project.

I'm trying to copy my local id_rsa to authenticate git account within the container. I'm trying to install private plugin via composer.json pointing to a private git repo which requires ssh auth to pull the file.

Thank you,

Antonio

**Comment by jasonmccallister** [comment]
Hi, we are closing this issue as we have decided to retire Nitro, so no additional work will occur on this project. You can read the official blog post here https://craftcms.com/blog/retiring-craft-nitro. We appreciate everyones feedback and involvement and we look forward to refocusing our efforts on Cloud! 

If you're looking for a new local development environment, we recommend DDEV and have a knowledge base article to help you with the transition: https://craftcms.com/knowledge-base/migrating-from-craft-nitro-to-ddev.
