### ISSUE TITLE
`.env` is not updated during `nitro create`

### ISSUE THREAD

**Issue by tommysvr** [craftcms/nitro#464]
### Description
The 'Update .env' step of `nitro create` appears to work, but nothing is actually written to `.env` due to these changes: https://github.com/craftcms/craft/commit/34e84a1edb6af4fd1ec59bce45060f5e1f6e807c

### Steps to reproduce

1. Run `nitro create`
2. Say yes to 'Should we update the env file? [Y/n]'
3. '.env updated!' will show but if you check `.env` the default settings remain

### Additional info
https://github.com/craftcms/nitro/blob/develop/command/create/create.go#L143

- Nitro version: 2.0.9

**Comment by jasonmccallister** [comment]
@tommysvr sorry will close this when we cut a release!

**Comment by jasonmccallister** [comment]
Just tagged [2.0.10](https://github.com/craftcms/nitro/blob/develop/CHANGELOG.md#2010---2022-05-19) with this change!
