### ISSUE TITLE
Language Settings are limited to "en".

### ISSUE THREAD

**Issue by Mankeldor** [craftcms/nitro#468]
### Description
I changed recently to nitro-workflow for my local development. All of my projects using at least the german locale. It seems that the nitro container only supports english locales (see screenshots).

I am still able to set the control panel language to different languages (see last screenshot). Maybe there is something wrong with the intl extension?

### Steps to reproduce

1. Create new project with `nitro create project`
2. Try to change language.

### Additional info

- Nitro version: 2.0.2.10 (installed via homebrew)
- Docker version: 20.10.16, build aa7e414 (using Docker Desktop)
- Local Development runs on Mac with Apple Silicon Chip

<img width="865" alt="Bildschirmfoto 2022-06-10 um 21 49 53" src="https://user-images.githubusercontent.com/12020025/173142299-55d696b9-ea7f-4ce7-b081-8ee00e716f85.png">
<img width="774" alt="Bildschirmfoto 2022-06-10 um 21 50 59" src="https://user-images.githubusercontent.com/12020025/173142311-c5ac057f-35ab-4751-98e7-e3fdf9faf3ac.png">
<img width="785" alt="Bildschirmfoto 2022-06-10 um 21 51 12" src="https://user-images.githubusercontent.com/12020025/173142313-8fe10143-f243-4215-9d1d-70b7bdee225f.png">
<img width="738" alt="Bildschirmfoto 2022-06-10 um 22 05 18" src="https://user-images.githubusercontent.com/12020025/173142865-e7cd338a-cf2a-46b0-b020-36521c42d883.png">

**Comment by therealpecus** [comment]
I hit the same issue. Updating the containers via `nitro update` fixed it.
Look for `craftcms/nginx`. The working docker image has id `b4ee53659218`. I was previosly running on `837b12afa529`: sites created _before_ this specific image retained their language, but modifying them via the Control Panel would show only english as available language options.

You can use docker desktop to verify your image id or `docker images` from the CLI. The tagged image is the current one.
```
REPOSITORY             TAG       IMAGE ID       CREATED        SIZE
craftcms/nginx         7.4-dev   b4ee53659218   5 days ago     956MB
craftcms/nitro-proxy   2.0.10    1f50ae8c6cba   3 weeks ago    144MB
craftcms/nginx         <none>    837b12afa529   3 weeks ago    961MB
craftcms/cli           7.4-dev   92631393bfb9   3 weeks ago    927MB
craftcms/nginx         <none>    041da3610f8b   8 weeks ago    955MB
craftcms/cli           <none>    74690dd8c36d   8 weeks ago    921MB
craftcms/nitro-proxy   2.0.9     4663c0f6bffa   3 months ago   144MB
mysql                  5.7       6c20ffa54f86   9 months ago   448MB
```
Edit: Apple Intel OSX 10.15.7; Docker version 20.10.14, build a224086; nitro version 2.0.10; Craft 3.7.44, PHP 7.4 (nitro)

**Comment by Mankeldor** [comment]
Thanks for your suggestion. Unfortunately `nitro update` didn't fix it.

What i tried so far:

- `nitro update`
- different containers (8.1, 8.0, 7.4 with craftcms 3.7.44)

My next step would be:

- Create a new project on an AMD64 based machine. (That will be tomorrow -> 13. June 10am UTC+2)

I will keep you up-to-date :-)

**Comment by Mankeldor** [comment]
A fresh install on an AMD64 machine leads to the same results. Only english is available.

Docker images are up to date (fresh installs).

If someone have an idea, let us know :-) In my case different languages are a "must have condition". And a Workaround to manually set the languages in database isn't suitable.

@therealpecus : Do you get more language options with a fresh install via `nitro create <project>` ? With that command you will get Craft 4 (so at least PHP 8.0)

kind regards

**Comment by therealpecus** [comment]
> @therealpecus : Do you get more language options with a fresh install via `nitro create <project>` ? With that command you will get Craft 4 (so at least PHP 8.0)

I just tried a fresh install of Craft 4 with PHP 8.1: only english is showing. I also tried to update containers with `nitro update` like I did a few days ago when this fixed containers on PHP 7.4 . Not only it did not fix the container on PHP 8.1, it also broke containers on PHP 7.4.

These are the hashes of the working images (at least for PHP 7.4, Mac Os X, Intel):
```
REPOSITORY             TAG       IMAGE ID       CREATED         SIZE
craftcms/cli           7.4-dev   bb31fbe2fb80   17 hours ago    921MB
craftcms/nginx         7.4-dev   b4ee53659218   9 days ago      956MB
```

Is there any way to rebuild containers based on these images? cc: @brandonkelly

**Comment by therealpecus** [comment]
this is being tracked here https://github.com/craftcms/docker/issues/60 
docker images are a dependency to nitro

**Comment by Mankeldor** [comment]
TY @therealpecus 

The missing part was an install of icu-data-full -> `apk add icu-data-full`. (As mentioned in [craftcms/docker#60](https://github.com/craftcms/docker/issues/60))

This command should be added in all craftcms docker containers

**Comment by fdelaneau** [comment]
This issue seems now fully resolved.

**Comment by jasonmccallister** [comment]
Hi, we are closing this issue as we have decided to retire Nitro, so no additional work will occur on this project. You can read the official blog post here https://craftcms.com/blog/retiring-craft-nitro. We appreciate everyones feedback and involvement and we look forward to refocusing our efforts on Cloud! 

If you're looking for a new local development environment, we recommend DDEV and have a knowledge base article to help you with the transition: https://craftcms.com/knowledge-base/migrating-from-craft-nitro-to-ddev.
