### ISSUE TITLE
Nitro add - database steps are not updating the .ENV file (like it has been)

### ISSUE THREAD

**Issue by kevinmu17** [craftcms/nitro#470]
### Description
Since Craft 4 there are some new .ENV variables to connect to the database
```
CRAFT_DB_DRIVER
CRAFT_DB_SERVER
CRAFT_DB_PORT
CRAFT_DB_DATABASE
CRAFT_DB_USER
CRAFT_DB_PASSWORD
CRAFT_DB_SCHEMA
CRAFT_DB_TABLE_PREFIX
```

Normally when using `nitro add` you will get asked to update the env file:
```
Should we update the env file? [y/N] Y
.env updated!
```
But this isn't updating anything anymore. Every variable is still empty. When changing it back to the old values it still works, but that requires manual work :)

**Comment by jasonmccallister** [comment]
Hi, we are closing this issue as we have decided to retire Nitro, so no additional work will occur on this project. You can read the official blog post here https://craftcms.com/blog/retiring-craft-nitro. We appreciate everyones feedback and involvement and we look forward to refocusing our efforts on Cloud! 

If you're looking for a new local development environment, we recommend DDEV and have a knowledge base article to help you with the transition: https://craftcms.com/knowledge-base/migrating-from-craft-nitro-to-ddev.
