### ISSUE TITLE
Nitro project getting gradually slower and slower as the DB gets bigger to a point where it times out.

### ISSUE THREAD

**Issue by JayBox325** [craftcms/nitro#471]
### Description
I have a local and production build of a project and I have been regularly pulling the production DB down onto my local version. However, with each time it makes my nitro platform slower and slower. It's to the point now where I am getting 504 errors when I log into the nitro CMS.

Please see the logs below to note that there is nothing out of the ordinary going on.

[web.log](https://github.com/craftcms/nitro/files/8958921/web.log)

The database that finally caused time outs was only 16.5mb, so I'd not have expected this to be big enough to cause time outs, however, I have increased the `max_execution_time` and increased the resources that docker can utilise and I'm getting the same timeout issues.

### Additional info

I understand this may be a setup/dev error issue, but it's something I've struggled to find advice on resolving, so even if it is an issue that is easily resolved, this could be highlight a requirement in the docs.

- Nitro version: 2.0.8
- Docker version: 4.6.1

**Comment by jasonmccallister** [comment]
Hi, we are closing this issue as we have decided to retire Nitro, so no additional work will occur on this project. You can read the official blog post here https://craftcms.com/blog/retiring-craft-nitro. We appreciate everyones feedback and involvement and we look forward to refocusing our efforts on Cloud! 

If you're looking for a new local development environment, we recommend DDEV and have a knowledge base article to help you with the transition: https://craftcms.com/knowledge-base/migrating-from-craft-nitro-to-ddev.
