### ISSUE TITLE
Add php command

### ISSUE THREAD

**Issue by jasonmccallister** [craftcms/nitro#57]
Copying the idea from @angrybrad:

> could we do something like `nitro php ini` where we could pass in flags like --memory-limit=512M, --max_execution_time=120, etc?

**Comment by peirix** [comment]
Is there any way to modify the ini file today?

**Comment by jasonmccallister** [comment]
@peirix you can log into the machine and you are free the edit the php.ini manually using:

1. `nitro ssh`
2. `sudo vim /etc/php/7.4/fpm/php.ini`
3. `sudo service php7.4-fpm restart`

Just replace the version of PHP with your installed version.

**Comment by jasonmccallister** [comment]
This was added and released with 1.0!
