### ISSUE TITLE
machine soft delete weirdness

### ISSUE THREAD

**Issue by angrybrad** [craftcms/nitro#60]
If a machine has been soft-deleted and you run `nitro machine destroy` again, it should tell you that there are no machines to destroy instead of appearing like it destroyed the machine again.

**Comment by jasonmccallister** [comment]
We need to step up the user output big time, I'd like to get a few examples in place and make a decision on what information we should display.

**Comment by jasonmccallister** [comment]
Trying to delete a machine twice will result in the following message:

```
Permanently destroying global
delete failed: The following errors occurred:
instance "global" does not exist
Error: exit status 2
```

It's not ideal, but it's slightly better.
