### ISSUE TITLE
import command is broken with a ~/path/to/backup.sql type of path

### ISSUE THREAD

**Issue by angrybrad** [craftcms/nitro#75]

**Comment by angrybrad** [comment]
Still seems to be an issue:

```
❯ nitro import ~/Downloads/bckup.sql
Error: unable to locate the file "/Users/brad/Downloads/backup.sql" to import
```

**Comment by jasonmccallister** [comment]
I just pushed https://github.com/craftcms/nitro/commit/214efe9fde4e9e683623cda8d2b8b032f6d8846f which should resolve this issue. 

I did not add the `...` syntax yet, I'm not sure if we need to correct that yet.
