### ISSUE TITLE
import should default to nuking existing database

### ISSUE THREAD

**Issue by angrybrad** [craftcms/nitro#77]
Easiest way is to:

`DROP DATABASE nitro; CREATE DATABASE nitro;`

We could optionally add a flag to import over existing one, but it's probably the edge case.

**Comment by jasonmccallister** [comment]
should prompt before nuking the database.

**Comment by jasonmccallister** [comment]
So we ask for a new database during import, I think we can close this out since we do not use the default nitro database?

**Comment by angrybrad** [comment]
Yup, closing.
