### ISSUE TITLE
Detect the SQL file‘s DB engine before import

### ISSUE THREAD

**Issue by lukeholder** [craftcms/nitro#81]
Totally not required, but a wish.

Would be cool if we could look in the SQL file when doing an import to limit the options to a compatible database engine for that dump.
When I get a database from a customer I go to import, but can't tell from the filename whether it is mysql or psql, and opening the (sometimes large) file to find out is a pain.

Around here: https://github.com/craftcms/nitro/blob/develop/internal/cmd/import.go#L51
We could look in the first 50 lines of the sql file for strings.Contains("PostgreSQL") or "pg_dump", "MySQL"  etc and limit the database engines presented.

**Comment by jasonmccallister** [comment]
That would be pretty awesome, I think reading the contents of the SQL file makes a lot of sense. On larger files, that could use a lot of memory, so I’d have to look into a way to “stream” the content.

**Comment by jasonmccallister** [comment]
This has been added in v2, thank you for the work you did on the original functionality!
