### ISSUE TITLE
Add lifecycle events for script

### ISSUE THREAD

**Issue by angrybrad** [craftcms/nitro#87]
Would live in a `script:` key in yaml config files.

e.g.

`after_apply` – list of scripts that should be run each time `apply` is run.
`after_init` - list of scripts to run after machine init

Would be useful for things like creating default databases, importing database backups, etc.

**Comment by jasonmccallister** [comment]
Pondering on this one, but would these scripts run inside the machine or on the host machine?

**Comment by angrybrad** [comment]
Both?

Something like:

```
script:
  machine:
    after_apply:
      ...
    after_init:
      ...
  host:
    after_apply:
      ...
    after_init:
      ...
```

**Comment by simeon-smith** [comment]
So, how would setting up a database look in this since there won't be a configuration for specifying a project specific DB?

**Comment by simeon-smith** [comment]
Also, it would be great if `nitro add` would ask you if you wanted to create a database.

**Comment by jasonmccallister** [comment]
Hi, we are closing this issue as we have decided to retire Nitro, so no additional work will occur on this project. You can read the official blog post here https://craftcms.com/blog/retiring-craft-nitro. We appreciate everyones feedback and involvement and we look forward to refocusing our efforts on Cloud! 

If you're looking for a new local development environment, we recommend DDEV and have a knowledge base article to help you with the transition: https://craftcms.com/knowledge-base/migrating-from-craft-nitro-to-ddev.
