### ISSUE TITLE
MySQL should use a config cnf file to store client password

### ISSUE THREAD

**Issue by angrybrad** [craftcms/nitro#93]
https://dev.mysql.com/doc/refman/5.6/en/mysql-config-editor.html

That will prevent all of these warnings from appearing:

> mysql: [Warning] Using a password on the command line interface can be insecure.

**Comment by jasonmccallister** [comment]
Create a file at `/opt/nitro/mysql/my.cnf` with the contents:

```
[client]
user = nitro
password = nitro
```

Update the docker run command to send `--defaults-extra-file=/opt/nitro/mysql/my.cnf`

**Comment by jasonmccallister** [comment]
Will be resolved in beta 3!
