### ISSUE TITLE
MySQL 8 support

### ISSUE THREAD

**Issue by angrybrad** [craftcms/nitro#97]
Add it back in and change the default authentication plugin back to the MySQL 5.x native one: https://mysqlserverteam.com/upgrading-to-mysql-8-0-default-authentication-plugin-considerations/

**Comment by lukeholder** [comment]
Just an idea, a central list of configs changes like this should exist in the docs so that if someone moves their site to production they can ensure their production config of mysql8 can be configured the same.

**Comment by jasonmccallister** [comment]
@angrybrad I have added support for mysql.cnf files for beta 3. 

https://github.com/craftcms/nitro/blob/develop/internal/cmd/config.go#L20
https://github.com/craftcms/nitro/blob/develop/scripts/refresh.sh (this one still needs to get updated for the final changes)

I do wonder if we should add the authentication change (this will be used for add mysql databases) and if that would break anything?

I would also like to get some recommendations on any defaults we should set here.
