### ISSUE TITLE
"Error: open : no such file or directory" on nitro add

### ISSUE THREAD

**Issue by chasegiunta** [craftcms/nitro#98]
😕 I'm not sure how to provide any more helpful info in this case! The `web` directory is definitely _there_, but perhaps Nitro is trying to open something _else_ within `web`?

![image](https://user-images.githubusercontent.com/1377169/81105525-b1c8dd80-8ed9-11ea-93aa-7843ea9636cc.png)
![image](https://user-images.githubusercontent.com/1377169/81105659-dfae2200-8ed9-11ea-8f1b-cc2742f8f26c.png)

**Comment by jasonmccallister** [comment]
@chasegiunta thanks for the report. Can you provide the output of `nitro context` on this ticket and verify the `mounts` and `sites` paths look correct based on your setup?

**Comment by ademers** [comment]
I'm getting the same.

**Comment by jasonmccallister** [comment]
I just created a new machine and walked through adding a basic craft install and I cannot reproduce this issue.

Can you provide the following:

1. OS and version
2. Output of `nitro context`
3. If you can open and remove the site and mount from your nitro.yaml can you run `nitro add --debug` and provide the output?

<img width="1082" alt="Screen Shot 2020-05-05 at 3 24 16 PM" src="https://user-images.githubusercontent.com/5354908/81107190-c363b280-8ee4-11ea-8005-69b2d33235cd.png">

**Comment by chasegiunta** [comment]
`nitro context` outputs `Error: no configuration file being used`

**Comment by chasegiunta** [comment]
I think this is probably just a documentation error.

```
curl -sLS http://installer.getnitro.sh | bash
```
does not create a new machine, so that's probably what the issue is.

**Comment by jasonmccallister** [comment]
Ahh, ok. Did you run `nitro init` and follow the prompts?

**Comment by chasegiunta** [comment]
Nope! Just ran per documentation [here](https://getnitro.sh/) and [here](https://github.com/craftcms/nitro#installation) 😜

**Comment by jasonmccallister** [comment]
yep, we added the init call, but forgot to call it. Updating the install script now.

**Comment by ademers** [comment]
`nitro info` gives me `instance "nitro-dev" does not exist`

**Comment by jasonmccallister** [comment]
That makes sense @ademers - you need to run `nitro init` before calling add which the script is supposed to ask for you. I just updated the `install.sh` (https://github.com/craftcms/nitro/commit/6c7b92ca7f279db1cf1039db6ca295ae02023759) script so it will now prompt you to create a new machine.

Can you both run the installer again? It should now ask you to create the machine and prompt for details.

```sh
curl -sLS http://installer.getnitro.sh | bash
```

**Comment by ademers** [comment]
I get following when run installer command above. Also when prefixing with `sudo`. Is this normal?
```
Downloading package https://github.com/craftcms/nitro/releases/download/1.0.0-beta.1/nitro_darwin_x86_64.tar.gz to /Users/andreademers/temp_nitro_extract/nitro_darwin_x86_64.tar.gz

x CHANGELOG.md
x LICENSE.md
x README.md
x nitro

Download complete.

============================================================
  The script was run as a user who is unable to write
  to /usr/local/bin. To complete the installation the
  following commands may need to be run manually:
============================================================

  sudo cp ./nitro /usr/local/bin/nitro
  nitro
```

**Comment by jasonmccallister** [comment]
Your user does not have permissions, which makes sense. It won't prompt you to create a new machine in that case so you need to run `nitro init`. We should cleanup the error messages to check for a machine and be more explicit.

**Comment by ademers** [comment]
This may seem like a silly, question, but where should the command be run? My home dire in macOS Terminal or in the Multipass shell?

**Comment by jasonmccallister** [comment]
@ademers its a global command, so its anywhere you want to use it.

**Comment by ademers** [comment]
`nitro init`:
```
andreademers@Andreas-MacBook-Pro ~ $ nitro init
How many CPU cores? [2] 
How much memory? [4G] 
How much disk space? [40G] 
Which version of PHP? [7.4] 
Which database engine? [mysql] 
Which version of mysql? [5.7] 
Applying the changes now...
Waiting for initialization to complete /   
```

**Comment by jasonmccallister** [comment]
@ademers Ryan has a quick introduction that covers the first time setup if that is helpful: https://craftquest.io/courses/localhosting-craft-cms/26221

**Comment by ademers** [comment]
Got it sorted running `nitro init`:
```
Using config: /Users/andreademers/.nitro/nitro-dev.yaml
------
php: "7.4"
databases:
  - engine: mysql
    version: "5.7"
    port: "3306"
andreademers@Andreas-MacBook-Pro ~ $ nitro info
Name:           nitro-dev
State:          Running
IPv4:           192.168.64.3
Release:        Ubuntu 18.04.4 LTS
Image hash:     2f6bc5e7d9ac (Ubuntu 18.04 LTS)
Load:           0.80 0.67 0.31
Disk usage:     2.4G out of 38.6G
Memory usage:   373.0M out of 3.9G
```

**Comment by ademers** [comment]
Running `nitro add` assumes that I've already installed Craft. And Craft is typically installed via Composer. I don't have Composer installed in macOS, because I've been using Homestead which includes Composer. Do I need to install Composer in macOS? Or, should I install it in Multipass:
```
ubuntu@primary:~$ composer

Command 'composer' not found, but can be installed with:

sudo apt install composer

ubuntu@primary:~$ 
```

**Comment by byronrode** [comment]
Hey team, just an FYI, I ran this about 15 minutes ago, and I get the following error - I am using ZSH:

`bash: line 252: nit: command not found`

I went through the script and found the call for `nitro init` which is running at the moment (thanks slow interwebz), but not sure why it gives the error above. Last 18 lines of the current script I saw is below. 

```
      nitro
      init
    fi
  fi
}

init() {
  echo
  read -p "Initialize the primary machine now? " -n 1 -r
  echo
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    nitro init
  fi
}

hasCurl
hasMultipass
getNitro
init
```
