### ISSUE TITLE
bash: line 252: nit: command not found

### ISSUE THREAD

**Issue by byronrode** [craftcms/nitro#99]
Reposting here as #98 is now closed. If resolved, will close this.

--- 
Hey team, just an FYI, I ran this about 15 minutes ago, and I get the following error - I am using ZSH:

`bash: line 252: nit: command not found`

I went through the script and found the call for `nitro init` which is running at the moment (thanks slow interwebz), but not sure why it gives the error above. Last 18 lines of the current script I saw is below. 

```
      nitro
      init
    fi
  fi
}

init() {
  echo
  read -p "Initialize the primary machine now? " -n 1 -r
  echo
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    nitro init
  fi
}

hasCurl
hasMultipass
getNitro
init
```

_Originally posted by @byronrode in https://github.com/craftcms/nitro/issues/98#issuecomment-624294099_

**Comment by jasonmccallister** [comment]
@byronrode thank you for the report, we just pushed a change to resolve this. It might take a second for the DNS/cache from GitHub to catch up.
